-- hailsdotgo schema
-- Run once on your MySQL server to create the database and tables.

CREATE DATABASE IF NOT EXISTS hailsdotgo
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hailsdotgo;

CREATE TABLE IF NOT EXISTS users (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username   VARCHAR(32)  NOT NULL,
  email      VARCHAR(255) NOT NULL,
  password   VARCHAR(60)  NOT NULL,         -- bcrypt hash
  role       ENUM('user','admin') NOT NULL DEFAULT 'user',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username),
  UNIQUE KEY uk_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  token      CHAR(64)     NOT NULL,
  user_id    INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (token),
  KEY idx_expires (expires_at),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- form is '' for the default variant; shadow/purified/etc. are separate rows.
-- pokemon_id matches the name key from PoGoAPI shinies (e.g. "Bulbasaur").
CREATE TABLE IF NOT EXISTS user_shinies (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    INT UNSIGNED NOT NULL,
  pokemon_id VARCHAR(64)  NOT NULL,
  form       VARCHAR(32)  NOT NULL DEFAULT '',
  method     VARCHAR(32)  NOT NULL DEFAULT '',
  caught_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_shiny (user_id, pokemon_id, form),
  CONSTRAINT fk_shiny_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key   VARCHAR(64)  NOT NULL,
  setting_value VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO site_settings (setting_key, setting_value)
  VALUES ('registration_open', '0');

-- Single-use invite tokens generated by admins.
CREATE TABLE IF NOT EXISTS invites (
  token      CHAR(64)     NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME     NOT NULL,
  used_by    INT UNSIGNED DEFAULT NULL,
  used_at    DATETIME     DEFAULT NULL,
  PRIMARY KEY (token),
  KEY idx_invite_expires (expires_at),
  CONSTRAINT fk_invite_creator FOREIGN KEY (created_by)
    REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_invite_used FOREIGN KEY (used_by)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- After first deploy, register your admin account via the UI, then run:
--   UPDATE users SET role = 'admin' WHERE username = 'yourusername';
