-- hailsdotgo schema
-- Run once on your MySQL server to create the database and tables.

CREATE DATABASE IF NOT EXISTS hailsdotgo
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hailsdotgo;

CREATE TABLE IF NOT EXISTS users (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username   VARCHAR(32)  NOT NULL,
  email      VARCHAR(255) NOT NULL,
  password   VARCHAR(60)  NOT NULL,         -- bcrypt hash
  role       ENUM('user','tester','moderator','admin') NOT NULL DEFAULT 'user',
  disabled   TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_username (username),
  UNIQUE KEY uk_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  token      CHAR(64)     NOT NULL,
  user_id    INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (token),
  KEY idx_expires (expires_at),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- form is '' for the default variant; shadow/purified/etc. are separate rows.
-- pokemon_id matches the name key from PoGoAPI shinies (e.g. "Bulbasaur").
CREATE TABLE IF NOT EXISTS user_shinies (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    INT UNSIGNED NOT NULL,
  pokemon_id VARCHAR(64)  NOT NULL,
  form       VARCHAR(32)  NOT NULL DEFAULT '',
  method     VARCHAR(32)  NOT NULL DEFAULT '',
  caught_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_shiny (user_id, pokemon_id, form),
  CONSTRAINT fk_shiny_user FOREIGN KEY (user_id)
    REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key   VARCHAR(64)  NOT NULL,
  setting_value VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO site_settings (setting_key, setting_value)
  VALUES ('registration_open', '0');

INSERT IGNORE INTO site_settings (setting_key, setting_value) VALUES
  ('page_raids_enabled', '1'),
  ('page_dps_enabled', '1'),
  ('page_pvp_enabled', '1'),
  ('page_events_enabled', '1'),
  ('page_trainers_enabled', '1'),
  ('section_trainer_directory_enabled', '1'),
  ('section_raid_finder_enabled', '1'),
  ('page_shinies_enabled', '1');

-- Single-use invite tokens generated by admins.
CREATE TABLE IF NOT EXISTS invites (
  token      CHAR(64)     NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME     NOT NULL,
  used_by    INT UNSIGNED DEFAULT NULL,
  used_at    DATETIME     DEFAULT NULL,
  PRIMARY KEY (token),
  KEY idx_invite_expires (expires_at),
  CONSTRAINT fk_invite_creator FOREIGN KEY (created_by)
    REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_invite_used FOREIGN KEY (used_by)
    REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- After first deploy, register your admin account via the UI, then run:
--   UPDATE users SET role = 'admin' WHERE username = 'yourusername';

-- Migration: run these on existing installs to add moderator role and disabled flag.
--   ALTER TABLE users MODIFY COLUMN role ENUM('user','moderator','admin') NOT NULL DEFAULT 'user';
-- Migration: add tester role.
--   ALTER TABLE users MODIFY COLUMN role ENUM('user','tester','moderator','admin') NOT NULL DEFAULT 'user';
--   ALTER TABLE users ADD COLUMN disabled TINYINT(1) NOT NULL DEFAULT 0 AFTER role;

-- Migration: add trainer profile columns (settings page + trainer directory).
--   ALTER TABLE users ADD COLUMN trainer_name  VARCHAR(64)  NOT NULL DEFAULT '' AFTER disabled;
--   ALTER TABLE users ADD COLUMN trainer_code  VARCHAR(16)  NOT NULL DEFAULT '' AFTER trainer_name;
--   ALTER TABLE users ADD COLUMN avatar        VARCHAR(32)  NOT NULL DEFAULT '' AFTER trainer_name;
--   ALTER TABLE users ADD COLUMN city          VARCHAR(100) NOT NULL DEFAULT '' AFTER trainer_code;
--   ALTER TABLE users ADD COLUMN profile_public TINYINT(1)  NOT NULL DEFAULT 0  AFTER city;

-- Migration: add granular location fields for trainer directory privacy controls.
--   ALTER TABLE users ADD COLUMN region           VARCHAR(100) NOT NULL DEFAULT '' AFTER city;
--   ALTER TABLE users ADD COLUMN country          VARCHAR(100) NOT NULL DEFAULT '' AFTER region;
--   ALTER TABLE users ADD COLUMN location_display ENUM('none','country','full') NOT NULL DEFAULT 'none' AFTER country;

-- Migration: add pronouns field to user profiles.
--   ALTER TABLE users ADD COLUMN pronouns VARCHAR(32) NOT NULL DEFAULT '' AFTER avatar;

-- Migration: add directory_hidden flag for staff moderation.
--   ALTER TABLE users ADD COLUMN directory_hidden TINYINT(1) NOT NULL DEFAULT 0 AFTER profile_public;

-- Migration: add raid_banned flag for raid moderation.
--   ALTER TABLE users ADD COLUMN raid_banned TINYINT(1) NOT NULL DEFAULT 0 AFTER directory_hidden;

-- Migration: add favorite Pokémon fields to user profiles.
--   ALTER TABLE users ADD COLUMN fav_pokemon      VARCHAR(64)  NOT NULL DEFAULT '' AFTER raid_banned;
--   ALTER TABLE users ADD COLUMN fav_pokemon_form  VARCHAR(32)  NOT NULL DEFAULT '' AFTER fav_pokemon;
--   ALTER TABLE users ADD COLUMN fav_sprite_url    VARCHAR(255) NOT NULL DEFAULT '' AFTER fav_pokemon_form;

-- Migration: user strikes / penalty system.
--   CREATE TABLE IF NOT EXISTS user_strikes (
--     id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id        INT UNSIGNED NOT NULL,
--     reason         VARCHAR(255) NOT NULL DEFAULT '',
--     issued_by      INT UNSIGNED NOT NULL,
--     issued_by_name VARCHAR(32)  NOT NULL DEFAULT '',
--     created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_strike_user (user_id),
--     CONSTRAINT fk_strike_user   FOREIGN KEY (user_id)   REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_strike_issuer FOREIGN KEY (issued_by) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration: raid finder tables (run as a block).
--
--   CREATE TABLE IF NOT EXISTS raid_posts (
--     id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id         INT UNSIGNED NOT NULL,
--     boss_name       VARCHAR(64)  NOT NULL,
--     note            VARCHAR(160) NOT NULL DEFAULT '',
--     players_needed  TINYINT UNSIGNED NOT NULL DEFAULT 0,
--     weather_boosted TINYINT(1) NOT NULL DEFAULT 0,
--     created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     expires_at      DATETIME NOT NULL,
--     PRIMARY KEY (id),
--     KEY idx_raid_expires (expires_at),
--     CONSTRAINT fk_raidpost_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS raid_joins (
--     id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     post_id      INT UNSIGNED NOT NULL,
--     joiner_id    INT UNSIGNED NOT NULL,
--     confirmed    TINYINT(1) NOT NULL DEFAULT 0,
--     host_invited TINYINT(1) NOT NULL DEFAULT 0,
--     joined_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_join (post_id, joiner_id),
--     CONSTRAINT fk_join_post FOREIGN KEY (post_id) REFERENCES raid_posts (id) ON DELETE CASCADE,
--     CONSTRAINT fk_join_user FOREIGN KEY (joiner_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS raid_leave_log (
--     id       INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id  INT UNSIGNED NOT NULL,
--     left_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_leave_user_time (user_id, left_at),
--     CONSTRAINT fk_leave_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS raid_join_cooldowns (
--     user_id INT UNSIGNED NOT NULL,
--     until   DATETIME NOT NULL,
--     PRIMARY KEY (user_id),
--     CONSTRAINT fk_cooldown_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS raid_ratings (
--     id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     post_id    INT UNSIGNED NOT NULL,
--     rater_id   INT UNSIGNED NOT NULL,
--     rated_id   INT UNSIGNED NOT NULL,
--     score      TINYINT UNSIGNED NOT NULL,
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_rating (post_id, rater_id, rated_id),
--     CONSTRAINT fk_rating_rater FOREIGN KEY (rater_id) REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_rating_rated FOREIGN KEY (rated_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration: add queue status to raid_joins (run on VPS, no IF NOT EXISTS in MySQL 8).
--
--   ALTER TABLE raid_joins ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'accepted' AFTER host_invited;
--
-- Default 'accepted' preserves the existing open-join behaviour for rows created before this migration.

-- Migration: friendlier invite tokens (VARCHAR to support both old 64-char and new 8-char codes).
--   ALTER TABLE invites MODIFY COLUMN token VARCHAR(64) NOT NULL;

-- Migration: invite role assignment, multi-use codes, and pending staff confirmation.
--
--   ALTER TABLE invites ADD COLUMN granted_role ENUM('user','tester','moderator','admin') NOT NULL DEFAULT 'user' AFTER created_by;
--   ALTER TABLE invites ADD COLUMN max_uses TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER expires_at;
--   ALTER TABLE invites ADD COLUMN use_count TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER max_uses;
--   UPDATE invites SET use_count = 1 WHERE used_at IS NOT NULL;
--
--   ALTER TABLE users ADD COLUMN pending_role ENUM('tester','moderator','admin') NULL DEFAULT NULL AFTER role;

-- Migration: add API access permission flag to users (admin-only, superadmin-granted).
--
--   ALTER TABLE users ADD COLUMN api_access TINYINT(1) NOT NULL DEFAULT 0 AFTER role;

-- Migration: tag system (coloured label pills for admin users).
--
--   CREATE TABLE IF NOT EXISTS tags (
--     id    INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     name  VARCHAR(32)  NOT NULL,
--     color VARCHAR(7)   NOT NULL DEFAULT '#cccccc',
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_tag_name (name)
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS user_tags (
--     user_id INT UNSIGNED NOT NULL,
--     tag_id  INT UNSIGNED NOT NULL,
--     PRIMARY KEY (user_id, tag_id),
--     CONSTRAINT fk_ut_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_ut_tag  FOREIGN KEY (tag_id)  REFERENCES tags (id)  ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration: add raid XP, activity tracking, and rating weight to users.
--
--   ALTER TABLE users ADD COLUMN raid_xp     INT UNSIGNED         NOT NULL DEFAULT 0     AFTER raid_banned;
--   ALTER TABLE users ADD COLUMN last_raid_at DATETIME             NULL                   AFTER raid_xp;
--   ALTER TABLE users ADD COLUMN rater_weight DECIMAL(4,3)         NOT NULL DEFAULT 1.000 AFTER last_raid_at;
--   ALTER TABLE users ADD COLUMN last_seen_at DATETIME             NULL                   AFTER rater_weight;
--
-- raid_xp: cumulative XP for ranking (15 per confirmed join, 20 per host invite, 3–5 for high ratings received).
-- last_raid_at: used to compute rating decay for inactive hosts.
-- rater_weight: consensus-based reliability weight, recomputed after each rating.

-- Migration: user language preference (i18n support).
--   ALTER TABLE users ADD COLUMN lang VARCHAR(8) NOT NULL DEFAULT 'en' AFTER email;

-- Migration: store system (PayPal payments, queue priority, custom tags).
--
--   CREATE TABLE IF NOT EXISTS store_items (
--     id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     name        VARCHAR(64)  NOT NULL,
--     slug        VARCHAR(32)  NOT NULL,
--     description TEXT         NOT NULL,   -- no DEFAULT: TEXT can't have one in strict mode
--     price_cents INT UNSIGNED NOT NULL,
--     type        ENUM('one_time','monthly','bimonthly') NOT NULL DEFAULT 'one_time',
--     benefit     VARCHAR(32)  NOT NULL DEFAULT '',
--     active      TINYINT(1)   NOT NULL DEFAULT 1,
--     sort_order  TINYINT UNSIGNED NOT NULL DEFAULT 0,
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_slug (slug)
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS purchases (
--     id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id         INT UNSIGNED NOT NULL,
--     item_id         INT UNSIGNED NOT NULL,
--     paypal_order_id VARCHAR(64)  NOT NULL DEFAULT '',
--     status          ENUM('pending','completed','refunded','cancelled') NOT NULL DEFAULT 'pending',
--     created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     completed_at    DATETIME NULL,
--     expires_at      DATETIME NULL,
--     PRIMARY KEY (id),
--     KEY idx_purchase_user (user_id),
--     CONSTRAINT fk_purchase_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_purchase_item FOREIGN KEY (item_id) REFERENCES store_items (id)
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS custom_tag_requests (
--     id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id       INT UNSIGNED NOT NULL,
--     name          VARCHAR(32)  NOT NULL,
--     color         VARCHAR(7)   NOT NULL DEFAULT '#cccccc',
--     status        ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
--     reviewed_by   INT UNSIGNED NULL,
--     reviewed_at   DATETIME NULL,
--     reject_reason VARCHAR(255) NOT NULL DEFAULT '',
--     created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_ctr_status (status),
--     CONSTRAINT fk_ctr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   ALTER TABLE custom_tag_requests
--     MODIFY COLUMN status ENUM('pending','approved','rejected','revision') NOT NULL DEFAULT 'pending';
--
--   ALTER TABLE raid_joins ADD COLUMN priority TINYINT(1) NOT NULL DEFAULT 0 AFTER status;
--
--   INSERT IGNORE INTO site_settings (setting_key, setting_value) VALUES ('store_enabled', '0');
--
--   INSERT IGNORE INTO store_items (name, slug, description, price_cents, type, benefit, sort_order) VALUES
--     ('Supporter Pack', 'supporter',
--      'Submit a custom tag (staff-reviewed) that appears on your trainer profile. Includes a Supporter badge.',
--      299, 'bimonthly', 'supporter', 1),
--     ('Priority Pass', 'priority_pass',
--      'Jump to the front of the raid join queue for 30 days.',
--      799, 'monthly', 'queue_priority', 2);
-- last_seen_at: updated on every HTML page render; online = within last 5 minutes.

-- Migration: add boss tier to raid posts so the lobby can display it.
--
--   ALTER TABLE raid_posts ADD COLUMN boss_tier TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER boss_name;

-- No schema change required for Trainer Directory "show all users" update.
-- profile_public now means "show full profile" instead of "appear in directory".
-- All non-disabled, non-hidden users appear; profile_public gates rich details.

-- Migration: custom tag weekly cooldown + color rate limiting (2026-06-06).
--
--   ALTER TABLE users
--     ADD COLUMN tag_requested_at DATETIME NULL AFTER last_seen_at;
--
--   CREATE TABLE IF NOT EXISTS tag_color_changes (
--     id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id    INT UNSIGNED NOT NULL,
--     changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_tcc_user_time (user_id, changed_at),
--     CONSTRAINT fk_tcc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration: account suspension reason (2026-06-06).
--
--   ALTER TABLE users
--     ADD COLUMN disabled_reason VARCHAR(255) NOT NULL DEFAULT '' AFTER disabled;

-- Migration: translator permission + pending translation edits (2026-06-10).
-- translator is toggled by the superadmin only; translation_edits holds pending
-- locale changes submitted by translators and reviewed by admins. t_key is the
-- locale string key ("key" is reserved in MySQL). old_text snapshots the merged
-- value at submit time so reviewers can see if it changed before approval.
--
--   ALTER TABLE users
--     ADD COLUMN translator TINYINT(1) NOT NULL DEFAULT 0 AFTER api_access;
--
--   CREATE TABLE IF NOT EXISTS translation_edits (
--     id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id       INT UNSIGNED NOT NULL,
--     lang          CHAR(2)      NOT NULL,
--     t_key         VARCHAR(191) NOT NULL,
--     old_text      TEXT         NOT NULL,
--     new_text      TEXT         NOT NULL,
--     status        ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
--     reviewed_by   INT UNSIGNED NULL,
--     reviewed_at   DATETIME NULL,
--     reject_reason VARCHAR(255) NOT NULL DEFAULT '',
--     created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_te_status (status),
--     KEY idx_te_user_lang_key (user_id, lang, t_key),
--     CONSTRAINT fk_te_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_te_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migration: Raid Finder v2 lobby matchmaking + trust + awards (2026-06-10).
-- Replaces the browse-and-join raid post board with per-boss matchmaking
-- queues, host lobbies with server-enforced timers, a behavioral trust
-- system (replaces 1-5 star ratings), and a community awards system.
-- Old tables (raid_posts, raid_joins, raid_ratings) stay for history; v2
-- stops writing to them. raid_leave_log and raid_join_cooldowns are REUSED.
-- users.rater_weight is repurposed as trust report reliability (same range).
-- users.raid_xp / last_raid_at are unchanged (rank ladder stays).
--
--   CREATE TABLE IF NOT EXISTS raid_lobbies (
--     id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     host_id         INT UNSIGNED NOT NULL,
--     boss_name       VARCHAR(64)  NOT NULL,
--     boss_tier       TINYINT UNSIGNED NOT NULL DEFAULT 0,
--     is_custom       TINYINT(1)   NOT NULL DEFAULT 0,
--     note            VARCHAR(160) NOT NULL DEFAULT '',
--     weather_boosted TINYINT(1)   NOT NULL DEFAULT 0,
--     max_members     TINYINT UNSIGNED NOT NULL DEFAULT 5,
--     state           ENUM('open','full','raiding','reported','cancelled','expired') NOT NULL DEFAULT 'open',
--     invite_deadline DATETIME NULL,
--     created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     expires_at      DATETIME NOT NULL,
--     closed_at       DATETIME NULL,
--     PRIMARY KEY (id),
--     KEY idx_lobby_state_boss (state, boss_name, created_at),
--     KEY idx_lobby_expires (expires_at),
--     CONSTRAINT fk_lobby_host FOREIGN KEY (host_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   CREATE TABLE IF NOT EXISTS raid_lobby_members (
--     id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     lobby_id         INT UNSIGNED NOT NULL,
--     user_id          INT UNSIGNED NOT NULL,
--     state            ENUM('matched','confirmed','timed_out','left','removed','requeued') NOT NULL DEFAULT 'matched',
--     priority         TINYINT(1) NOT NULL DEFAULT 0,
--     matched_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     confirm_deadline DATETIME NOT NULL,
--     confirmed_at     DATETIME NULL,
--     attended         TINYINT(1) NULL,
--     left_early       TINYINT(1) NOT NULL DEFAULT 0,
--     raid_success     TINYINT(1) NULL,
--     host_vote        ENUM('none','commend','dislike') NOT NULL DEFAULT 'none',
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_lobby_member (lobby_id, user_id),
--     KEY idx_member_user (user_id, state),
--     CONSTRAINT fk_lm_lobby FOREIGN KEY (lobby_id) REFERENCES raid_lobbies (id) ON DELETE CASCADE,
--     CONSTRAINT fk_lm_user  FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   -- One queue slot per user. enqueued_at is millisecond precision and is
--   -- PRESERVED when members are returned to the queue, so they re-enter at
--   -- the front. last_seen_at is the poll heartbeat; stale rows are evicted.
--   CREATE TABLE IF NOT EXISTS raid_queue (
--     user_id      INT UNSIGNED NOT NULL,
--     boss_name    VARCHAR(64)  NOT NULL,
--     boss_tier    TINYINT UNSIGNED NOT NULL DEFAULT 0,
--     priority     TINYINT(1)   NOT NULL DEFAULT 0,
--     enqueued_at  DATETIME(3)  NOT NULL,
--     last_seen_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (user_id),
--     KEY idx_queue_boss (boss_name, priority, enqueued_at),
--     CONSTRAINT fk_rq_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   -- Source of truth for trust. users.trust_score caches SUM(applied_delta).
--   -- actor_id NULL means a system event (timeouts, window expiry).
--   -- uk_te_vote makes commend/dislike idempotent per lobby per pair.
--   CREATE TABLE IF NOT EXISTS trust_events (
--     id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     user_id       INT UNSIGNED NOT NULL,
--     actor_id      INT UNSIGNED NULL,
--     lobby_id      INT UNSIGNED NULL,
--     event_type    ENUM('commend','dislike','confirm_timeout','invite_window_fail','left_early','raid_success','staff_adjust') NOT NULL,
--     raw_delta     DECIMAL(6,2) NOT NULL,
--     weight        DECIMAL(4,3) NOT NULL DEFAULT 1.000,
--     applied_delta DECIMAL(6,2) NOT NULL,
--     note          VARCHAR(255) NOT NULL DEFAULT '',
--     created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     KEY idx_te_user (user_id, created_at),
--     KEY idx_te_actor (actor_id, event_type, created_at),
--     UNIQUE KEY uk_te_vote (lobby_id, actor_id, user_id, event_type),
--     CONSTRAINT fk_tev_user  FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_tev_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   ALTER TABLE users ADD COLUMN trust_score DECIMAL(7,2) NOT NULL DEFAULT 0.00 AFTER rater_weight;
--   ALTER TABLE users ADD COLUMN special_rank ENUM('','trusted','content_creator') NOT NULL DEFAULT '' AFTER trust_score;
--
--   CREATE TABLE IF NOT EXISTS awards (
--     id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     slug        VARCHAR(32)  NOT NULL,
--     name        VARCHAR(64)  NOT NULL,
--     description VARCHAR(255) NOT NULL DEFAULT '',
--     icon        VARCHAR(16)  NOT NULL DEFAULT '🏆',
--     color       VARCHAR(7)   NOT NULL DEFAULT '#f0b429',
--     active      TINYINT(1)   NOT NULL DEFAULT 1,
--     sort_order  TINYINT UNSIGNED NOT NULL DEFAULT 0,
--     created_by  INT UNSIGNED NULL,
--     created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_award_slug (slug),
--     CONSTRAINT fk_award_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   -- Same award from different granters stacks; one granter can't repeat it.
--   CREATE TABLE IF NOT EXISTS award_grants (
--     id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     award_id     INT UNSIGNED NOT NULL,
--     recipient_id INT UNSIGNED NOT NULL,
--     granter_id   INT UNSIGNED NULL,
--     note         VARCHAR(160) NOT NULL DEFAULT '',
--     created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     UNIQUE KEY uk_grant_once (award_id, recipient_id, granter_id),
--     KEY idx_grant_recipient (recipient_id),
--     CONSTRAINT fk_ag_award     FOREIGN KEY (award_id)     REFERENCES awards (id) ON DELETE CASCADE,
--     CONSTRAINT fk_ag_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE,
--     CONSTRAINT fk_ag_granter   FOREIGN KEY (granter_id)   REFERENCES users (id) ON DELETE SET NULL
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   INSERT IGNORE INTO site_settings (setting_key, setting_value) VALUES
--     ('awards_community_grants_enabled', '0'),
--     ('awards_grant_min_trust', '50'),
--     ('raid_custom_lobby_min_trust', '50');
--
--   INSERT IGNORE INTO awards (slug, name, description, icon, color, sort_order) VALUES
--     ('helping-hand', 'Helping Hand', 'Goes out of their way to help other trainers', '🤝', '#4caf50', 1),
--     ('friend-ball',  'Friend Ball',  'Welcoming and friendly to everyone in lobbies', '💚', '#7bd389', 2),
--     ('professors-aide', 'Professor''s Aide', 'Great teacher: explains counters, mechanics, and strategy', '📚', '#5b9cf6', 3),
--     ('ace-trainer', 'Ace Trainer', 'A role model for the community', '⭐', '#f0b429', 4),
--     ('joyful-spirit', 'Joyful Spirit', 'Keeps raids fun and positive', '🎉', '#e91e63', 5);
--
-- After v2 has been stable for a release, retire the legacy tables manually:
--   DROP TABLE raid_ratings;   -- replaced by trust_events
--   DROP TABLE raid_joins;     -- replaced by raid_lobby_members
--   DROP TABLE raid_posts;     -- replaced by raid_lobbies

-- Migration: runtime locale registry (2026-06-10).
-- Translators can create new locales from /translate; they stay hidden from
-- the public language switcher until an admin enables them. en is implicit
-- (always enabled, never editable) and is not stored here. es/fr/de are
-- seeded enabled to match the previously hardcoded switcher.
--
--   CREATE TABLE IF NOT EXISTS locales (
--     code       CHAR(2)      NOT NULL,
--     enabled    TINYINT(1)   NOT NULL DEFAULT 0,
--     created_by INT UNSIGNED NULL,
--     created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (code),
--     CONSTRAINT fk_loc_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   INSERT INTO locales (code, enabled) VALUES ('es', 1), ('fr', 1), ('de', 1);
