// Costume resolution, sharing its data with the Go side rather than duplicating it.
//
//   internal/costumes/catalog.json  GENERATED by `make costumes` from the mined PokeMiners
//                                   asset tree: every costume code that has shiny art, and
//                                   exactly which species have it. Never hand-edited.
//   internal/costumes/labels.json   CURATED: the human labels trainers see and type.
//
// Both files are also go:embed'ed by internal/costumes, so the two resolvers cannot drift.
// Resolution requires a catalog hit, so a label whose art does not exist upstream is simply
// inert: a costume can be recorded before its release without any "pending" bookkeeping.
import catalog from "../../internal/costumes/catalog.json";
import labelData from "../../internal/costumes/labels.json";

type Catalog = { assetBase: string; codes: Record<string, { pretty: string; dex: number[] }> };
type Labels = {
  species: Record<string, Record<string, string>>;
  shared: { label: string; code: string }[];
  aliases: Record<string, string>;
  hidden: string[];
};

const CAT = catalog as unknown as Catalog;

// Labels are the one part of this that changes at runtime: an admin can name a costume in the
// admin panel, and it lands in an overlay on the server rather than in the file compiled in here.
// The shinies and trainer templates inject the MERGED set as COSTUME_LABELS, so the picker knows
// about a costume named since the last deploy. Any page without the injection (or a server that
// failed to marshal it) falls back to the compiled-in copy and behaves exactly as before.
declare const COSTUME_LABELS: Labels | null | undefined;
const injected = typeof COSTUME_LABELS !== "undefined" ? COSTUME_LABELS : null;
const LAB = (injected ?? (labelData as unknown as Labels)) as Labels;

// Sprites are proxied and cached by us, never hotlinked from the asset host.
const SPRITE_PATH = "/api/costume-sprite/";

export const TINY_POKEMON = new Set<number>([
  // Baby Pokemon
  172, 173, 174, 175, 236, 238, 239, 240,
  298, 360, 406, 433, 438, 439, 440, 446, 447, 458,
  // Small mythicals and user-called-out tiny Pokemon
  151, 251, 311, 312, 385, 490, 494,
  // Other notoriously small sprites
  595,       // Joltik
  669, 670,  // Flabebe, Floette
  742, 743,  // Cutiefly, Ribombee
]);

// covers: does this code have shiny art for this species?
function covers(code: string, dexId: number): boolean {
  return CAT.codes[code]?.dex.includes(dexId) ?? false;
}

// A curated override wins, else a shared costume the species is eligible for. Both tiers
// require the code to have shiny art for this dex, so an unknown or stale label just misses.
function resolve(dexId: number, pokemonName: string, costumeLabel: string): string | null {
  if (!costumeLabel || !dexId) return null;
  const label = LAB.aliases[costumeLabel] ?? costumeLabel;

  const override = LAB.species[pokemonName]?.[label];
  if (override && covers(override, dexId)) return override;

  const shared = LAB.shared.find((s) => s.label === label && covers(s.code, dexId));
  return shared ? shared.code : null;
}

// pm25.cANNIVERSARY.s.icon.png -- the code carries its own prefix ("c:" or "f:").
function assetFile(dexId: number, code: string): string {
  const [p, name] = [code.slice(0, 1), code.slice(2)];
  return `pm${dexId}.${p}${name}.s.icon.png`;
}

export function costumeShinyUrl(dexId: number, pokemonName: string, costumeLabel: string): string | null {
  const code = resolve(dexId, pokemonName, costumeLabel);
  return code ? SPRITE_PATH + assetFile(dexId, code) : null;
}

// Costume labels to offer for a species: its curated overrides, then any shared costume it is
// eligible for, skipping a code an override already covers so the same art is never offered
// under two labels. Overrides are sorted so the picker matches the Go resolver exactly.
export function costumeLabelsForDex(dexId: number, pokemonName: string): string[] {
  const labels: string[] = [];
  const usedCodes = new Set<string>();

  for (const [label, code] of Object.entries(LAB.species[pokemonName] ?? {})) {
    if (!covers(code, dexId)) continue;
    labels.push(label);
    usedCodes.add(code);
  }
  labels.sort();

  for (const s of LAB.shared) {
    if (usedCodes.has(s.code) || labels.includes(s.label) || !covers(s.code, dexId)) continue;
    labels.push(s.label);
  }
  return labels;
}
