// Costume resolution, sharing its data with the Go side rather than duplicating it.
//
//   internal/costumes/catalog.json  GENERATED by `make costumes` from the mined PokeMiners
//                                   asset tree: every costume code that has shiny art, and
//                                   exactly which species have it. Never hand-edited.
//   internal/costumes/labels.json   CURATED: the human labels trainers see and type.
//
// Both files are also go:embed'ed by internal/costumes, so the two resolvers cannot drift.
// Resolution requires a catalog hit, so a label whose art does not exist upstream is simply
// inert: a costume can be recorded before its release without any "pending" bookkeeping.
import catalog from "../../internal/costumes/catalog.json";
import labelData from "../../internal/costumes/labels.json";
import type { PickerEntry } from "./picker";

type Catalog = { assetBase: string; codes: Record<string, { pretty: string; dex: number[] }> };
type Labels = {
  species: Record<string, Record<string, string>>;
  shared: { label: string; code: string }[];
  aliases: Record<string, string>;
  hidden: string[];
};

// The catalog changes at runtime too, for the same reason labels do: the discovery job can admit
// a costume the game shipped after our last deploy, and it lands in an overlay on the server
// rather than in the file compiled in here. The shinies and trainer templates inject whatever the
// compiled-in copy is missing as COSTUME_CATALOG. Without this a discovered costume would resolve
// on public profiles and in the app but stay untypeable in the picker, which is the same bug one
// step further down the pipe.
declare const COSTUME_CATALOG: Record<string, { pretty: string; dex: number[] }> | null | undefined;
const catalogDelta = typeof COSTUME_CATALOG !== "undefined" ? (COSTUME_CATALOG ?? {}) : {};

// Costumes that exist but are not in the game yet. Injected the same way, and deliberately NOT
// merged into the resolver: they must be shown and refused, so resolve() must keep missing them
// while the picker still offers a grayed row.
declare const COSTUME_UPCOMING: { code: string; label: string; release_date?: string }[] | null | undefined;
const UPCOMING = typeof COSTUME_UPCOMING !== "undefined" ? (COSTUME_UPCOMING ?? []) : [];
const CAT: Catalog = {
  ...(catalog as unknown as Catalog),
  codes: { ...(catalog as unknown as Catalog).codes, ...catalogDelta },
};

// Labels are the one part of this that changes at runtime: an admin can name a costume in the
// admin panel, and it lands in an overlay on the server rather than in the file compiled in here.
// The shinies and trainer templates inject the MERGED set as COSTUME_LABELS, so the picker knows
// about a costume named since the last deploy. Any page without the injection (or a server that
// failed to marshal it) falls back to the compiled-in copy and behaves exactly as before.
declare const COSTUME_LABELS: Labels | null | undefined;
const injected = typeof COSTUME_LABELS !== "undefined" ? COSTUME_LABELS : null;
const LAB = (injected ?? (labelData as unknown as Labels)) as Labels;

// Sprites are proxied and cached by us, never hotlinked from the asset host.
const SPRITE_PATH = "/api/costume-sprite/";

export const TINY_POKEMON = new Set<number>([
  // Baby Pokemon
  172, 173, 174, 175, 236, 238, 239, 240,
  298, 360, 406, 433, 438, 439, 440, 446, 447, 458,
  // Small mythicals and user-called-out tiny Pokemon
  151, 251, 311, 312, 385, 490, 494,
  // Other notoriously small sprites
  595,       // Joltik
  669, 670,  // Flabebe, Floette
  742, 743,  // Cutiefly, Ribombee
]);

// covers: does this code have shiny art for this species?
function covers(code: string, dexId: number): boolean {
  return CAT.codes[code]?.dex.includes(dexId) ?? false;
}

// A curated override wins, else a shared costume the species is eligible for. Both tiers
// require the code to have shiny art for this dex, so an unknown or stale label just misses.
function resolve(dexId: number, pokemonName: string, costumeLabel: string): string | null {
  if (!costumeLabel || !dexId) return null;
  const label = LAB.aliases[costumeLabel] ?? costumeLabel;

  const override = LAB.species[pokemonName]?.[label];
  if (override && covers(override, dexId)) return override;

  const shared = LAB.shared.find((s) => s.label === label && covers(s.code, dexId));
  return shared ? shared.code : null;
}

// Other spellings that resolve to a label. This is the reverse of the aliases map, which runs
// typed text -> label, and it exists so the picker can MATCH on the name the game uses while
// still SHOWING ours: searching "Professor Willow's assistant" has to find "Willow's Lab Coat".
export function costumeAliasesFor(label: string): string[] {
  return Object.entries(LAB.aliases)
    .filter(([, canonical]) => canonical === label)
    .map(([alias]) => alias);
}

// The costume field used to be an <input list> pointing at a <datalist>. Desktop browsers
// autocompleted it; mobile browsers render datalist suggestions inconsistently, and on a phone the
// list did not appear at all, which made every costume invisible to anyone who did not already know
// its exact label. A trainer reported the Willow costume as missing for that reason. These entries
// drive a createPicker dropdown instead, which renders itself and so behaves the same everywhere.
//
// Each row carries its shiny sprite, because a costume is far easier to recognise than to name.
export function costumeEntries(dexId: number, pokemonName: string): PickerEntry[] {
  const entries: PickerEntry[] = costumeLabelsForDex(dexId, pokemonName).map((label, i) => ({
    key: label,
    name: label,
    label,
    sprite: costumeShinyUrl(dexId, pokemonName, label),
    aliases: costumeAliasesFor(label),
    types: [],
    group: i,
  }));

  // Then the ones that are coming: grayed, unselectable, and last, so they never sit between two
  // costumes a trainer can actually choose.
  for (const u of UPCOMING) {
    const e = CAT.codes[u.code];
    if (!e || !e.dex.includes(dexId)) continue;
    entries.push({
      key: "upcoming:" + u.code,
      name: u.label,
      label: u.label,
      sprite: SPRITE_PATH + assetFile(dexId, u.code),
      types: [],
      tag: u.release_date ? u.release_date : "soon",
      group: 1000,
      unavailable: true,
    });
  }
  return entries;
}

// pm25.cANNIVERSARY.s.icon.png -- the code carries its own prefix ("c:" or "f:").
function assetFile(dexId: number, code: string): string {
  const [p, name] = [code.slice(0, 1), code.slice(2)];
  return `pm${dexId}.${p}${name}.s.icon.png`;
}

export function costumeShinyUrl(dexId: number, pokemonName: string, costumeLabel: string): string | null {
  const code = resolve(dexId, pokemonName, costumeLabel);
  return code ? SPRITE_PATH + assetFile(dexId, code) : null;
}

// Costume labels to offer for a species: its curated overrides, then any shared costume it is
// eligible for, skipping a code an override already covers so the same art is never offered
// under two labels. Overrides are sorted so the picker matches the Go resolver exactly.
export function costumeLabelsForDex(dexId: number, pokemonName: string): string[] {
  const labels: string[] = [];
  const usedCodes = new Set<string>();

  for (const [label, code] of Object.entries(LAB.species[pokemonName] ?? {})) {
    if (!covers(code, dexId)) continue;
    labels.push(label);
    usedCodes.add(code);
  }
  labels.sort();

  for (const s of LAB.shared) {
    if (usedCodes.has(s.code) || labels.includes(s.label) || !covers(s.code, dexId)) continue;
    labels.push(s.label);
  }
  return labels;
}
