import { Region, shinyRegionalForms } from "./regionalForms";

// Maps each Pokemon name (as used in GO/our data) to the name(s) it can evolve into.
// Only GO-relevant forms included. Branching evolutions list all options.
// Entries with [] are final forms, legendaries, or have no GO evolution path.
// Regional variants with different targets live in REGIONAL_EVOLUTION_NEXT below.
export const EVOLUTION_NEXT: Record<string, string[]> = {
  // Gen 1
  "Bulbasaur":    ["Ivysaur"],
  "Ivysaur":      ["Venusaur"],
  "Charmander":   ["Charmeleon"],
  "Charmeleon":   ["Charizard"],
  "Squirtle":     ["Wartortle"],
  "Wartortle":    ["Blastoise"],
  "Caterpie":     ["Metapod"],
  "Metapod":      ["Butterfree"],
  "Weedle":       ["Kakuna"],
  "Kakuna":       ["Beedrill"],
  "Pidgey":       ["Pidgeotto"],
  "Pidgeotto":    ["Pidgeot"],
  "Rattata":      ["Raticate"],
  "Spearow":      ["Fearow"],
  "Ekans":        ["Arbok"],
  "Pichu":        ["Pikachu"],
  "Pikachu":      ["Raichu"],
  "Sandshrew":    ["Sandslash"],
  "Nidoran♀":    ["Nidorina"],
  "Nidorina":     ["Nidoqueen"],
  "Nidoran♂":    ["Nidorino"],
  "Nidorino":     ["Nidoking"],
  "Cleffa":       ["Clefairy"],
  "Clefairy":     ["Clefable"],
  "Vulpix":       ["Ninetales"],
  "Igglybuff":    ["Jigglypuff"],
  "Jigglypuff":   ["Wigglytuff"],
  "Zubat":        ["Golbat"],
  "Golbat":       ["Crobat"],
  "Oddish":       ["Gloom"],
  "Gloom":        ["Vileplume", "Bellossom"],
  "Paras":        ["Parasect"],
  "Venonat":      ["Venomoth"],
  "Diglett":      ["Dugtrio"],
  "Meowth":       ["Persian"],
  "Psyduck":      ["Golduck"],
  "Mankey":       ["Primeape"],
  "Primeape":     ["Annihilape"],
  "Growlithe":    ["Arcanine"],
  "Poliwag":      ["Poliwhirl"],
  "Poliwhirl":    ["Poliwrath", "Politoed"],
  "Abra":         ["Kadabra"],
  "Kadabra":      ["Alakazam"],
  "Machop":       ["Machoke"],
  "Machoke":      ["Machamp"],
  "Bellsprout":   ["Weepinbell"],
  "Weepinbell":   ["Victreebel"],
  "Tentacool":    ["Tentacruel"],
  "Geodude":      ["Graveler"],
  "Graveler":     ["Golem"],
  "Ponyta":       ["Rapidash"],
  "Slowpoke":     ["Slowbro", "Slowking"],
  "Magnemite":    ["Magneton"],
  "Magneton":     ["Magnezone"],
  "Doduo":        ["Dodrio"],
  "Seel":         ["Dewgong"],
  "Grimer":       ["Muk"],
  "Shellder":     ["Cloyster"],
  "Gastly":       ["Haunter"],
  "Haunter":      ["Gengar"],
  "Drowzee":      ["Hypno"],
  "Krabby":       ["Kingler"],
  "Voltorb":      ["Electrode"],
  "Exeggcute":    ["Exeggutor"],
  "Cubone":       ["Marowak"],
  "Tyrogue":      ["Hitmonlee", "Hitmonchan", "Hitmontop"],
  "Lickitung":    ["Lickilicky"],
  "Koffing":      ["Weezing"],
  "Rhyhorn":      ["Rhydon"],
  "Rhydon":       ["Rhyperior"],
  "Chansey":      ["Blissey"],
  "Tangela":      ["Tangrowth"],
  "Horsea":       ["Seadra"],
  "Seadra":       ["Kingdra"],
  "Goldeen":      ["Seaking"],
  "Staryu":       ["Starmie"],
  "Mr. Mime":     [], // only Galarian Mr. Mime evolves (to Mr. Rime); see REGIONAL_EVOLUTION_NEXT
  "Scyther":      ["Scizor", "Kleavor"],
  "Smoochum":     ["Jynx"],
  "Elekid":       ["Electabuzz"],
  "Electabuzz":   ["Electivire"],
  "Magby":        ["Magmar"],
  "Magmar":       ["Magmortar"],
  "Magikarp":     ["Gyarados"],
  "Eevee":        ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"],
  "Omanyte":      ["Omastar"],
  "Kabuto":       ["Kabutops"],
  "Dratini":      ["Dragonair"],
  "Dragonair":    ["Dragonite"],
  // Gen 2
  "Chikorita":    ["Bayleef"],
  "Bayleef":      ["Meganium"],
  "Cyndaquil":    ["Quilava"],
  "Quilava":      ["Typhlosion"],
  "Totodile":     ["Croconaw"],
  "Croconaw":     ["Feraligatr"],
  "Sentret":      ["Furret"],
  "Hoothoot":     ["Noctowl"],
  "Ledyba":       ["Ledian"],
  "Spinarak":     ["Ariados"],
  "Chinchou":     ["Lanturn"],
  "Togepi":       ["Togetic"],
  "Togetic":      ["Togekiss"],
  "Natu":         ["Xatu"],
  "Mareep":       ["Flaaffy"],
  "Flaaffy":      ["Ampharos"],
  "Marill":       ["Azumarill"],
  "Azurill":      ["Marill"],
  "Hoppip":       ["Skiploom"],
  "Skiploom":     ["Jumpluff"],
  "Aipom":        ["Ambipom"],
  "Sunkern":      ["Sunflora"],
  "Yanma":        ["Yanmega"],
  "Wooper":       ["Quagsire"],
  "Murkrow":      ["Honchkrow"],
  "Misdreavus":   ["Mismagius"],
  "Girafarig":    ["Farigiraf"],
  "Pineco":       ["Forretress"],
  "Dunsparce":    ["Dudunsparce"],
  "Gligar":       ["Gliscor"],
  "Snubbull":     ["Granbull"],
  "Qwilfish":     [], // only Hisuian Qwilfish evolves (to Overqwil); see REGIONAL_EVOLUTION_NEXT
  "Sneasel":      ["Weavile"],
  "Teddiursa":    ["Ursaring"],
  "Ursaring":     ["Ursaluna"],
  "Slugma":       ["Magcargo"],
  "Swinub":       ["Piloswine"],
  "Piloswine":    ["Mamoswine"],
  "Remoraid":     ["Octillery"],
  "Mantyke":      ["Mantine"],
  "Houndour":     ["Houndoom"],
  "Phanpy":       ["Donphan"],
  "Stantler":     ["Wyrdeer"],
  "Larvitar":     ["Pupitar"],
  "Pupitar":      ["Tyranitar"],
  // Gen 3
  "Treecko":      ["Grovyle"],
  "Grovyle":      ["Sceptile"],
  "Torchic":      ["Combusken"],
  "Combusken":    ["Blaziken"],
  "Mudkip":       ["Marshtomp"],
  "Marshtomp":    ["Swampert"],
  "Poochyena":    ["Mightyena"],
  "Zigzagoon":    ["Linoone"],
  "Linoone":      [], // only Galarian Linoone evolves (to Obstagoon); see REGIONAL_EVOLUTION_NEXT
  "Wurmple":      ["Silcoon", "Cascoon"],
  "Silcoon":      ["Beautifly"],
  "Cascoon":      ["Dustox"],
  "Lotad":        ["Lombre"],
  "Lombre":       ["Ludicolo"],
  "Seedot":       ["Nuzleaf"],
  "Nuzleaf":      ["Shiftry"],
  "Taillow":      ["Swellow"],
  "Wingull":      ["Pelipper"],
  "Ralts":        ["Kirlia"],
  "Kirlia":       ["Gardevoir", "Gallade"],
  "Surskit":      ["Masquerain"],
  "Shroomish":    ["Breloom"],
  "Slakoth":      ["Vigoroth"],
  "Vigoroth":     ["Slaking"],
  "Nincada":      ["Ninjask", "Shedinja"],
  "Whismur":      ["Loudred"],
  "Loudred":      ["Exploud"],
  "Makuhita":     ["Hariyama"],
  "Nosepass":     ["Probopass"],
  "Skitty":       ["Delcatty"],
  "Aron":         ["Lairon"],
  "Lairon":       ["Aggron"],
  "Meditite":     ["Medicham"],
  "Electrike":    ["Manectric"],
  "Roselia":      ["Roserade"],
  "Budew":        ["Roselia"],
  "Gulpin":       ["Swalot"],
  "Carvanha":     ["Sharpedo"],
  "Wailmer":      ["Wailord"],
  "Numel":        ["Camerupt"],
  "Spoink":       ["Grumpig"],
  "Trapinch":     ["Vibrava"],
  "Vibrava":      ["Flygon"],
  "Cacnea":       ["Cacturne"],
  "Swablu":       ["Altaria"],
  "Barboach":     ["Whiscash"],
  "Corphish":     ["Crawdaunt"],
  "Baltoy":       ["Claydol"],
  "Lileep":       ["Cradily"],
  "Anorith":      ["Armaldo"],
  "Feebas":       ["Milotic"],
  "Shuppet":      ["Banette"],
  "Duskull":      ["Dusclops"],
  "Dusclops":     ["Dusknoir"],
  "Wynaut":       ["Wobbuffet"],
  "Snorunt":      ["Glalie", "Froslass"],
  "Spheal":       ["Sealeo"],
  "Sealeo":       ["Walrein"],
  "Clamperl":     ["Huntail", "Gorebyss"],
  "Bagon":        ["Shelgon"],
  "Shelgon":      ["Salamence"],
  "Beldum":       ["Metang"],
  "Metang":       ["Metagross"],
  // Gen 4
  "Turtwig":      ["Grotle"],
  "Grotle":       ["Torterra"],
  "Chimchar":     ["Monferno"],
  "Monferno":     ["Infernape"],
  "Piplup":       ["Prinplup"],
  "Prinplup":     ["Empoleon"],
  "Starly":       ["Staravia"],
  "Staravia":     ["Staraptor"],
  "Bidoof":       ["Bibarel"],
  "Kricketot":    ["Kricketune"],
  "Shinx":        ["Luxio"],
  "Luxio":        ["Luxray"],
  "Cranidos":     ["Rampardos"],
  "Shieldon":     ["Bastiodon"],
  "Burmy":        ["Wormadam", "Mothim"],
  "Combee":       ["Vespiquen"],
  "Buizel":       ["Floatzel"],
  "Cherubi":      ["Cherrim"],
  "Shellos":      ["Gastrodon"],
  "Drifloon":     ["Drifblim"],
  "Buneary":      ["Lopunny"],
  "Glameow":      ["Purugly"],
  "Stunky":       ["Skuntank"],
  "Bronzor":      ["Bronzong"],
  "Bonsly":       ["Sudowoodo"],
  "Mime Jr.":     ["Mr. Mime"],
  "Happiny":      ["Chansey"],
  "Gible":        ["Gabite"],
  "Gabite":       ["Garchomp"],
  "Riolu":        ["Lucario"],
  "Hippopotas":   ["Hippowdon"],
  "Skorupi":      ["Drapion"],
  "Croagunk":     ["Toxicroak"],
  "Finneon":      ["Lumineon"],
  "Snover":       ["Abomasnow"],
  "Munchlax":     ["Snorlax"],
  // Gen 5
  "Snivy":        ["Servine"],
  "Servine":      ["Serperior"],
  "Tepig":        ["Pignite"],
  "Pignite":      ["Emboar"],
  "Oshawott":     ["Dewott"],
  "Dewott":       ["Samurott"],
  "Patrat":       ["Watchog"],
  "Lillipup":     ["Herdier"],
  "Herdier":      ["Stoutland"],
  "Purrloin":     ["Liepard"],
  "Pansage":      ["Simisage"],
  "Pansear":      ["Simisear"],
  "Panpour":      ["Simipour"],
  "Munna":        ["Musharna"],
  "Pidove":       ["Tranquill"],
  "Tranquill":    ["Unfezant"],
  "Blitzle":      ["Zebstrika"],
  "Roggenrola":   ["Boldore"],
  "Boldore":      ["Gigalith"],
  "Woobat":       ["Swoobat"],
  "Drilbur":      ["Excadrill"],
  "Timburr":      ["Gurdurr"],
  "Gurdurr":      ["Conkeldurr"],
  "Tympole":      ["Palpitoad"],
  "Palpitoad":    ["Seismitoad"],
  "Sewaddle":     ["Swadloon"],
  "Swadloon":     ["Leavanny"],
  "Venipede":     ["Whirlipede"],
  "Whirlipede":   ["Scolipede"],
  "Cottonee":     ["Whimsicott"],
  "Petilil":      ["Lilligant"],
  "Sandile":      ["Krokorok"],
  "Krokorok":     ["Krookodile"],
  "Darumaka":     ["Darmanitan"],
  "Dwebble":      ["Crustle"],
  "Scraggy":      ["Scrafty"],
  "Yamask":       ["Cofagrigus"],
  "Tirtouga":     ["Carracosta"],
  "Archen":       ["Archeops"],
  "Trubbish":     ["Garbodor"],
  "Zorua":        ["Zoroark"],
  "Minccino":     ["Cinccino"],
  "Gothita":      ["Gothorita"],
  "Gothorita":    ["Gothitelle"],
  "Solosis":      ["Duosion"],
  "Duosion":      ["Reuniclus"],
  "Ducklett":     ["Swanna"],
  "Vanillite":    ["Vanillish"],
  "Vanillish":    ["Vanilluxe"],
  "Deerling":     ["Sawsbuck"],
  "Karrablast":   ["Escavalier"],
  "Foongus":      ["Amoonguss"],
  "Frillish":     ["Jellicent"],
  "Joltik":       ["Galvantula"],
  "Ferroseed":    ["Ferrothorn"],
  "Klink":        ["Klang"],
  "Klang":        ["Klinklang"],
  "Tynamo":       ["Eelektrik"],
  "Eelektrik":    ["Eelektross"],
  "Elgyem":       ["Beheeyem"],
  "Litwick":      ["Lampent"],
  "Lampent":      ["Chandelure"],
  "Axew":         ["Fraxure"],
  "Fraxure":      ["Haxorus"],
  "Cubchoo":      ["Beartic"],
  "Shelmet":      ["Accelgor"],
  "Mienfoo":      ["Mienshao"],
  "Golett":       ["Golurk"],
  "Pawniard":     ["Bisharp"],
  "Bisharp":      ["Kingambit"],
  "Rufflet":      ["Braviary"],
  "Vullaby":      ["Mandibuzz"],
  "Deino":        ["Zweilous"],
  "Zweilous":     ["Hydreigon"],
  "Larvesta":     ["Volcarona"],
  // Gen 6
  "Chespin":      ["Quilladin"],
  "Quilladin":    ["Chesnaught"],
  "Fennekin":     ["Braixen"],
  "Braixen":      ["Delphox"],
  "Froakie":      ["Frogadier"],
  "Frogadier":    ["Greninja"],
  "Bunnelby":     ["Diggersby"],
  "Fletchling":   ["Fletchinder"],
  "Fletchinder":  ["Talonflame"],
  "Scatterbug":   ["Spewpa"],
  "Spewpa":       ["Vivillon"],
  "Litleo":       ["Pyroar"],
  "Flabebe":      ["Floette"],
  "Floette":      ["Florges"],
  "Skiddo":       ["Gogoat"],
  "Pancham":      ["Pangoro"],
  "Espurr":       ["Meowstic"],
  "Honedge":      ["Doublade"],
  "Doublade":     ["Aegislash"],
  "Spritzee":     ["Aromatisse"],
  "Swirlix":      ["Slurpuff"],
  "Inkay":        ["Malamar"],
  "Binacle":      ["Barbaracle"],
  "Skrelp":       ["Dragalge"],
  "Clauncher":    ["Clawitzer"],
  "Helioptile":   ["Heliolisk"],
  "Tyrunt":       ["Tyrantrum"],
  "Amaura":       ["Aurorus"],
  "Goomy":        ["Sliggoo"],
  "Sliggoo":      ["Goodra"],
  "Phantump":     ["Trevenant"],
  "Pumpkaboo":    ["Gourgeist"],
  "Bergmite":     ["Avalugg"],
  "Noibat":       ["Noivern"],
  // Gen 7
  "Rowlet":       ["Dartrix"],
  "Dartrix":      ["Decidueye"],
  "Litten":       ["Torracat"],
  "Torracat":     ["Incineroar"],
  "Popplio":      ["Brionne"],
  "Brionne":      ["Primarina"],
  "Pikipek":      ["Trumbeak"],
  "Trumbeak":     ["Toucannon"],
  "Yungoos":      ["Gumshoos"],
  "Grubbin":      ["Charjabug"],
  "Charjabug":    ["Vikavolt"],
  "Crabrawler":   ["Crabominable"],
  "Cutiefly":     ["Ribombee"],
  "Rockruff":     ["Lycanroc"],
  "Mareanie":     ["Toxapex"],
  "Mudbray":      ["Mudsdale"],
  "Dewpider":     ["Araquanid"],
  "Fomantis":     ["Lurantis"],
  "Morelull":     ["Shiinotic"],
  "Salandit":     ["Salazzle"],
  "Stufful":      ["Bewear"],
  "Bounsweet":    ["Steenee"],
  "Steenee":      ["Tsareena"],
  "Wimpod":       ["Golisopod"],
  "Sandygast":    ["Palossand"],
  "Jangmo-o":     ["Hakamo-o"],
  "Hakamo-o":     ["Kommo-o"],
  "Cosmog":       ["Cosmoem"],
  "Cosmoem":      ["Solgaleo", "Lunala"],
  // Gen 8
  "Grookey":      ["Thwackey"],
  "Thwackey":     ["Rillaboom"],
  "Scorbunny":    ["Raboot"],
  "Raboot":       ["Cinderace"],
  "Sobble":       ["Drizzile"],
  "Drizzile":     ["Inteleon"],
  "Skwovet":      ["Greedent"],
  "Rookidee":     ["Corvisquire"],
  "Corvisquire":  ["Corviknight"],
  "Blipbug":      ["Dottler"],
  "Dottler":      ["Orbeetle"],
  "Nickit":       ["Thievul"],
  "Gossifleur":   ["Eldegoss"],
  "Wooloo":       ["Dubwool"],
  "Chewtle":      ["Drednaw"],
  "Yamper":       ["Boltund"],
  "Rolycoly":     ["Carkol"],
  "Carkol":       ["Coalossal"],
  "Applin":       ["Flapple", "Appletun"],
  "Silicobra":    ["Sandaconda"],
  "Arrokuda":     ["Barraskewda"],
  "Toxel":        ["Toxtricity"],
  "Sizzlipede":   ["Centiskorch"],
  "Clobbopus":    ["Grapploct"],
  "Sinistea":     ["Polteageist"],
  "Hatenna":      ["Hattrem"],
  "Hattrem":      ["Hatterene"],
  "Impidimp":     ["Morgrem"],
  "Morgrem":      ["Grimmsnarl"],
  "Milcery":      ["Alcremie"],
  "Snom":         ["Frosmoth"],
  "Cufant":       ["Copperajah"],
  "Dreepy":       ["Drakloak"],
  "Drakloak":     ["Dragapult"],
  "Kubfu":        ["Urshifu"],
  // Gen 9
  "Sprigatito":   ["Floragato"],
  "Floragato":    ["Meowscarada"],
  "Fuecoco":      ["Crocalor"],
  "Crocalor":     ["Skeledirge"],
  "Quaxly":       ["Quaxwell"],
  "Quaxwell":     ["Quaquaval"],
  "Lechonk":      ["Oinkologne"],
  "Tarountula":   ["Spidops"],
  "Nymble":       ["Lokix"],
  "Pawmi":        ["Pawmo"],
  "Pawmo":        ["Pawmot"],
  "Tandemaus":    ["Maushold"],
  "Fidough":      ["Dachsbun"],
  "Smoliv":       ["Dolliv"],
  "Dolliv":       ["Arboliva"],
  "Nacli":        ["Naclstack"],
  "Naclstack":    ["Garganacl"],
  "Charcadet":    ["Armarouge", "Ceruledge"],
  "Tadbulb":      ["Bellibolt"],
  "Wattrel":      ["Kilowattrel"],
  "Maschiff":     ["Mabosstiff"],
  "Shroodle":     ["Grafaiai"],
  "Bramblin":     ["Brambleghast"],
  "Toedscool":    ["Toedscruel"],
  "Capsakid":     ["Scovillain"],
  "Rellor":       ["Rabsca"],
  "Flittle":      ["Espathra"],
  "Tinkatink":    ["Tinkatuff"],
  "Tinkatuff":    ["Tinkaton"],
  "Wiglett":      ["Wugtrio"],
  "Finizen":      ["Palafin"],
  "Varoom":       ["Revavroom"],
  "Glimmet":      ["Glimmora"],
  "Greavard":     ["Houndstone"],
  "Cetoddle":     ["Cetitan"],
  "Frigibax":     ["Arctibax"],
  "Arctibax":     ["Baxcalibur"],
  "Gimmighoul":   ["Gholdengo"],
};

// Regional evolution overrides, keyed by base species then region. A missing
// region key falls back to EVOLUTION_NEXT for that species. Targets that are
// standalone species (Perrserker, Sneasler, ...) clear the region via the
// propagation rule in getEvolveTargets.
export const REGIONAL_EVOLUTION_NEXT: Record<string, Partial<Record<Region, string[]>>> = {
  "Meowth":     { galarian: ["Perrserker"] },
  "Slowpoke":   { galarian: ["Slowbro", "Slowking"] },
  "Farfetch’d": { galarian: ["Sirfetch’d"] },
  "Mr. Mime":   { galarian: ["Mr. Rime"] },
  "Yamask":     { galarian: ["Runerigus"] },
  "Corsola":    { galarian: ["Cursola"] },
  "Linoone":    { galarian: ["Obstagoon"] },
  "Qwilfish":   { hisuian: ["Overqwil"] },
  "Sneasel":    { hisuian: ["Sneasler"] },
  "Wooper":     { paldean: ["Clodsire"] },
};

export interface EvolveTarget {
  name: string;
  region: string;
}

// Region propagation rule: keep the entry's region when the target species
// itself has that region as a shiny form, otherwise clear it (the target is
// a standalone species such as Perrserker or Sneasler).
export function getEvolveTargets(species: string, region: string): EvolveTarget[] {
  const names =
    (region && REGIONAL_EVOLUTION_NEXT[species]?.[region as Region]) ||
    EVOLUTION_NEXT[species] ||
    [];
  return names.map((n) => ({
    name: n,
    region: shinyRegionalForms(n).some((f) => f.region === region) ? region : "",
  }));
}

// Reverse map: each Pokemon name -> the name(s) it evolves from. Built once by
// inverting EVOLUTION_NEXT plus the regional overrides, so families such as
// Mime Jr./Mr. Mime/Mr. Rime stay connected for search.
const EVOLUTION_PREV: Record<string, string[]> = {};
const REGIONAL_FAMILY_NEXT: Record<string, string[]> = {};
for (const [from, tos] of Object.entries(EVOLUTION_NEXT)) {
  for (const to of tos) (EVOLUTION_PREV[to] ??= []).push(from);
}
for (const [from, byRegion] of Object.entries(REGIONAL_EVOLUTION_NEXT)) {
  for (const tos of Object.values(byRegion)) {
    for (const to of tos ?? []) {
      (EVOLUTION_PREV[to] ??= []).push(from);
      (REGIONAL_FAMILY_NEXT[from] ??= []).push(to);
    }
  }
}

// Returns the full evolution family for a name: every pre-evolution, evolution,
// and branch in its connected component (e.g. Deino/Zweilous/Hydreigon, or Eevee
// plus all eeveelutions). A name with no evolution links returns just itself.
export function getEvolutionFamily(name: string): Set<string> {
  const seen = new Set<string>([name]);
  const queue = [name];
  while (queue.length) {
    const cur = queue.shift()!;
    for (const next of [
      ...(EVOLUTION_NEXT[cur] ?? []),
      ...(REGIONAL_FAMILY_NEXT[cur] ?? []),
      ...(EVOLUTION_PREV[cur] ?? []),
    ]) {
      if (!seen.has(next)) {
        seen.add(next);
        queue.push(next);
      }
    }
  }
  return seen;
}
