package pogodata

// showdownNewSlices groups all NEW Showdown trainer classes (beyond the original builtinTrainerClasses).
// init() in pogodata.go registers these slugs into showdownSources.
// New() appends these to the TrainerClasses list.
var showdownNewSlices = [][]TrainerClass{
	showdownModernExtClasses,
	showdownGen1RBClasses,
	showdownGen1Classes,
	showdownGen2Classes,
	showdownGen3RSClasses,
	showdownGen3Classes,
	showdownGen4DPClasses,
	showdownGen4Classes,
	showdownGen5Classes,
	showdownGen6Classes,
	showdownGen7Classes,
	showdownGen8Classes,
	showdownGen9Classes,
	showdownLGPEClasses,
	showdownMastersClasses,
	showdownGOClasses,
}

// showdownModernExtClasses contains trainers from Showdown's modern sprite directory
// that are NOT already listed in the original builtinTrainerClasses (now showdownModernClasses).
var showdownModernExtClasses = []TrainerClass{
	{Slug: "aarune", Label: "Aarune", Group: "showdown-modern"},
	{Slug: "acerola", Label: "Acerola", Group: "showdown-modern"},
	{Slug: "acetrainercouple", Label: "Ace Trainer Couple", Group: "showdown-modern"},
	{Slug: "acetrainerf", Label: "Ace Trainer F", Group: "showdown-modern"},
	{Slug: "acetrainersnow", Label: "Ace Trainer (Snow)", Group: "showdown-modern"},
	{Slug: "acetrainersnowf", Label: "Ace Trainer F (Snow)", Group: "showdown-modern"},
	{Slug: "adaman", Label: "Adaman", Group: "showdown-modern"},
	{Slug: "aetheremployee", Label: "Aether Employee", Group: "showdown-modern"},
	{Slug: "aetheremployeef", Label: "Aether Employee F", Group: "showdown-modern"},
	{Slug: "aetherfoundation", Label: "Aether Foundation", Group: "showdown-modern"},
	{Slug: "aetherfoundation2", Label: "Aether Foundation 2", Group: "showdown-modern"},
	{Slug: "aetherfoundationf", Label: "Aether Foundation F", Group: "showdown-modern"},
	{Slug: "akari", Label: "Akari", Group: "showdown-modern"},
	{Slug: "akari-isekai", Label: "Akari Isekai", Group: "showdown-modern"},
	{Slug: "alain", Label: "Alain", Group: "showdown-modern"},
	{Slug: "alec-anime", Label: "Alec Anime", Group: "showdown-modern"},
	{Slug: "allister-unmasked", Label: "Allister Unmasked", Group: "showdown-modern"},
	{Slug: "amarys", Label: "Amarys", Group: "showdown-modern"},
	{Slug: "amelia-shuffle", Label: "Amelia Shuffle", Group: "showdown-modern"},
	{Slug: "anabel", Label: "Anabel", Group: "showdown-modern"},
	{Slug: "ansha", Label: "Ansha", Group: "showdown-modern"},
	{Slug: "ansha-cook", Label: "Ansha Cook", Group: "showdown-modern"},
	{Slug: "anthe", Label: "Anthe", Group: "showdown-modern"},
	{Slug: "anthea", Label: "Anthea", Group: "showdown-modern"},
	{Slug: "anvin", Label: "Anvin", Group: "showdown-modern"},
	{Slug: "aquagrunt", Label: "Aquagrunt", Group: "showdown-modern"},
	{Slug: "aquagruntf", Label: "Aquagruntf", Group: "showdown-modern"},
	{Slug: "aquagruntf-rse", Label: "Aquagruntf Rse", Group: "showdown-modern"},
	{Slug: "aquagrunt-rse", Label: "Aquagrunt Rse", Group: "showdown-modern"},
	{Slug: "aquasuit", Label: "Aquasuit", Group: "showdown-modern"},
	{Slug: "archer", Label: "Archer", Group: "showdown-modern"},
	{Slug: "archie-usum", Label: "Archie Usum", Group: "showdown-modern"},
	{Slug: "arezu", Label: "Arezu", Group: "showdown-modern"},
	{Slug: "argenta", Label: "Argenta", Group: "showdown-modern"},
	{Slug: "ariana", Label: "Ariana", Group: "showdown-modern"},
	{Slug: "arlo", Label: "Arlo", Group: "showdown-modern"},
	{Slug: "aromalady", Label: "Aroma Lady", Group: "showdown-modern"},
	{Slug: "artist", Label: "Artist", Group: "showdown-modern"},
	{Slug: "ash", Label: "Ash", Group: "showdown-modern"},
	{Slug: "ash-alola", Label: "Ash Alola", Group: "showdown-modern"},
	{Slug: "ash-capbackward", Label: "Ash Capbackward", Group: "showdown-modern"},
	{Slug: "ash-hoenn", Label: "Ash Hoenn", Group: "showdown-modern"},
	{Slug: "ash-johto", Label: "Ash Johto", Group: "showdown-modern"},
	{Slug: "ash-kalos", Label: "Ash Kalos", Group: "showdown-modern"},
	{Slug: "ash-sinnoh", Label: "Ash Sinnoh", Group: "showdown-modern"},
	{Slug: "ash-unova", Label: "Ash Unova", Group: "showdown-modern"},
	{Slug: "atticus", Label: "Atticus", Group: "showdown-modern"},
	{Slug: "avery", Label: "Avery", Group: "showdown-modern"},
	{Slug: "az", Label: "AZ", Group: "showdown-modern"},
	{Slug: "az-lza", Label: "Az Lza", Group: "showdown-modern"},
	{Slug: "backers", Label: "Backers", Group: "showdown-modern"},
	{Slug: "backersf", Label: "Backersf", Group: "showdown-modern"},
	{Slug: "backpacker", Label: "Backpacker", Group: "showdown-modern"},
	{Slug: "backpackerf", Label: "Backpackerf", Group: "showdown-modern"},
	{Slug: "baker", Label: "Baker", Group: "showdown-modern"},
	{Slug: "ballguy", Label: "Ballguy", Group: "showdown-modern"},
	{Slug: "baoba", Label: "Baoba", Group: "showdown-modern"},
	{Slug: "bede-leader", Label: "Bede Leader", Group: "showdown-modern"},
	{Slug: "bellelba", Label: "Bellelba", Group: "showdown-modern"},
	{Slug: "bellepa", Label: "Bellepa", Group: "showdown-modern"},
	{Slug: "bellhop", Label: "Bellhop", Group: "showdown-modern"},
	{Slug: "bellis", Label: "Bellis", Group: "showdown-modern"},
	{Slug: "benga", Label: "Benga", Group: "showdown-modern"},
	{Slug: "beni", Label: "Beni", Group: "showdown-modern"},
	{Slug: "beni-ninja", Label: "Beni Ninja", Group: "showdown-modern"},
	{Slug: "bianca-pwt", Label: "Bianca Pwt", Group: "showdown-modern"},
	{Slug: "bill", Label: "Bill", Group: "showdown-modern"},
	{Slug: "blanche", Label: "Blanche", Group: "showdown-modern"},
	{Slug: "blanche-casual", Label: "Blanche Casual", Group: "showdown-modern"},
	{Slug: "blue-gen1champion", Label: "Blue Gen1champion", Group: "showdown-modern"},
	{Slug: "blue-gen1rbchampion", Label: "Blue Gen1rbchampion", Group: "showdown-modern"},
	{Slug: "blue-gen1rbtwo", Label: "Blue Gen1rbtwo", Group: "showdown-modern"},
	{Slug: "blue-gen1two", Label: "Blue Gen1two", Group: "showdown-modern"},
	{Slug: "blue-gen3champion", Label: "Blue Gen3champion", Group: "showdown-modern"},
	{Slug: "blue-gen3two", Label: "Blue Gen3two", Group: "showdown-modern"},
	{Slug: "boarder", Label: "Boarder", Group: "showdown-modern"},
	{Slug: "brandon", Label: "Brandon", Group: "showdown-modern"},
	{Slug: "brawly", Label: "Brawly", Group: "showdown-modern"},
	{Slug: "brendan", Label: "Brendan", Group: "showdown-modern"},
	{Slug: "brendan-contest", Label: "Brendan Contest", Group: "showdown-modern"},
	{Slug: "brendan-e", Label: "Brendan E", Group: "showdown-modern"},
	{Slug: "brendan-rs", Label: "Brendan Rs", Group: "showdown-modern"},
	{Slug: "briar", Label: "Briar", Group: "showdown-modern"},
	{Slug: "brigette", Label: "Brigette", Group: "showdown-modern"},
	{Slug: "bruno", Label: "Bruno", Group: "showdown-modern"},
	{Slug: "brycen", Label: "Brycen", Group: "showdown-modern"},
	{Slug: "brycenman", Label: "Brycenman", Group: "showdown-modern"},
	{Slug: "bryony", Label: "Bryony", Group: "showdown-modern"},
	{Slug: "buck", Label: "Buck", Group: "showdown-modern"},
	{Slug: "burgh", Label: "Burgh", Group: "showdown-modern"},
	{Slug: "burnet-radar", Label: "Burnet Radar", Group: "showdown-modern"},
	{Slug: "butler", Label: "Butler", Group: "showdown-modern"},
	{Slug: "byron", Label: "Byron", Group: "showdown-modern"},
	{Slug: "cabbie", Label: "Cabbie", Group: "showdown-modern"},
	{Slug: "cafemaster", Label: "Cafemaster", Group: "showdown-modern"},
	{Slug: "caitlin", Label: "Caitlin", Group: "showdown-modern"},
	{Slug: "calaba", Label: "Calaba", Group: "showdown-modern"},
	{Slug: "cameraman", Label: "Cameraman", Group: "showdown-modern"},
	{Slug: "canari", Label: "Canari", Group: "showdown-modern"},
	{Slug: "candela", Label: "Candela", Group: "showdown-modern"},
	{Slug: "candela-casual", Label: "Candela Casual", Group: "showdown-modern"},
	{Slug: "candice", Label: "Candice", Group: "showdown-modern"},
	{Slug: "caraliss", Label: "Caraliss", Group: "showdown-modern"},
	{Slug: "caretaker", Label: "Caretaker", Group: "showdown-modern"},
	{Slug: "carmine", Label: "Carmine", Group: "showdown-modern"},
	{Slug: "carmine-festival", Label: "Carmine Festival", Group: "showdown-modern"},
	{Slug: "cedricjuniper", Label: "Cedricjuniper", Group: "showdown-modern"},
	{Slug: "celio", Label: "Celio", Group: "showdown-modern"},
	{Slug: "charm", Label: "Charm", Group: "showdown-modern"},
	{Slug: "charon", Label: "Charon", Group: "showdown-modern"},
	{Slug: "chase", Label: "Chase", Group: "showdown-modern"},
	{Slug: "chef", Label: "Chef", Group: "showdown-modern"},
	{Slug: "cheryl", Label: "Cheryl", Group: "showdown-modern"},
	{Slug: "chili", Label: "Chili", Group: "showdown-modern"},
	{Slug: "choy", Label: "Choy", Group: "showdown-modern"},
	{Slug: "christoph", Label: "Christoph", Group: "showdown-modern"},
	{Slug: "chuck", Label: "Chuck", Group: "showdown-modern"},
	{Slug: "cilan", Label: "Cilan", Group: "showdown-modern"},
	{Slug: "clavell-s", Label: "Clavell S", Group: "showdown-modern"},
	{Slug: "clay", Label: "Clay", Group: "showdown-modern"},
	{Slug: "clemont", Label: "Clemont", Group: "showdown-modern"},
	{Slug: "clerk", Label: "Clerk", Group: "showdown-modern"},
	{Slug: "clerk-boss", Label: "Clerk Boss", Group: "showdown-modern"},
	{Slug: "clerkf", Label: "Clerkf", Group: "showdown-modern"},
	{Slug: "clerk-unite", Label: "Clerk Unite", Group: "showdown-modern"},
	{Slug: "cliff", Label: "Cliff", Group: "showdown-modern"},
	{Slug: "clive-v", Label: "Clive V", Group: "showdown-modern"},
	{Slug: "clover", Label: "Clover", Group: "showdown-modern"},
	{Slug: "clown", Label: "Clown", Group: "showdown-modern"},
	{Slug: "cogita", Label: "Cogita", Group: "showdown-modern"},
	{Slug: "coin", Label: "Coin", Group: "showdown-modern"},
	{Slug: "collector", Label: "Collector", Group: "showdown-modern"},
	{Slug: "colza", Label: "Colza", Group: "showdown-modern"},
	{Slug: "concordia", Label: "Concordia", Group: "showdown-modern"},
	{Slug: "cook", Label: "Cook", Group: "showdown-modern"},
	{Slug: "corbeau", Label: "Corbeau", Group: "showdown-modern"},
	{Slug: "courier", Label: "Courier", Group: "showdown-modern"},
	{Slug: "courtney", Label: "Courtney", Group: "showdown-modern"},
	{Slug: "cowgirl", Label: "Cowgirl", Group: "showdown-modern"},
	{Slug: "crasherwake", Label: "Crasherwake", Group: "showdown-modern"},
	{Slug: "cress", Label: "Cress", Group: "showdown-modern"},
	{Slug: "crispin", Label: "Crispin", Group: "showdown-modern"},
	{Slug: "curtis", Label: "Curtis", Group: "showdown-modern"},
	{Slug: "cyclist", Label: "Cyclist", Group: "showdown-modern"},
	{Slug: "cyclistf", Label: "Cyclistf", Group: "showdown-modern"},
	{Slug: "cyllene", Label: "Cyllene", Group: "showdown-modern"},
	{Slug: "cynthia-anime", Label: "Cynthia Anime", Group: "showdown-modern"},
	{Slug: "cynthia-anime2", Label: "Cynthia Anime2", Group: "showdown-modern"},
	{Slug: "cyrano", Label: "Cyrano", Group: "showdown-modern"},
	{Slug: "dagero", Label: "Dagero", Group: "showdown-modern"},
	{Slug: "dahlia", Label: "Dahlia", Group: "showdown-modern"},
	{Slug: "daisy", Label: "Daisy", Group: "showdown-modern"},
	{Slug: "dana", Label: "Dana", Group: "showdown-modern"},
	{Slug: "darach", Label: "Darach", Group: "showdown-modern"},
	{Slug: "darach-caitlin", Label: "Darach Caitlin", Group: "showdown-modern"},
	{Slug: "dawn-contest", Label: "Dawn Contest", Group: "showdown-modern"},
	{Slug: "dawn-gen4pt", Label: "Dawn Gen4pt", Group: "showdown-modern"},
	{Slug: "delinquent", Label: "Delinquent", Group: "showdown-modern"},
	{Slug: "dendra", Label: "Dendra", Group: "showdown-modern"},
	{Slug: "depotagent", Label: "Depotagent", Group: "showdown-modern"},
	{Slug: "dexio", Label: "Dexio", Group: "showdown-modern"},
	{Slug: "diamondclanmember", Label: "Diamondclanmember", Group: "showdown-modern"},
	{Slug: "doubleteam", Label: "Doubleteam", Group: "showdown-modern"},
	{Slug: "drayden", Label: "Drayden", Group: "showdown-modern"},
	{Slug: "drayton", Label: "Drayton", Group: "showdown-modern"},
	{Slug: "dulse", Label: "Dulse", Group: "showdown-modern"},
	{Slug: "elaine", Label: "Elaine", Group: "showdown-modern"},
	{Slug: "elesa", Label: "Elesa", Group: "showdown-modern"},
	{Slug: "elio-usum", Label: "Elio Usum", Group: "showdown-modern"},
	{Slug: "emma", Label: "Emma", Group: "showdown-modern"},
	{Slug: "emma-lza", Label: "Emma Lza", Group: "showdown-modern"},
	{Slug: "emmet", Label: "Emmet", Group: "showdown-modern"},
	{Slug: "erbie-unite", Label: "Erbie Unite", Group: "showdown-modern"},
	{Slug: "eri", Label: "Eri", Group: "showdown-modern"},
	{Slug: "essentia", Label: "Essentia", Group: "showdown-modern"},
	{Slug: "ethan-gen2c", Label: "Ethan Gen2c", Group: "showdown-modern"},
	{Slug: "ethan-pokeathlon", Label: "Ethan Pokeathlon", Group: "showdown-modern"},
	{Slug: "eusine", Label: "Eusine", Group: "showdown-modern"},
	{Slug: "evelyn", Label: "Evelyn", Group: "showdown-modern"},
	{Slug: "fairytalegirl", Label: "Fairytalegirl", Group: "showdown-modern"},
	{Slug: "fantina", Label: "Fantina", Group: "showdown-modern"},
	{Slug: "fennel", Label: "Fennel", Group: "showdown-modern"},
	{Slug: "firefighter", Label: "Firefighter", Group: "showdown-modern"},
	{Slug: "flannery", Label: "Flannery", Group: "showdown-modern"},
	{Slug: "flaregrunt", Label: "Flaregrunt", Group: "showdown-modern"},
	{Slug: "flaregruntf", Label: "Flaregruntf", Group: "showdown-modern"},
	{Slug: "freediver", Label: "Freediver", Group: "showdown-modern"},
	{Slug: "furisodegirl-black", Label: "Furisodegirl Black", Group: "showdown-modern"},
	{Slug: "furisodegirl-blue", Label: "Furisodegirl Blue", Group: "showdown-modern"},
	{Slug: "furisodegirl-pink", Label: "Furisodegirl Pink", Group: "showdown-modern"},
	{Slug: "furisodegirl-white", Label: "Furisodegirl White", Group: "showdown-modern"},
	{Slug: "gaeric", Label: "Gaeric", Group: "showdown-modern"},
	{Slug: "galacticgrunt", Label: "Galacticgrunt", Group: "showdown-modern"},
	{Slug: "galacticgruntf", Label: "Galactic Grunt F", Group: "showdown-modern"},
	{Slug: "garcon", Label: "Garcon", Group: "showdown-modern"},
	{Slug: "gardener", Label: "Gardener", Group: "showdown-modern"},
	{Slug: "gardenia", Label: "Gardenia", Group: "showdown-modern"},
	{Slug: "giacomo", Label: "Giacomo", Group: "showdown-modern"},
	{Slug: "ginchiyo-conquest", Label: "Ginchiyo Conquest", Group: "showdown-modern"},
	{Slug: "ginter", Label: "Ginter", Group: "showdown-modern"},
	{Slug: "glacia", Label: "Glacia", Group: "showdown-modern"},
	{Slug: "gladion-stance", Label: "Gladion Stance", Group: "showdown-modern"},
	{Slug: "gloria-dojo", Label: "Gloria Dojo", Group: "showdown-modern"},
	{Slug: "gloria-league", Label: "Gloria League", Group: "showdown-modern"},
	{Slug: "gloria-tundra", Label: "Gloria Tundra", Group: "showdown-modern"},
	{Slug: "golfer", Label: "Golfer", Group: "showdown-modern"},
	{Slug: "grace", Label: "Grace", Group: "showdown-modern"},
	{Slug: "grant", Label: "Grant", Group: "showdown-modern"},
	{Slug: "green", Label: "Green", Group: "showdown-modern"},
	{Slug: "greta", Label: "Greta", Group: "showdown-modern"},
	{Slug: "grimsley", Label: "Grimsley", Group: "showdown-modern"},
	{Slug: "grisham", Label: "Grisham", Group: "showdown-modern"},
	{Slug: "guitarist", Label: "Guitarist", Group: "showdown-modern"},
	{Slug: "gurkinn", Label: "Gurkinn", Group: "showdown-modern"},
	{Slug: "gwynn", Label: "Gwynn", Group: "showdown-modern"},
	{Slug: "hala", Label: "Hala", Group: "showdown-modern"},
	{Slug: "hanbei-conquest", Label: "Hanbei Conquest", Group: "showdown-modern"},
	{Slug: "hapu", Label: "Hapu", Group: "showdown-modern"},
	{Slug: "harlequin", Label: "Harlequin", Group: "showdown-modern"},
	{Slug: "harmony", Label: "Harmony", Group: "showdown-modern"},
	{Slug: "hau-stance", Label: "Hau Stance", Group: "showdown-modern"},
	{Slug: "hayley", Label: "Hayley", Group: "showdown-modern"},
	{Slug: "heath", Label: "Heath", Group: "showdown-modern"},
	{Slug: "hero2-conquest", Label: "Hero2 Conquest", Group: "showdown-modern"},
	{Slug: "hero-conquest", Label: "Hero Conquest", Group: "showdown-modern"},
	{Slug: "heroine2-conquest", Label: "Heroine2 Conquest", Group: "showdown-modern"},
	{Slug: "heroine-conquest", Label: "Heroine Conquest", Group: "showdown-modern"},
	{Slug: "hilbert-wonderlauncher", Label: "Hilbert Wonderlauncher", Group: "showdown-modern"},
	{Slug: "hilda-wonderlauncher", Label: "Hilda Wonderlauncher", Group: "showdown-modern"},
	{Slug: "hooligans", Label: "Hooligans", Group: "showdown-modern"},
	{Slug: "hoopster", Label: "Hoopster", Group: "showdown-modern"},
	{Slug: "hyde", Label: "Hyde", Group: "showdown-modern"},
	{Slug: "idol", Label: "Idol", Group: "showdown-modern"},
	{Slug: "ilima", Label: "Ilima", Group: "showdown-modern"},
	{Slug: "infielder", Label: "Infielder", Group: "showdown-modern"},
	{Slug: "ingo", Label: "Ingo", Group: "showdown-modern"},
	{Slug: "ingo-hisui", Label: "Ingo Hisui", Group: "showdown-modern"},
	{Slug: "interviewers", Label: "Interviewers", Group: "showdown-modern"},
	{Slug: "irida", Label: "Irida", Group: "showdown-modern"},
	{Slug: "iscan", Label: "Iscan", Group: "showdown-modern"},
	{Slug: "ivor", Label: "Ivor", Group: "showdown-modern"},
	{Slug: "jacinthe", Label: "Jacinthe", Group: "showdown-modern"},
	{Slug: "jacq", Label: "Jacq", Group: "showdown-modern"},
	{Slug: "jamie", Label: "Jamie", Group: "showdown-modern"},
	{Slug: "janine", Label: "Janine", Group: "showdown-modern"},
	{Slug: "janitor", Label: "Janitor", Group: "showdown-modern"},
	{Slug: "jasmine-contest", Label: "Jasmine Contest", Group: "showdown-modern"},
	{Slug: "jogger", Label: "Jogger", Group: "showdown-modern"},
	{Slug: "johanna", Label: "Johanna", Group: "showdown-modern"},
	{Slug: "johanna-contest", Label: "Johanna Contest", Group: "showdown-modern"},
	{Slug: "juan", Label: "Juan", Group: "showdown-modern"},
	{Slug: "jupiter", Label: "Jupiter", Group: "showdown-modern"},
	{Slug: "kahili", Label: "Kahili", Group: "showdown-modern"},
	{Slug: "kamado", Label: "Kamado", Group: "showdown-modern"},
	{Slug: "kamado-armor", Label: "Kamado Armor", Group: "showdown-modern"},
	{Slug: "karen", Label: "Karen", Group: "showdown-modern"},
	{Slug: "katy", Label: "Katy", Group: "showdown-modern"},
	{Slug: "kiawe", Label: "Kiawe", Group: "showdown-modern"},
	{Slug: "kieran-champion", Label: "Kieran Champion", Group: "showdown-modern"},
	{Slug: "kieran-festival", Label: "Kieran Festival", Group: "showdown-modern"},
	{Slug: "kimonogirl", Label: "Kimono Girl", Group: "showdown-modern"},
	{Slug: "klara", Label: "Klara", Group: "showdown-modern"},
	{Slug: "kofu", Label: "Kofu", Group: "showdown-modern"},
	{Slug: "korrina", Label: "Korrina", Group: "showdown-modern"},
	{Slug: "kukui-stand", Label: "Kukui Stand", Group: "showdown-modern"},
	{Slug: "kunoichi2-conquest", Label: "Kunoichi2 Conquest", Group: "showdown-modern"},
	{Slug: "kunoichi-conquest", Label: "Kunoichi Conquest", Group: "showdown-modern"},
	{Slug: "kurt", Label: "Kurt", Group: "showdown-modern"},
	{Slug: "lacey", Label: "Lacey", Group: "showdown-modern"},
	{Slug: "lady", Label: "Lady", Group: "showdown-modern"},
	{Slug: "lana", Label: "Lana", Group: "showdown-modern"},
	{Slug: "lance", Label: "Lance", Group: "showdown-modern"},
	{Slug: "lanette", Label: "Lanette", Group: "showdown-modern"},
	{Slug: "laventon2", Label: "Laventon2", Group: "showdown-modern"},
	{Slug: "leaguestaff", Label: "Leaguestaff", Group: "showdown-modern"},
	{Slug: "leaguestafff", Label: "Leaguestafff", Group: "showdown-modern"},
	{Slug: "lebanne", Label: "Lebanne", Group: "showdown-modern"},
	{Slug: "lenora", Label: "Lenora", Group: "showdown-modern"},
	{Slug: "leon-tower", Label: "Leon Tower", Group: "showdown-modern"},
	{Slug: "li", Label: "Li", Group: "showdown-modern"},
	{Slug: "lian", Label: "Lian", Group: "showdown-modern"},
	{Slug: "lida", Label: "Lida", Group: "showdown-modern"},
	{Slug: "liko", Label: "Liko", Group: "showdown-modern"},
	{Slug: "lillie-z", Label: "Lillie Z", Group: "showdown-modern"},
	{Slug: "linebacker", Label: "Linebacker", Group: "showdown-modern"},
	{Slug: "lisia", Label: "Lisia", Group: "showdown-modern"},
	{Slug: "liza", Label: "Liza", Group: "showdown-modern"},
	{Slug: "lucas-contest", Label: "Lucas Contest", Group: "showdown-modern"},
	{Slug: "lucas-gen4pt", Label: "Lucas Gen4pt", Group: "showdown-modern"},
	{Slug: "lucy", Label: "Lucy", Group: "showdown-modern"},
	{Slug: "lusamine-nihilego", Label: "Lusamine Nihilego", Group: "showdown-modern"},
	{Slug: "lyra-pokeathlon", Label: "Lyra Pokeathlon", Group: "showdown-modern"},
	{Slug: "mable", Label: "Mable", Group: "showdown-modern"},
	{Slug: "madame", Label: "Madame", Group: "showdown-modern"},
	{Slug: "magmagrunt", Label: "Magmagrunt", Group: "showdown-modern"},
	{Slug: "magmagruntf", Label: "Magmagruntf", Group: "showdown-modern"},
	{Slug: "magmagruntf-rse", Label: "Magmagruntf Rse", Group: "showdown-modern"},
	{Slug: "magmagrunt-rse", Label: "Magmagrunt Rse", Group: "showdown-modern"},
	{Slug: "magmasuit", Label: "Magmasuit", Group: "showdown-modern"},
	{Slug: "magnus", Label: "Magnus", Group: "showdown-modern"},
	{Slug: "mai", Label: "Mai", Group: "showdown-modern"},
	{Slug: "maid", Label: "Maid", Group: "showdown-modern"},
	{Slug: "mallow", Label: "Mallow", Group: "showdown-modern"},
	{Slug: "marley", Label: "Marley", Group: "showdown-modern"},
	{Slug: "marlon", Label: "Marlon", Group: "showdown-modern"},
	{Slug: "marnie-league", Label: "Marnie League", Group: "showdown-modern"},
	{Slug: "mars", Label: "Mars", Group: "showdown-modern"},
	{Slug: "marshal", Label: "Marshal", Group: "showdown-modern"},
	{Slug: "masamune-conquest", Label: "Masamune Conquest", Group: "showdown-modern"},
	{Slug: "mateo", Label: "Mateo", Group: "showdown-modern"},
	{Slug: "matt", Label: "Matt", Group: "showdown-modern"},
	{Slug: "may", Label: "May", Group: "showdown-modern"},
	{Slug: "may-contest", Label: "May Contest", Group: "showdown-modern"},
	{Slug: "may-e", Label: "May E", Group: "showdown-modern"},
	{Slug: "maylene", Label: "Maylene", Group: "showdown-modern"},
	{Slug: "may-rs", Label: "May Rs", Group: "showdown-modern"},
	{Slug: "mela", Label: "Mela", Group: "showdown-modern"},
	{Slug: "melli", Label: "Melli", Group: "showdown-modern"},
	{Slug: "miku-fairy", Label: "Miku Fairy", Group: "showdown-modern"},
	{Slug: "miku-fire", Label: "Miku Fire", Group: "showdown-modern"},
	{Slug: "miku-flying", Label: "Miku Flying", Group: "showdown-modern"},
	{Slug: "miku-ghost", Label: "Miku Ghost", Group: "showdown-modern"},
	{Slug: "miku-grass", Label: "Miku Grass", Group: "showdown-modern"},
	{Slug: "miku-ground", Label: "Miku Ground", Group: "showdown-modern"},
	{Slug: "miku-ice", Label: "Miku Ice", Group: "showdown-modern"},
	{Slug: "miku-psychic", Label: "Miku Psychic", Group: "showdown-modern"},
	{Slug: "miku-water", Label: "Miku Water", Group: "showdown-modern"},
	{Slug: "milo", Label: "Milo", Group: "showdown-modern"},
	{Slug: "mina", Label: "Mina", Group: "showdown-modern"},
	{Slug: "mira", Label: "Mira", Group: "showdown-modern"},
	{Slug: "miriam", Label: "Miriam", Group: "showdown-modern"},
	{Slug: "mirror", Label: "Mirror", Group: "showdown-modern"},
	{Slug: "mohn", Label: "Mohn", Group: "showdown-modern"},
	{Slug: "mohn-anime", Label: "Mohn Anime", Group: "showdown-modern"},
	{Slug: "mom-alola", Label: "Mom Alola", Group: "showdown-modern"},
	{Slug: "mom-hoenn", Label: "Mom Hoenn", Group: "showdown-modern"},
	{Slug: "mom-johto", Label: "Mom Johto", Group: "showdown-modern"},
	{Slug: "mom-paldea", Label: "Mom Paldea", Group: "showdown-modern"},
	{Slug: "mom-unova", Label: "Mom Unova", Group: "showdown-modern"},
	{Slug: "mom-unova2", Label: "Mom Unova2", Group: "showdown-modern"},
	{Slug: "morgan", Label: "Morgan", Group: "showdown-modern"},
	{Slug: "mrbriney", Label: "Mr. Briney", Group: "showdown-modern"},
	{Slug: "mrstone", Label: "Mr. Stone", Group: "showdown-modern"},
	{Slug: "musician", Label: "Musician", Group: "showdown-modern"},
	{Slug: "mustard", Label: "Mustard", Group: "showdown-modern"},
	{Slug: "mustard-champion", Label: "Mustard Champion", Group: "showdown-modern"},
	{Slug: "mustard-master", Label: "Mustard Master", Group: "showdown-modern"},
	{Slug: "nancy", Label: "Nancy", Group: "showdown-modern"},
	{Slug: "nanu", Label: "Nanu", Group: "showdown-modern"},
	{Slug: "nate-pokestar", Label: "Nate Pokestar", Group: "showdown-modern"},
	{Slug: "nate-pokestar3", Label: "Nate Pokestar3", Group: "showdown-modern"},
	{Slug: "nate-wonderlauncher", Label: "Nate Wonderlauncher", Group: "showdown-modern"},
	{Slug: "naveen", Label: "Naveen", Group: "showdown-modern"},
	{Slug: "nemona-s", Label: "Nemona S", Group: "showdown-modern"},
	{Slug: "nemona-v", Label: "Nemona V", Group: "showdown-modern"},
	{Slug: "neroli", Label: "Neroli", Group: "showdown-modern"},
	{Slug: "ninjaboy", Label: "Ninja Boy", Group: "showdown-modern"},
	{Slug: "nita", Label: "Nita", Group: "showdown-modern"},
	{Slug: "nobunaga-conquest", Label: "Nobunaga Conquest", Group: "showdown-modern"},
	{Slug: "noland", Label: "Noland", Group: "showdown-modern"},
	{Slug: "norman", Label: "Norman", Group: "showdown-modern"},
	{Slug: "nurseryaide", Label: "Nurseryaide", Group: "showdown-modern"},
	{Slug: "oak", Label: "Oak", Group: "showdown-modern"},
	{Slug: "officeworker", Label: "Officeworker", Group: "showdown-modern"},
	{Slug: "officeworkerf", Label: "Officeworkerf", Group: "showdown-modern"},
	{Slug: "ogreclan", Label: "Ogreclan", Group: "showdown-modern"},
	{Slug: "oichi-conquest", Label: "Oichi Conquest", Group: "showdown-modern"},
	{Slug: "oleana", Label: "Oleana", Group: "showdown-modern"},
	{Slug: "olivia", Label: "Olivia", Group: "showdown-modern"},
	{Slug: "olympia", Label: "Olympia", Group: "showdown-modern"},
	{Slug: "ortega", Label: "Ortega", Group: "showdown-modern"},
	{Slug: "owner", Label: "Owner", Group: "showdown-modern"},
	{Slug: "palina", Label: "Palina", Group: "showdown-modern"},
	{Slug: "palmer", Label: "Palmer", Group: "showdown-modern"},
	{Slug: "parasollady", Label: "Parasol Lady", Group: "showdown-modern"},
	{Slug: "paxton", Label: "Paxton", Group: "showdown-modern"},
	{Slug: "pearlclanmember", Label: "Pearlclanmember", Group: "showdown-modern"},
	{Slug: "peonia", Label: "Peonia", Group: "showdown-modern"},
	{Slug: "peony", Label: "Peony", Group: "showdown-modern"},
	{Slug: "peony-league", Label: "Peony League", Group: "showdown-modern"},
	{Slug: "perrin", Label: "Perrin", Group: "showdown-modern"},
	{Slug: "pesselle", Label: "Pesselle", Group: "showdown-modern"},
	{Slug: "petrel", Label: "Petrel", Group: "showdown-modern"},
	{Slug: "phil", Label: "Phil", Group: "showdown-modern"},
	{Slug: "phillipe", Label: "Phillipe", Group: "showdown-modern"},
	{Slug: "phorus-unite", Label: "Phorus Unite", Group: "showdown-modern"},
	{Slug: "phyco", Label: "Phyco", Group: "showdown-modern"},
	{Slug: "piers-league", Label: "Piers League", Group: "showdown-modern"},
	{Slug: "pilot", Label: "Pilot", Group: "showdown-modern"},
	{Slug: "plasmagrunt", Label: "Plasmagrunt", Group: "showdown-modern"},
	{Slug: "plasmagruntf", Label: "Plasmagruntf", Group: "showdown-modern"},
	{Slug: "plumeria-league", Label: "Plumeria League", Group: "showdown-modern"},
	{Slug: "pokefan", Label: "Poké Fan", Group: "showdown-modern"},
	{Slug: "pokefanf", Label: "Poké Fan F", Group: "showdown-modern"},
	{Slug: "pokekid", Label: "Pokekid", Group: "showdown-modern"},
	{Slug: "pokemonbreeder", Label: "Pokémon Breeder", Group: "showdown-modern"},
	{Slug: "pokemonbreederf", Label: "Pokémon Breeder F", Group: "showdown-modern"},
	{Slug: "pokemonbreederf-gen3frlg", Label: "Pokemonbreederf Gen3frlg", Group: "showdown-modern"},
	{Slug: "pokemoncenterlady", Label: "Pokemoncenterlady", Group: "showdown-modern"},
	{Slug: "pokemonranger", Label: "Pokémon Ranger", Group: "showdown-modern"},
	{Slug: "pokemonrangerf", Label: "Pokémon Ranger F", Group: "showdown-modern"},
	{Slug: "policeman", Label: "Policeman", Group: "showdown-modern"},
	{Slug: "postman", Label: "Postman", Group: "showdown-modern"},
	{Slug: "preschooler", Label: "Preschooler", Group: "showdown-modern"},
	{Slug: "preschoolerf", Label: "Preschoolerf", Group: "showdown-modern"},
	{Slug: "preschoolers", Label: "Preschoolers", Group: "showdown-modern"},
	{Slug: "proton", Label: "Proton", Group: "showdown-modern"},
	{Slug: "psychicf", Label: "Psychicf", Group: "showdown-modern"},
	{Slug: "punkgirl", Label: "Punkgirl", Group: "showdown-modern"},
	{Slug: "punkguy", Label: "Punkguy", Group: "showdown-modern"},
	{Slug: "raifort", Label: "Raifort", Group: "showdown-modern"},
	{Slug: "railstaff", Label: "Railstaff", Group: "showdown-modern"},
	{Slug: "rainbowrocketgrunt", Label: "Rainbowrocketgrunt", Group: "showdown-modern"},
	{Slug: "rainbowrocketgruntf", Label: "Rainbowrocketgruntf", Group: "showdown-modern"},
	{Slug: "ramos", Label: "Ramos", Group: "showdown-modern"},
	{Slug: "rancher", Label: "Rancher", Group: "showdown-modern"},
	{Slug: "ranmaru-conquest", Label: "Ranmaru Conquest", Group: "showdown-modern"},
	{Slug: "red", Label: "Red", Group: "showdown-modern"},
	{Slug: "red-gen1main", Label: "Red Gen1main", Group: "showdown-modern"},
	{Slug: "red-gen1title", Label: "Red Gen1title", Group: "showdown-modern"},
	{Slug: "rei", Label: "Rei", Group: "showdown-modern"},
	{Slug: "rei-isekai", Label: "Rei Isekai", Group: "showdown-modern"},
	{Slug: "reporter", Label: "Reporter", Group: "showdown-modern"},
	{Slug: "rhi", Label: "Rhi", Group: "showdown-modern"},
	{Slug: "richboy", Label: "Rich Boy", Group: "showdown-modern"},
	{Slug: "rika", Label: "Rika", Group: "showdown-modern"},
	{Slug: "riley", Label: "Riley", Group: "showdown-modern"},
	{Slug: "risingstar", Label: "Risingstar", Group: "showdown-modern"},
	{Slug: "risingstarf", Label: "Risingstarf", Group: "showdown-modern"},
	{Slug: "rita", Label: "Rita", Group: "showdown-modern"},
	{Slug: "river", Label: "River", Group: "showdown-modern"},
	{Slug: "roark", Label: "Roark", Group: "showdown-modern"},
	{Slug: "rocketgrunt", Label: "Rocketgrunt", Group: "showdown-modern"},
	{Slug: "rocketgruntf", Label: "Rocketgruntf", Group: "showdown-modern"},
	{Slug: "rollerskater", Label: "Rollerskater", Group: "showdown-modern"},
	{Slug: "rollerskaterf", Label: "Rollerskaterf", Group: "showdown-modern"},
	{Slug: "rood", Label: "Rood", Group: "showdown-modern"},
	{Slug: "rosa-pokestar", Label: "Rosa Pokestar", Group: "showdown-modern"},
	{Slug: "rosa-pokestar2", Label: "Rosa Pokestar2", Group: "showdown-modern"},
	{Slug: "rosa-pokestar3", Label: "Rosa Pokestar3", Group: "showdown-modern"},
	{Slug: "rosa-wonderlauncher", Label: "Rosa Wonderlauncher", Group: "showdown-modern"},
	{Slug: "rose-zerosuit", Label: "Rose Zerosuit", Group: "showdown-modern"},
	{Slug: "roughneck", Label: "Roughneck", Group: "showdown-modern"},
	{Slug: "roxanne", Label: "Roxanne", Group: "showdown-modern"},
	{Slug: "roxie", Label: "Roxie", Group: "showdown-modern"},
	{Slug: "roy", Label: "Roy", Group: "showdown-modern"},
	{Slug: "ruffian", Label: "Ruffian", Group: "showdown-modern"},
	{Slug: "ruinmaniac", Label: "Ruin Maniac", Group: "showdown-modern"},
	{Slug: "rye", Label: "Rye", Group: "showdown-modern"},
	{Slug: "ryuki", Label: "Ryuki", Group: "showdown-modern"},
	{Slug: "sabi", Label: "Sabi", Group: "showdown-modern"},
	{Slug: "sabrina-frlg", Label: "Sabrina Frlg", Group: "showdown-modern"},
	{Slug: "sada-ai", Label: "Sada Ai", Group: "showdown-modern"},
	{Slug: "sage", Label: "Sage", Group: "showdown-modern"},
	{Slug: "saguaro", Label: "Saguaro", Group: "showdown-modern"},
	{Slug: "salvatore", Label: "Salvatore", Group: "showdown-modern"},
	{Slug: "samsonoak", Label: "Samsonoak", Group: "showdown-modern"},
	{Slug: "sanqua", Label: "Sanqua", Group: "showdown-modern"},
	{Slug: "saturn", Label: "Saturn", Group: "showdown-modern"},
	{Slug: "sbcmember", Label: "Sbcmember", Group: "showdown-modern"},
	{Slug: "schoolboy", Label: "School Boy", Group: "showdown-modern"},
	{Slug: "schoolgirl", Label: "Schoolgirl", Group: "showdown-modern"},
	{Slug: "schoolkid", Label: "School Kid", Group: "showdown-modern"},
	{Slug: "schoolkidf", Label: "School Kid F", Group: "showdown-modern"},
	{Slug: "scientistf", Label: "Scientistf", Group: "showdown-modern"},
	{Slug: "scott", Label: "Scott", Group: "showdown-modern"},
	{Slug: "scubadiver", Label: "Scubadiver", Group: "showdown-modern"},
	{Slug: "securitycorps", Label: "Securitycorps", Group: "showdown-modern"},
	{Slug: "securitycorpsf", Label: "Securitycorpsf", Group: "showdown-modern"},
	{Slug: "selene-usum", Label: "Selene Usum", Group: "showdown-modern"},
	{Slug: "serena-anime", Label: "Serena Anime", Group: "showdown-modern"},
	{Slug: "shadowtriad", Label: "Shadowtriad", Group: "showdown-modern"},
	{Slug: "shauna", Label: "Shauna", Group: "showdown-modern"},
	{Slug: "shauntal", Label: "Shauntal", Group: "showdown-modern"},
	{Slug: "shelly", Label: "Shelly", Group: "showdown-modern"},
	{Slug: "shielbert", Label: "Shielbert", Group: "showdown-modern"},
	{Slug: "sidney", Label: "Sidney", Group: "showdown-modern"},
	{Slug: "sierra", Label: "Sierra", Group: "showdown-modern"},
	{Slug: "sightseer", Label: "Sightseer", Group: "showdown-modern"},
	{Slug: "sightseerf", Label: "Sightseerf", Group: "showdown-modern"},
	{Slug: "silver-gen2kanto", Label: "Silver Gen2kanto", Group: "showdown-modern"},
	{Slug: "sina", Label: "Sina", Group: "showdown-modern"},
	{Slug: "sisandbro", Label: "Sisandbro", Group: "showdown-modern"},
	{Slug: "skier", Label: "Skier", Group: "showdown-modern"},
	{Slug: "skierf", Label: "Skierf", Group: "showdown-modern"},
	{Slug: "skullgrunt", Label: "Skullgrunt", Group: "showdown-modern"},
	{Slug: "skullgruntf", Label: "Skullgruntf", Group: "showdown-modern"},
	{Slug: "skyla", Label: "Skyla", Group: "showdown-modern"},
	{Slug: "skytrainer", Label: "Skytrainer", Group: "showdown-modern"},
	{Slug: "skytrainerf", Label: "Skytrainerf", Group: "showdown-modern"},
	{Slug: "smasher", Label: "Smasher", Group: "showdown-modern"},
	{Slug: "soliera", Label: "Soliera", Group: "showdown-modern"},
	{Slug: "sonia-professor", Label: "Sonia Professor", Group: "showdown-modern"},
	{Slug: "sophocles", Label: "Sophocles", Group: "showdown-modern"},
	{Slug: "sordward", Label: "Sordward", Group: "showdown-modern"},
	{Slug: "sordward-shielbert", Label: "Sordward Shielbert", Group: "showdown-modern"},
	{Slug: "spark", Label: "Spark", Group: "showdown-modern"},
	{Slug: "spark-casual", Label: "Spark Casual", Group: "showdown-modern"},
	{Slug: "spenser", Label: "Spenser", Group: "showdown-modern"},
	{Slug: "stargruntf-s", Label: "Stargruntf S", Group: "showdown-modern"},
	{Slug: "stargruntf-v", Label: "Stargruntf V", Group: "showdown-modern"},
	{Slug: "stargrunt-s", Label: "Stargrunt S", Group: "showdown-modern"},
	{Slug: "stargrunt-v", Label: "Stargrunt V", Group: "showdown-modern"},
	{Slug: "streetthug", Label: "Streetthug", Group: "showdown-modern"},
	{Slug: "striker", Label: "Striker", Group: "showdown-modern"},
	{Slug: "surfer", Label: "Surfer", Group: "showdown-modern"},
	{Slug: "swimmerf", Label: "Swimmerf", Group: "showdown-modern"},
	{Slug: "swimmer-gen4jp", Label: "Swimmer Gen4jp", Group: "showdown-modern"},
	{Slug: "tabitha", Label: "Tabitha", Group: "showdown-modern"},
	{Slug: "taohua", Label: "Taohua", Group: "showdown-modern"},
	{Slug: "tarragon", Label: "Tarragon", Group: "showdown-modern"},
	{Slug: "tate", Label: "Tate", Group: "showdown-modern"},
	{Slug: "taunie", Label: "Taunie", Group: "showdown-modern"},
	{Slug: "teacher", Label: "Teacher", Group: "showdown-modern"},
	{Slug: "teammates", Label: "Teammates", Group: "showdown-modern"},
	{Slug: "teamrocket", Label: "Teamrocket", Group: "showdown-modern"},
	{Slug: "theroyal", Label: "Theroyal", Group: "showdown-modern"},
	{Slug: "thorton", Label: "Thorton", Group: "showdown-modern"},
	{Slug: "tierno", Label: "Tierno", Group: "showdown-modern"},
	{Slug: "toddsnap", Label: "Toddsnap", Group: "showdown-modern"},
	{Slug: "toddsnap2", Label: "Toddsnap2", Group: "showdown-modern"},
	{Slug: "tourist", Label: "Tourist", Group: "showdown-modern"},
	{Slug: "touristf", Label: "Touristf", Group: "showdown-modern"},
	{Slug: "touristf2", Label: "Touristf2", Group: "showdown-modern"},
	{Slug: "trace", Label: "Trace", Group: "showdown-modern"},
	{Slug: "trevor", Label: "Trevor", Group: "showdown-modern"},
	{Slug: "trialguide", Label: "Trialguide", Group: "showdown-modern"},
	{Slug: "trialguidef", Label: "Trialguidef", Group: "showdown-modern"},
	{Slug: "tuber", Label: "Tuber", Group: "showdown-modern"},
	{Slug: "tuberf", Label: "Tuberf", Group: "showdown-modern"},
	{Slug: "tucker", Label: "Tucker", Group: "showdown-modern"},
	{Slug: "tuli", Label: "Tuli", Group: "showdown-modern"},
	{Slug: "turo-ai", Label: "Turo Ai", Group: "showdown-modern"},
	{Slug: "twins", Label: "Twins", Group: "showdown-modern"},
	{Slug: "tyme", Label: "Tyme", Group: "showdown-modern"},
	{Slug: "ultraforestkartenvoy", Label: "Ultraforestkartenvoy", Group: "showdown-modern"},
	{Slug: "unknown", Label: "Unknown", Group: "showdown-modern"},
	{Slug: "unknownf", Label: "Unknownf", Group: "showdown-modern"},
	{Slug: "urbain", Label: "Urbain", Group: "showdown-modern"},
	{Slug: "valerie", Label: "Valerie", Group: "showdown-modern"},
	{Slug: "vessa", Label: "Vessa", Group: "showdown-modern"},
	{Slug: "veteran", Label: "Veteran", Group: "showdown-modern"},
	{Slug: "veteranf", Label: "Veteranf", Group: "showdown-modern"},
	{Slug: "victor-dojo", Label: "Victor Dojo", Group: "showdown-modern"},
	{Slug: "victor-league", Label: "Victor League", Group: "showdown-modern"},
	{Slug: "victor-tundra", Label: "Victor Tundra", Group: "showdown-modern"},
	{Slug: "vince", Label: "Vince", Group: "showdown-modern"},
	{Slug: "viola", Label: "Viola", Group: "showdown-modern"},
	{Slug: "volo-ginkgo", Label: "Volo Ginkgo", Group: "showdown-modern"},
	{Slug: "waiter", Label: "Waiter", Group: "showdown-modern"},
	{Slug: "waitress", Label: "Waitress", Group: "showdown-modern"},
	{Slug: "wallace", Label: "Wallace", Group: "showdown-modern"},
	{Slug: "wally-rse", Label: "Wally Rse", Group: "showdown-modern"},
	{Slug: "wattson", Label: "Wattson", Group: "showdown-modern"},
	{Slug: "wicke", Label: "Wicke", Group: "showdown-modern"},
	{Slug: "will", Label: "Will", Group: "showdown-modern"},
	{Slug: "willow-casual", Label: "Willow Casual", Group: "showdown-modern"},
	{Slug: "winona", Label: "Winona", Group: "showdown-modern"},
	{Slug: "workerice", Label: "Workerice", Group: "showdown-modern"},
	{Slug: "wulfric", Label: "Wulfric", Group: "showdown-modern"},
	{Slug: "xerosic", Label: "Xerosic", Group: "showdown-modern"},
	{Slug: "yancy", Label: "Yancy", Group: "showdown-modern"},
	{Slug: "yellgrunt", Label: "Yellgrunt", Group: "showdown-modern"},
	{Slug: "yellgruntf", Label: "Yellgruntf", Group: "showdown-modern"},
	{Slug: "yellow", Label: "Yellow", Group: "showdown-modern"},
	{Slug: "youngathlete", Label: "Youngathlete", Group: "showdown-modern"},
	{Slug: "youngathletef", Label: "Youngathletef", Group: "showdown-modern"},
	{Slug: "youngcouple", Label: "Young Couple", Group: "showdown-modern"},
	{Slug: "youngn", Label: "Youngn", Group: "showdown-modern"},
	{Slug: "yukito-hideko", Label: "Yukito & Hideko", Group: "showdown-modern"},
	{Slug: "zinnia", Label: "Zinnia", Group: "showdown-modern"},
	{Slug: "zinzolin", Label: "Zinzolin", Group: "showdown-modern"},
	{Slug: "zirco-unite", Label: "Zirco (Unite)", Group: "showdown-modern"},
	{Slug: "zisu", Label: "Zisu", Group: "showdown-modern"},
	{Slug: "zossie", Label: "Zossie", Group: "showdown-modern"},
}

var showdownGen1RBClasses = []TrainerClass{
	{Slug: "acetrainerf-gen1rb", Label: "Ace Trainer F (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "acetrainer-gen1rb", Label: "Ace Trainer (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "agatha-gen1rb", Label: "Agatha (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "beauty-gen1rb", Label: "Beauty (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "biker-gen1rb", Label: "Biker (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "birdkeeper-gen1rb", Label: "Bird Keeper (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "blackbelt-gen1rb", Label: "Black Belt (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "blaine-gen1rb", Label: "Blaine (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "blue-gen1rb", Label: "Blue (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "brock-gen1rb", Label: "Brock (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "bruno-gen1rb", Label: "Bruno (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "bugcatcher-gen1rb", Label: "Bug Catcher (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "burglar-gen1rb", Label: "Burglar (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "channeler-gen1rb", Label: "Channeler (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "cueball-gen1rb", Label: "Cueball (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "engineer-gen1rb", Label: "Engineer (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "erika-gen1rb", Label: "Erika (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "fisherman-gen1rb", Label: "Fisherman (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "gambler-gen1rb", Label: "Gambler (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "gentleman-gen1rb", Label: "Gentleman (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "giovanni-gen1rb", Label: "Giovanni (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "hiker-gen1rb", Label: "Hiker (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "jrtrainerf-gen1rb", Label: "Jr. Trainer F (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "jrtrainer-gen1rb", Label: "Jr. Trainer (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "juggler-gen1rb", Label: "Juggler (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "koga-gen1rb", Label: "Koga (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "lance-gen1rb", Label: "Lance (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "lass-gen1rb", Label: "Lass (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "lorelei-gen1rb", Label: "Lorelei (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "ltsurge-gen1rb", Label: "Lt. Surge (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "misty-gen1rb", Label: "Misty (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "oak-gen1rb", Label: "Oak (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "pokemaniac-gen1rb", Label: "Pokemaniac (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "psychic-gen1rb", Label: "Psychic (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "red-gen1rb", Label: "Red (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "rocker-gen1rb", Label: "Rocker (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "rocket-gen1rb", Label: "Rocket (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "sabrina-gen1rb", Label: "Sabrina (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "sailor-gen1rb", Label: "Sailor (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "scientist-gen1rb", Label: "Scientist (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "supernerd-gen1rb", Label: "Super Nerd (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "swimmer-gen1rb", Label: "Swimmer (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "tamer-gen1rb", Label: "Tamer (Gen 1 RB)", Group: "showdown-gen1rb"},
	{Slug: "youngster-gen1rb", Label: "Youngster (Gen 1 RB)", Group: "showdown-gen1rb"},
}

var showdownGen1Classes = []TrainerClass{
	{Slug: "acetrainerf-gen1", Label: "Ace Trainer F (Gen 1)", Group: "showdown-gen1"},
	{Slug: "acetrainer-gen1", Label: "Ace Trainer (Gen 1)", Group: "showdown-gen1"},
	{Slug: "agatha-gen1", Label: "Agatha (Gen 1)", Group: "showdown-gen1"},
	{Slug: "beauty-gen1", Label: "Beauty (Gen 1)", Group: "showdown-gen1"},
	{Slug: "biker-gen1", Label: "Biker (Gen 1)", Group: "showdown-gen1"},
	{Slug: "birdkeeper-gen1", Label: "Bird Keeper (Gen 1)", Group: "showdown-gen1"},
	{Slug: "blackbelt-gen1", Label: "Black Belt (Gen 1)", Group: "showdown-gen1"},
	{Slug: "blaine-gen1", Label: "Blaine (Gen 1)", Group: "showdown-gen1"},
	{Slug: "blue-gen1", Label: "Blue (Gen 1)", Group: "showdown-gen1"},
	{Slug: "brock-gen1", Label: "Brock (Gen 1)", Group: "showdown-gen1"},
	{Slug: "bruno-gen1", Label: "Bruno (Gen 1)", Group: "showdown-gen1"},
	{Slug: "bugcatcher-gen1", Label: "Bug Catcher (Gen 1)", Group: "showdown-gen1"},
	{Slug: "burglar-gen1", Label: "Burglar (Gen 1)", Group: "showdown-gen1"},
	{Slug: "channeler-gen1", Label: "Channeler (Gen 1)", Group: "showdown-gen1"},
	{Slug: "cueball-gen1", Label: "Cueball (Gen 1)", Group: "showdown-gen1"},
	{Slug: "engineer-gen1", Label: "Engineer (Gen 1)", Group: "showdown-gen1"},
	{Slug: "erika-gen1", Label: "Erika (Gen 1)", Group: "showdown-gen1"},
	{Slug: "fisherman-gen1", Label: "Fisherman (Gen 1)", Group: "showdown-gen1"},
	{Slug: "gambler-gen1", Label: "Gambler (Gen 1)", Group: "showdown-gen1"},
	{Slug: "gentleman-gen1", Label: "Gentleman (Gen 1)", Group: "showdown-gen1"},
	{Slug: "giovanni-gen1", Label: "Giovanni (Gen 1)", Group: "showdown-gen1"},
	{Slug: "hiker-gen1", Label: "Hiker (Gen 1)", Group: "showdown-gen1"},
	{Slug: "jessiejames-gen1", Label: "Jessiejames (Gen 1)", Group: "showdown-gen1"},
	{Slug: "jrtrainerf-gen1", Label: "Jr. Trainer F (Gen 1)", Group: "showdown-gen1"},
	{Slug: "jrtrainer-gen1", Label: "Jr. Trainer (Gen 1)", Group: "showdown-gen1"},
	{Slug: "juggler-gen1", Label: "Juggler (Gen 1)", Group: "showdown-gen1"},
	{Slug: "koga-gen1", Label: "Koga (Gen 1)", Group: "showdown-gen1"},
	{Slug: "lance-gen1", Label: "Lance (Gen 1)", Group: "showdown-gen1"},
	{Slug: "lass-gen1", Label: "Lass (Gen 1)", Group: "showdown-gen1"},
	{Slug: "lorelei-gen1", Label: "Lorelei (Gen 1)", Group: "showdown-gen1"},
	{Slug: "ltsurge-gen1", Label: "Lt. Surge (Gen 1)", Group: "showdown-gen1"},
	{Slug: "misty-gen1", Label: "Misty (Gen 1)", Group: "showdown-gen1"},
	{Slug: "oak-gen1", Label: "Oak (Gen 1)", Group: "showdown-gen1"},
	{Slug: "pokemaniac-gen1", Label: "Pokemaniac (Gen 1)", Group: "showdown-gen1"},
	{Slug: "psychic-gen1", Label: "Psychic (Gen 1)", Group: "showdown-gen1"},
	{Slug: "red-gen1", Label: "Red (Gen 1)", Group: "showdown-gen1"},
	{Slug: "rocker-gen1", Label: "Rocker (Gen 1)", Group: "showdown-gen1"},
	{Slug: "rocket-gen1", Label: "Rocket (Gen 1)", Group: "showdown-gen1"},
	{Slug: "sabrina-gen1", Label: "Sabrina (Gen 1)", Group: "showdown-gen1"},
	{Slug: "sailor-gen1", Label: "Sailor (Gen 1)", Group: "showdown-gen1"},
	{Slug: "scientist-gen1", Label: "Scientist (Gen 1)", Group: "showdown-gen1"},
	{Slug: "supernerd-gen1", Label: "Super Nerd (Gen 1)", Group: "showdown-gen1"},
	{Slug: "swimmer-gen1", Label: "Swimmer (Gen 1)", Group: "showdown-gen1"},
	{Slug: "tamer-gen1", Label: "Tamer (Gen 1)", Group: "showdown-gen1"},
	{Slug: "youngster-gen1", Label: "Youngster (Gen 1)", Group: "showdown-gen1"},
}

var showdownGen2Classes = []TrainerClass{
	{Slug: "acetrainerf-gen2", Label: "Ace Trainer F (Gen 2)", Group: "showdown-gen2"},
	{Slug: "acetrainer-gen2", Label: "Ace Trainer (Gen 2)", Group: "showdown-gen2"},
	{Slug: "beauty-gen2", Label: "Beauty (Gen 2)", Group: "showdown-gen2"},
	{Slug: "beauty-gen2jp", Label: "Beauty (Gen 2 JP)", Group: "showdown-gen2"},
	{Slug: "biker-gen2", Label: "Biker (Gen 2)", Group: "showdown-gen2"},
	{Slug: "birdkeeper-gen2", Label: "Bird Keeper (Gen 2)", Group: "showdown-gen2"},
	{Slug: "blackbelt-gen2", Label: "Black Belt (Gen 2)", Group: "showdown-gen2"},
	{Slug: "blaine-gen2", Label: "Blaine (Gen 2)", Group: "showdown-gen2"},
	{Slug: "blue-gen2", Label: "Blue (Gen 2)", Group: "showdown-gen2"},
	{Slug: "boarder-gen2", Label: "Boarder (Gen 2)", Group: "showdown-gen2"},
	{Slug: "brock-gen2", Label: "Brock (Gen 2)", Group: "showdown-gen2"},
	{Slug: "bruno-gen2", Label: "Bruno (Gen 2)", Group: "showdown-gen2"},
	{Slug: "bugcatcher-gen2", Label: "Bug Catcher (Gen 2)", Group: "showdown-gen2"},
	{Slug: "bugsy-gen2", Label: "Bugsy (Gen 2)", Group: "showdown-gen2"},
	{Slug: "burglar-gen2", Label: "Burglar (Gen 2)", Group: "showdown-gen2"},
	{Slug: "camper-gen2", Label: "Camper (Gen 2)", Group: "showdown-gen2"},
	{Slug: "chuck-gen2", Label: "Chuck (Gen 2)", Group: "showdown-gen2"},
	{Slug: "clair-gen2", Label: "Clair (Gen 2)", Group: "showdown-gen2"},
	{Slug: "erika-gen2", Label: "Erika (Gen 2)", Group: "showdown-gen2"},
	{Slug: "ethan-gen2", Label: "Ethan (Gen 2)", Group: "showdown-gen2"},
	{Slug: "eusine-gen2", Label: "Eusine (Gen 2)", Group: "showdown-gen2"},
	{Slug: "falkner-gen2", Label: "Falkner (Gen 2)", Group: "showdown-gen2"},
	{Slug: "firebreather-gen2", Label: "Fire Breather (Gen 2)", Group: "showdown-gen2"},
	{Slug: "fisherman-gen2jp", Label: "Fisherman (Gen 2 JP)", Group: "showdown-gen2"},
	{Slug: "gentleman-gen2", Label: "Gentleman (Gen 2)", Group: "showdown-gen2"},
	{Slug: "guitarist-gen2", Label: "Guitarist (Gen 2)", Group: "showdown-gen2"},
	{Slug: "hiker-gen2", Label: "Hiker (Gen 2)", Group: "showdown-gen2"},
	{Slug: "janine-gen2", Label: "Janine (Gen 2)", Group: "showdown-gen2"},
	{Slug: "jasmine-gen2", Label: "Jasmine (Gen 2)", Group: "showdown-gen2"},
	{Slug: "juggler-gen2", Label: "Juggler (Gen 2)", Group: "showdown-gen2"},
	{Slug: "karen-gen2", Label: "Karen (Gen 2)", Group: "showdown-gen2"},
	{Slug: "kimonogirl-gen2", Label: "Kimono Girl (Gen 2)", Group: "showdown-gen2"},
	{Slug: "koga-gen2", Label: "Koga (Gen 2)", Group: "showdown-gen2"},
	{Slug: "kris-gen2", Label: "Kris (Gen 2)", Group: "showdown-gen2"},
	{Slug: "lance-gen2", Label: "Lance (Gen 2)", Group: "showdown-gen2"},
	{Slug: "lass-gen2", Label: "Lass (Gen 2)", Group: "showdown-gen2"},
	{Slug: "ltsurge-gen2", Label: "Lt. Surge (Gen 2)", Group: "showdown-gen2"},
	{Slug: "medium-gen2jp", Label: "Medium (Gen 2 JP)", Group: "showdown-gen2"},
	{Slug: "misty-gen2", Label: "Misty (Gen 2)", Group: "showdown-gen2"},
	{Slug: "morty-gen2", Label: "Morty (Gen 2)", Group: "showdown-gen2"},
	{Slug: "oak-gen2", Label: "Oak (Gen 2)", Group: "showdown-gen2"},
	{Slug: "officer-gen2", Label: "Officer (Gen 2)", Group: "showdown-gen2"},
	{Slug: "picnicker-gen2", Label: "Picnicker (Gen 2)", Group: "showdown-gen2"},
	{Slug: "pokefanf-gen2", Label: "Poké Fan F (Gen 2)", Group: "showdown-gen2"},
	{Slug: "pokefan-gen2", Label: "Poké Fan (Gen 2)", Group: "showdown-gen2"},
	{Slug: "pokemaniac-gen2", Label: "Pokemaniac (Gen 2)", Group: "showdown-gen2"},
	{Slug: "pryce-gen2", Label: "Pryce (Gen 2)", Group: "showdown-gen2"},
	{Slug: "psychic-gen2", Label: "Psychic (Gen 2)", Group: "showdown-gen2"},
	{Slug: "red-gen2", Label: "Red (Gen 2)", Group: "showdown-gen2"},
	{Slug: "rocketexecutivef-gen2", Label: "Rocketexecutivef (Gen 2)", Group: "showdown-gen2"},
	{Slug: "rocketexecutive-gen2", Label: "Rocketexecutive (Gen 2)", Group: "showdown-gen2"},
	{Slug: "rocketgruntf-gen2", Label: "Rocketgruntf (Gen 2)", Group: "showdown-gen2"},
	{Slug: "rocketgrunt-gen2", Label: "Rocketgrunt (Gen 2)", Group: "showdown-gen2"},
	{Slug: "sabrina-gen2", Label: "Sabrina (Gen 2)", Group: "showdown-gen2"},
	{Slug: "sage-gen2", Label: "Sage (Gen 2)", Group: "showdown-gen2"},
	{Slug: "sage-gen2jp", Label: "Sage (Gen 2 JP)", Group: "showdown-gen2"},
	{Slug: "sailor-gen2", Label: "Sailor (Gen 2)", Group: "showdown-gen2"},
	{Slug: "schoolboy-gen2", Label: "School Boy (Gen 2)", Group: "showdown-gen2"},
	{Slug: "scientist-gen2", Label: "Scientist (Gen 2)", Group: "showdown-gen2"},
	{Slug: "silver-gen2", Label: "Silver (Gen 2)", Group: "showdown-gen2"},
	{Slug: "skier-gen2", Label: "Skier (Gen 2)", Group: "showdown-gen2"},
	{Slug: "supernerd-gen2", Label: "Super Nerd (Gen 2)", Group: "showdown-gen2"},
	{Slug: "swimmerf-gen2", Label: "Swimmerf (Gen 2)", Group: "showdown-gen2"},
	{Slug: "swimmerfjp-gen2", Label: "Swimmerfjp (Gen 2)", Group: "showdown-gen2"},
	{Slug: "swimmerm-gen2", Label: "Swimmerm (Gen 2)", Group: "showdown-gen2"},
	{Slug: "teacher-gen2", Label: "Teacher (Gen 2)", Group: "showdown-gen2"},
	{Slug: "twins-gen2", Label: "Twins (Gen 2)", Group: "showdown-gen2"},
	{Slug: "whitney-gen2", Label: "Whitney (Gen 2)", Group: "showdown-gen2"},
	{Slug: "will-gen2", Label: "Will (Gen 2)", Group: "showdown-gen2"},
	{Slug: "youngster-gen2", Label: "Youngster (Gen 2)", Group: "showdown-gen2"},
}

var showdownGen3RSClasses = []TrainerClass{
	{Slug: "acetrainerf-gen3rs", Label: "Ace Trainer F (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "acetrainer-gen3rs", Label: "Ace Trainer (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "aromalady-gen3rs", Label: "Aroma Lady (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "beauty-gen3rs", Label: "Beauty (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "birdkeeper-gen3rs", Label: "Bird Keeper (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "blackbelt-gen3rs", Label: "Black Belt (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "brendan-gen3rs", Label: "Brendan (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "bugcatcher-gen3rs", Label: "Bug Catcher (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "camper-gen3rs", Label: "Camper (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "fisherman-gen3rs", Label: "Fisherman (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "gentleman-gen3rs", Label: "Gentleman (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "hiker-gen3rs", Label: "Hiker (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "lady-gen3rs", Label: "Lady (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "lass-gen3rs", Label: "Lass (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "may-gen3rs", Label: "May (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "picnicker-gen3rs", Label: "Picnicker (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "pokemaniac-gen3rs", Label: "Pokemaniac (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "pokemonrangerf-gen3rs", Label: "Pokémon Ranger F (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "pokemonranger-gen3rs", Label: "Pokémon Ranger (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "psychicf-gen3rs", Label: "Psychicf (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "psychic-gen3rs", Label: "Psychic (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "ruinmaniac-gen3rs", Label: "Ruin Maniac (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "sailor-gen3rs", Label: "Sailor (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "sisandbro-gen3rs", Label: "Sisandbro (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "swimmerf-gen3rs", Label: "Swimmerf (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "swimmerm-gen3rs", Label: "Swimmerm (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "tuberf-gen3rs", Label: "Tuberf (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "twins-gen3rs", Label: "Twins (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "wallace-gen3rs", Label: "Wallace (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "youngcouple-gen3rs", Label: "Young Couple (Gen 3 RS)", Group: "showdown-gen3rs"},
	{Slug: "youngster-gen3rs", Label: "Youngster (Gen 3 RS)", Group: "showdown-gen3rs"},
}

var showdownGen3Classes = []TrainerClass{
	{Slug: "acetrainercouple-gen3", Label: "Ace Trainer Couple (Gen 3)", Group: "showdown-gen3"},
	{Slug: "acetrainerf-gen3", Label: "Ace Trainer F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "acetrainer-gen3", Label: "Ace Trainer (Gen 3)", Group: "showdown-gen3"},
	{Slug: "acetrainer-gen3jp", Label: "Ace Trainer (Gen 3 JP)", Group: "showdown-gen3"},
	{Slug: "agatha-gen3", Label: "Agatha (Gen 3)", Group: "showdown-gen3"},
	{Slug: "anabel-gen3", Label: "Anabel (Gen 3)", Group: "showdown-gen3"},
	{Slug: "archie-gen3", Label: "Archie (Gen 3)", Group: "showdown-gen3"},
	{Slug: "aromalady-gen3", Label: "Aroma Lady (Gen 3)", Group: "showdown-gen3"},
	{Slug: "battlegirl-gen3", Label: "Battle Girl (Gen 3)", Group: "showdown-gen3"},
	{Slug: "beauty-gen3", Label: "Beauty (Gen 3)", Group: "showdown-gen3"},
	{Slug: "biker-gen3", Label: "Biker (Gen 3)", Group: "showdown-gen3"},
	{Slug: "bill-gen3", Label: "Bill (Gen 3)", Group: "showdown-gen3"},
	{Slug: "birch-gen3", Label: "Prof. Birch (Gen 3)", Group: "showdown-gen3"},
	{Slug: "birdkeeper-gen3", Label: "Bird Keeper (Gen 3)", Group: "showdown-gen3"},
	{Slug: "blackbelt-gen3", Label: "Black Belt (Gen 3)", Group: "showdown-gen3"},
	{Slug: "blaine-gen3", Label: "Blaine (Gen 3)", Group: "showdown-gen3"},
	{Slug: "blue-gen3", Label: "Blue (Gen 3)", Group: "showdown-gen3"},
	{Slug: "brandon-gen3", Label: "Brandon (Gen 3)", Group: "showdown-gen3"},
	{Slug: "brawly-gen3", Label: "Brawly (Gen 3)", Group: "showdown-gen3"},
	{Slug: "brendan-gen3", Label: "Brendan (Gen 3)", Group: "showdown-gen3"},
	{Slug: "brock-gen3", Label: "Brock (Gen 3)", Group: "showdown-gen3"},
	{Slug: "bruno-gen3", Label: "Bruno (Gen 3)", Group: "showdown-gen3"},
	{Slug: "bugcatcher-gen3", Label: "Bug Catcher (Gen 3)", Group: "showdown-gen3"},
	{Slug: "bugmaniac-gen3", Label: "Bug Maniac (Gen 3)", Group: "showdown-gen3"},
	{Slug: "burglar-gen3", Label: "Burglar (Gen 3)", Group: "showdown-gen3"},
	{Slug: "camper-gen3", Label: "Camper (Gen 3)", Group: "showdown-gen3"},
	{Slug: "channeler-gen3", Label: "Channeler (Gen 3)", Group: "showdown-gen3"},
	{Slug: "collector-gen3", Label: "Collector (Gen 3)", Group: "showdown-gen3"},
	{Slug: "courtney-gen3", Label: "Courtney (Gen 3)", Group: "showdown-gen3"},
	{Slug: "crushgirl-gen3", Label: "Crushgirl (Gen 3)", Group: "showdown-gen3"},
	{Slug: "crushkin-gen3", Label: "Crushkin (Gen 3)", Group: "showdown-gen3"},
	{Slug: "cueball-gen3", Label: "Cueball (Gen 3)", Group: "showdown-gen3"},
	{Slug: "daisy-gen3", Label: "Daisy (Gen 3)", Group: "showdown-gen3"},
	{Slug: "dragontamer-gen3", Label: "Dragon Tamer (Gen 3)", Group: "showdown-gen3"},
	{Slug: "drake-gen3", Label: "Drake (Gen 3)", Group: "showdown-gen3"},
	{Slug: "engineer-gen3", Label: "Engineer (Gen 3)", Group: "showdown-gen3"},
	{Slug: "erika-gen3", Label: "Erika (Gen 3)", Group: "showdown-gen3"},
	{Slug: "expertf-gen3", Label: "Expertf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "expert-gen3", Label: "Expert (Gen 3)", Group: "showdown-gen3"},
	{Slug: "fisherman-gen3", Label: "Fisherman (Gen 3)", Group: "showdown-gen3"},
	{Slug: "flannery-gen3", Label: "Flannery (Gen 3)", Group: "showdown-gen3"},
	{Slug: "gamer-gen3", Label: "Gamer (Gen 3)", Group: "showdown-gen3"},
	{Slug: "gentleman-gen3", Label: "Gentleman (Gen 3)", Group: "showdown-gen3"},
	{Slug: "giovanni-gen3", Label: "Giovanni (Gen 3)", Group: "showdown-gen3"},
	{Slug: "glacia-gen3", Label: "Glacia (Gen 3)", Group: "showdown-gen3"},
	{Slug: "greta-gen3", Label: "Greta (Gen 3)", Group: "showdown-gen3"},
	{Slug: "guitarist-gen3", Label: "Guitarist (Gen 3)", Group: "showdown-gen3"},
	{Slug: "hexmaniac-gen3", Label: "Hex Maniac (Gen 3)", Group: "showdown-gen3"},
	{Slug: "hexmaniac-gen3jp", Label: "Hex Maniac (Gen 3 JP)", Group: "showdown-gen3"},
	{Slug: "hiker-gen3", Label: "Hiker (Gen 3)", Group: "showdown-gen3"},
	{Slug: "interviewers-gen3", Label: "Interviewers (Gen 3)", Group: "showdown-gen3"},
	{Slug: "juan-gen3", Label: "Juan (Gen 3)", Group: "showdown-gen3"},
	{Slug: "juggler-gen3", Label: "Juggler (Gen 3)", Group: "showdown-gen3"},
	{Slug: "kindler-gen3", Label: "Kindler (Gen 3)", Group: "showdown-gen3"},
	{Slug: "koga-gen3", Label: "Koga (Gen 3)", Group: "showdown-gen3"},
	{Slug: "lady-gen3", Label: "Lady (Gen 3)", Group: "showdown-gen3"},
	{Slug: "lance-gen3", Label: "Lance (Gen 3)", Group: "showdown-gen3"},
	{Slug: "lass-gen3", Label: "Lass (Gen 3)", Group: "showdown-gen3"},
	{Slug: "leaf-gen3", Label: "Leaf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "lorelei-gen3", Label: "Lorelei (Gen 3)", Group: "showdown-gen3"},
	{Slug: "ltsurge-gen3", Label: "Lt. Surge (Gen 3)", Group: "showdown-gen3"},
	{Slug: "lucy-gen3", Label: "Lucy (Gen 3)", Group: "showdown-gen3"},
	{Slug: "matt-gen3", Label: "Matt (Gen 3)", Group: "showdown-gen3"},
	{Slug: "maxie-gen3", Label: "Maxie (Gen 3)", Group: "showdown-gen3"},
	{Slug: "may-gen3", Label: "May (Gen 3)", Group: "showdown-gen3"},
	{Slug: "misty-gen3", Label: "Misty (Gen 3)", Group: "showdown-gen3"},
	{Slug: "mrfuji-gen3", Label: "Mr. Fuji (Gen 3)", Group: "showdown-gen3"},
	{Slug: "ninjaboy-gen3", Label: "Ninja Boy (Gen 3)", Group: "showdown-gen3"},
	{Slug: "noland-gen3", Label: "Noland (Gen 3)", Group: "showdown-gen3"},
	{Slug: "norman-gen3", Label: "Norman (Gen 3)", Group: "showdown-gen3"},
	{Slug: "oak-gen3", Label: "Oak (Gen 3)", Group: "showdown-gen3"},
	{Slug: "oldcouple-gen3", Label: "Old Couple (Gen 3)", Group: "showdown-gen3"},
	{Slug: "painter-gen3", Label: "Painter (Gen 3)", Group: "showdown-gen3"},
	{Slug: "parasollady-gen3", Label: "Parasol Lady (Gen 3)", Group: "showdown-gen3"},
	{Slug: "phoebe-gen3", Label: "Phoebe (Gen 3)", Group: "showdown-gen3"},
	{Slug: "picnicker-gen3", Label: "Picnicker (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokefanf-gen3", Label: "Poké Fan F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokefan-gen3", Label: "Poké Fan (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokemaniac-gen3", Label: "Pokemaniac (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokemonbreederf-gen3", Label: "Pokémon Breeder F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokemonbreeder-gen3", Label: "Pokémon Breeder (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokemonrangerf-gen3", Label: "Pokémon Ranger F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "pokemonranger-gen3", Label: "Pokémon Ranger (Gen 3)", Group: "showdown-gen3"},
	{Slug: "psychicf-gen3", Label: "Psychicf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "psychicfjp-gen3", Label: "Psychicfjp (Gen 3)", Group: "showdown-gen3"},
	{Slug: "psychic-gen3", Label: "Psychic (Gen 3)", Group: "showdown-gen3"},
	{Slug: "red-gen3", Label: "Red (Gen 3)", Group: "showdown-gen3"},
	{Slug: "richboy-gen3", Label: "Rich Boy (Gen 3)", Group: "showdown-gen3"},
	{Slug: "rocker-gen3", Label: "Rocker (Gen 3)", Group: "showdown-gen3"},
	{Slug: "roxanne-gen3", Label: "Roxanne (Gen 3)", Group: "showdown-gen3"},
	{Slug: "ruinmaniac-gen3", Label: "Ruin Maniac (Gen 3)", Group: "showdown-gen3"},
	{Slug: "sabrina-gen3", Label: "Sabrina (Gen 3)", Group: "showdown-gen3"},
	{Slug: "sailor-gen3", Label: "Sailor (Gen 3)", Group: "showdown-gen3"},
	{Slug: "sailor-gen3jp", Label: "Sailor (Gen 3 JP)", Group: "showdown-gen3"},
	{Slug: "schoolkidf-gen3", Label: "School Kid F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "schoolkid-gen3", Label: "School Kid (Gen 3)", Group: "showdown-gen3"},
	{Slug: "scientist-gen3", Label: "Scientist (Gen 3)", Group: "showdown-gen3"},
	{Slug: "shelly-gen3", Label: "Shelly (Gen 3)", Group: "showdown-gen3"},
	{Slug: "sidney-gen3", Label: "Sidney (Gen 3)", Group: "showdown-gen3"},
	{Slug: "sisandbro-gen3", Label: "Sisandbro (Gen 3)", Group: "showdown-gen3"},
	{Slug: "spenser-gen3", Label: "Spenser (Gen 3)", Group: "showdown-gen3"},
	{Slug: "srandjr-gen3", Label: "Srandjr (Gen 3)", Group: "showdown-gen3"},
	{Slug: "steven-gen3", Label: "Steven (Gen 3)", Group: "showdown-gen3"},
	{Slug: "supernerd-gen3", Label: "Super Nerd (Gen 3)", Group: "showdown-gen3"},
	{Slug: "swimmerf-gen3", Label: "Swimmerf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "swimmerm-gen3", Label: "Swimmerm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tabitha-gen3", Label: "Tabitha (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tamer-gen3", Label: "Tamer (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tateandliza-gen3", Label: "Tateandliza (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teamaquabeta-gen3", Label: "Teamaquabeta (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teamaquagruntf-gen3", Label: "Teamaquagruntf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teamaquagruntm-gen3", Label: "Teamaquagruntm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teammagmagruntf-gen3", Label: "Teammagmagruntf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teammagmagruntm-gen3", Label: "Teammagmagruntm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teamrocketgruntf-gen3", Label: "Team Rocket Grunt F (Gen 3)", Group: "showdown-gen3"},
	{Slug: "teamrocketgruntm-gen3", Label: "Team Rocket Grunt M (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathletebikerf-gen3", Label: "Triathletebikerf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathletebikerm-gen3", Label: "Triathletebikerm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathleterunnerf-gen3", Label: "Triathleterunnerf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathleterunnerm-gen3", Label: "Triathleterunnerm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathleteswimmerf-gen3", Label: "Triathleteswimmerf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "triathleteswimmerm-gen3", Label: "Triathleteswimmerm (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tuberf-gen3", Label: "Tuberf (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tuber-gen3", Label: "Tuber (Gen 3)", Group: "showdown-gen3"},
	{Slug: "tucker-gen3", Label: "Tucker (Gen 3)", Group: "showdown-gen3"},
	{Slug: "twins-gen3", Label: "Twins (Gen 3)", Group: "showdown-gen3"},
	{Slug: "wallace-gen3", Label: "Wallace (Gen 3)", Group: "showdown-gen3"},
	{Slug: "wally-gen3", Label: "Wally (Gen 3)", Group: "showdown-gen3"},
	{Slug: "wattson-gen3", Label: "Wattson (Gen 3)", Group: "showdown-gen3"},
	{Slug: "winona-gen3", Label: "Winona (Gen 3)", Group: "showdown-gen3"},
	{Slug: "youngcouple-gen3", Label: "Young Couple (Gen 3)", Group: "showdown-gen3"},
	{Slug: "youngster-gen3", Label: "Youngster (Gen 3)", Group: "showdown-gen3"},
}

var showdownGen4DPClasses = []TrainerClass{
	{Slug: "acetrainerf-gen4dp", Label: "Ace Trainer F (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "acetrainer-gen4dp", Label: "Ace Trainer (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "beauty-gen4dp", Label: "Beauty (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "birdkeeper-gen4dp", Label: "Bird Keeper (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "blackbelt-gen4dp", Label: "Black Belt (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "bugcatcher-gen4dp", Label: "Bug Catcher (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "gentleman-gen4dp", Label: "Gentleman (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "lass-gen4dp", Label: "Lass (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "madame-gen4dp", Label: "Madame (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "schoolkid-gen4dp", Label: "School Kid (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "scientist-gen4dp", Label: "Scientist (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "skierf-gen4dp", Label: "Skierf (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "swimmerf-gen4dp", Label: "Swimmerf (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "swimmer-gen4dp", Label: "Swimmer (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "twins-gen4dp", Label: "Twins (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "waiter-gen4dp", Label: "Waiter (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "youngcouple-gen4dp", Label: "Young Couple (Gen 4 DP)", Group: "showdown-gen4dp"},
	{Slug: "youngster-gen4dp", Label: "Youngster (Gen 4 DP)", Group: "showdown-gen4dp"},
}

var showdownGen4Classes = []TrainerClass{
	{Slug: "acetrainerf-gen4", Label: "Ace Trainer F (Gen 4)", Group: "showdown-gen4"},
	{Slug: "acetrainer-gen4", Label: "Ace Trainer (Gen 4)", Group: "showdown-gen4"},
	{Slug: "artist-gen4", Label: "Artist (Gen 4)", Group: "showdown-gen4"},
	{Slug: "battlegirl-gen4", Label: "Battle Girl (Gen 4)", Group: "showdown-gen4"},
	{Slug: "biker-gen4", Label: "Biker (Gen 4)", Group: "showdown-gen4"},
	{Slug: "blackbelt-gen4", Label: "Black Belt (Gen 4)", Group: "showdown-gen4"},
	{Slug: "caitlin-gen4", Label: "Caitlin (Gen 4)", Group: "showdown-gen4"},
	{Slug: "cyclistf-gen4", Label: "Cyclistf (Gen 4)", Group: "showdown-gen4"},
	{Slug: "cyclist-gen4", Label: "Cyclist (Gen 4)", Group: "showdown-gen4"},
	{Slug: "cynthia-gen4", Label: "Cynthia (Gen 4)", Group: "showdown-gen4"},
	{Slug: "fisherman-gen4", Label: "Fisherman (Gen 4)", Group: "showdown-gen4"},
	{Slug: "gentleman-gen4", Label: "Gentleman (Gen 4)", Group: "showdown-gen4"},
	{Slug: "guitarist-gen4", Label: "Guitarist (Gen 4)", Group: "showdown-gen4"},
	{Slug: "hiker-gen4", Label: "Hiker (Gen 4)", Group: "showdown-gen4"},
	{Slug: "lady-gen4", Label: "Lady (Gen 4)", Group: "showdown-gen4"},
	{Slug: "lass-gen4", Label: "Lass (Gen 4)", Group: "showdown-gen4"},
	{Slug: "madame-gen4", Label: "Madame (Gen 4)", Group: "showdown-gen4"},
	{Slug: "maid-gen4", Label: "Maid (Gen 4)", Group: "showdown-gen4"},
	{Slug: "parasollady-gen4", Label: "Parasol Lady (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokefanf-gen4", Label: "Poké Fan F (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokefan-gen4", Label: "Poké Fan (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokemonbreederf-gen4", Label: "Pokémon Breeder F (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokemonbreeder-gen4", Label: "Pokémon Breeder (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokemonrangerf-gen4", Label: "Pokémon Ranger F (Gen 4)", Group: "showdown-gen4"},
	{Slug: "pokemonranger-gen4", Label: "Pokémon Ranger (Gen 4)", Group: "showdown-gen4"},
	{Slug: "policeman-gen4", Label: "Policeman (Gen 4)", Group: "showdown-gen4"},
	{Slug: "psychicf-gen4", Label: "Psychicf (Gen 4)", Group: "showdown-gen4"},
	{Slug: "psychic-gen4", Label: "Psychic (Gen 4)", Group: "showdown-gen4"},
	{Slug: "richboy-gen4", Label: "Rich Boy (Gen 4)", Group: "showdown-gen4"},
	{Slug: "roughneck-gen4", Label: "Roughneck (Gen 4)", Group: "showdown-gen4"},
	{Slug: "schoolkidf-gen4", Label: "School Kid F (Gen 4)", Group: "showdown-gen4"},
	{Slug: "schoolkid-gen4", Label: "School Kid (Gen 4)", Group: "showdown-gen4"},
	{Slug: "scientist-gen4", Label: "Scientist (Gen 4)", Group: "showdown-gen4"},
	{Slug: "swimmerf-gen4", Label: "Swimmerf (Gen 4)", Group: "showdown-gen4"},
	{Slug: "swimmer-gen4", Label: "Swimmer (Gen 4)", Group: "showdown-gen4"},
	{Slug: "twins-gen4", Label: "Twins (Gen 4)", Group: "showdown-gen4"},
	{Slug: "veteran-gen4", Label: "Veteran (Gen 4)", Group: "showdown-gen4"},
	{Slug: "waiter-gen4", Label: "Waiter (Gen 4)", Group: "showdown-gen4"},
	{Slug: "waitress-gen4", Label: "Waitress (Gen 4)", Group: "showdown-gen4"},
	{Slug: "worker-gen4", Label: "Worker (Gen 4)", Group: "showdown-gen4"},
	{Slug: "youngster-gen4", Label: "Youngster (Gen 4)", Group: "showdown-gen4"},
}

var showdownGen5Classes = []TrainerClass{
	{Slug: "beauty-gen5bw2", Label: "Beauty (Gen 5 BW2)", Group: "showdown-gen5"},
	{Slug: "cheren-gen5bw2", Label: "Cheren (Gen 5 BW2)", Group: "showdown-gen5"},
	{Slug: "elesa-gen5bw2", Label: "Elesa (Gen 5 BW2)", Group: "showdown-gen5"},
	{Slug: "ghetsis-gen5bw", Label: "Ghetsis (Gen 5 BW)", Group: "showdown-gen5"},
	{Slug: "iris-gen5bw2", Label: "Iris (Gen 5 BW2)", Group: "showdown-gen5"},
	{Slug: "plasmagruntf-gen5bw", Label: "Plasmagruntf (Gen 5 BW)", Group: "showdown-gen5"},
	{Slug: "plasmagrunt-gen5bw", Label: "Plasmagrunt (Gen 5 BW)", Group: "showdown-gen5"},
}

var showdownGen6Classes = []TrainerClass{
	{Slug: "acetrainerf-gen6", Label: "Ace Trainer F (Gen 6)", Group: "showdown-gen6"},
	{Slug: "acetrainerf-gen6xy", Label: "Ace Trainer F (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "acetrainer-gen6", Label: "Ace Trainer (Gen 6)", Group: "showdown-gen6"},
	{Slug: "acetrainer-gen6xy", Label: "Ace Trainer (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "archie-gen6", Label: "Archie (Gen 6)", Group: "showdown-gen6"},
	{Slug: "aromalady-gen6", Label: "Aroma Lady (Gen 6)", Group: "showdown-gen6"},
	{Slug: "artistf-gen6", Label: "Artistf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "artist-gen6", Label: "Artist (Gen 6)", Group: "showdown-gen6"},
	{Slug: "backpacker-gen6", Label: "Backpacker (Gen 6)", Group: "showdown-gen6"},
	{Slug: "battlegirl-gen6", Label: "Battle Girl (Gen 6)", Group: "showdown-gen6"},
	{Slug: "battlegirl-gen6xy", Label: "Battle Girl (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "beauty-gen6", Label: "Beauty (Gen 6)", Group: "showdown-gen6"},
	{Slug: "beauty-gen6xy", Label: "Beauty (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "birdkeeper-gen6", Label: "Bird Keeper (Gen 6)", Group: "showdown-gen6"},
	{Slug: "blackbelt-gen6", Label: "Black Belt (Gen 6)", Group: "showdown-gen6"},
	{Slug: "brawly-gen6", Label: "Brawly (Gen 6)", Group: "showdown-gen6"},
	{Slug: "bugcatcher-gen6", Label: "Bug Catcher (Gen 6)", Group: "showdown-gen6"},
	{Slug: "bugmaniac-gen6", Label: "Bug Maniac (Gen 6)", Group: "showdown-gen6"},
	{Slug: "cameraman-gen6", Label: "Cameraman (Gen 6)", Group: "showdown-gen6"},
	{Slug: "camper-gen6", Label: "Camper (Gen 6)", Group: "showdown-gen6"},
	{Slug: "collector-gen6", Label: "Collector (Gen 6)", Group: "showdown-gen6"},
	{Slug: "dexio-gen6", Label: "Dexio (Gen 6)", Group: "showdown-gen6"},
	{Slug: "dragontamer-gen6", Label: "Dragon Tamer (Gen 6)", Group: "showdown-gen6"},
	{Slug: "expertf-gen6", Label: "Expertf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "expert-gen6", Label: "Expert (Gen 6)", Group: "showdown-gen6"},
	{Slug: "fisherman-gen6", Label: "Fisherman (Gen 6)", Group: "showdown-gen6"},
	{Slug: "fisherman-gen6xy", Label: "Fisherman (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "flannery-gen6", Label: "Flannery (Gen 6)", Group: "showdown-gen6"},
	{Slug: "gentleman-gen6", Label: "Gentleman (Gen 6)", Group: "showdown-gen6"},
	{Slug: "gentleman-gen6xy", Label: "Gentleman (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "guitarist-gen6", Label: "Guitarist (Gen 6)", Group: "showdown-gen6"},
	{Slug: "hexmaniac-gen6", Label: "Hex Maniac (Gen 6)", Group: "showdown-gen6"},
	{Slug: "hiker-gen6", Label: "Hiker (Gen 6)", Group: "showdown-gen6"},
	{Slug: "interviewers-gen6", Label: "Interviewers (Gen 6)", Group: "showdown-gen6"},
	{Slug: "kindler-gen6", Label: "Kindler (Gen 6)", Group: "showdown-gen6"},
	{Slug: "lady-gen6", Label: "Lady (Gen 6)", Group: "showdown-gen6"},
	{Slug: "lady-gen6oras", Label: "Lady (Gen 6 ORAS)", Group: "showdown-gen6"},
	{Slug: "lass-gen6", Label: "Lass (Gen 6)", Group: "showdown-gen6"},
	{Slug: "lass-gen6oras", Label: "Lass (Gen 6 ORAS)", Group: "showdown-gen6"},
	{Slug: "liza-gen6", Label: "Liza (Gen 6)", Group: "showdown-gen6"},
	{Slug: "madame-gen6", Label: "Madame (Gen 6)", Group: "showdown-gen6"},
	{Slug: "maid-gen6", Label: "Maid (Gen 6)", Group: "showdown-gen6"},
	{Slug: "maxie-gen6", Label: "Maxie (Gen 6)", Group: "showdown-gen6"},
	{Slug: "ninjaboy-gen6", Label: "Ninja Boy (Gen 6)", Group: "showdown-gen6"},
	{Slug: "norman-gen6", Label: "Norman (Gen 6)", Group: "showdown-gen6"},
	{Slug: "parasollady-gen6", Label: "Parasol Lady (Gen 6)", Group: "showdown-gen6"},
	{Slug: "phoebe-gen6", Label: "Phoebe (Gen 6)", Group: "showdown-gen6"},
	{Slug: "picnicker-gen6", Label: "Picnicker (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokefanf-gen6", Label: "Poké Fan F (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokefanf-gen6xy", Label: "Poké Fan F (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "pokefan-gen6", Label: "Poké Fan (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokefan-gen6xy", Label: "Poké Fan (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "pokemaniac-gen6", Label: "Pokemaniac (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokemonbreederf-gen6", Label: "Pokémon Breeder F (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokemonbreederf-gen6xy", Label: "Pokémon Breeder F (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "pokemonbreeder-gen6", Label: "Pokémon Breeder (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokemonbreeder-gen6xy", Label: "Pokémon Breeder (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "pokemonrangerf-gen6", Label: "Pokémon Ranger F (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokemonrangerf-gen6xy", Label: "Pokémon Ranger F (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "pokemonranger-gen6", Label: "Pokémon Ranger (Gen 6)", Group: "showdown-gen6"},
	{Slug: "pokemonranger-gen6xy", Label: "Pokémon Ranger (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "preschoolerf-gen6", Label: "Preschoolerf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "preschooler-gen6", Label: "Preschooler (Gen 6)", Group: "showdown-gen6"},
	{Slug: "psychic-gen6", Label: "Psychic (Gen 6)", Group: "showdown-gen6"},
	{Slug: "reporter-gen6", Label: "Reporter (Gen 6)", Group: "showdown-gen6"},
	{Slug: "richboy-gen6", Label: "Rich Boy (Gen 6)", Group: "showdown-gen6"},
	{Slug: "richboy-gen6xy", Label: "Rich Boy (Gen 6 XY)", Group: "showdown-gen6"},
	{Slug: "risingstarf-gen6", Label: "Risingstarf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "risingstar-gen6", Label: "Risingstar (Gen 6)", Group: "showdown-gen6"},
	{Slug: "roxanne-gen6", Label: "Roxanne (Gen 6)", Group: "showdown-gen6"},
	{Slug: "ruinmaniac-gen6", Label: "Ruin Maniac (Gen 6)", Group: "showdown-gen6"},
	{Slug: "sailor-gen6", Label: "Sailor (Gen 6)", Group: "showdown-gen6"},
	{Slug: "schoolkidf-gen6", Label: "School Kid F (Gen 6)", Group: "showdown-gen6"},
	{Slug: "schoolkid-gen6", Label: "School Kid (Gen 6)", Group: "showdown-gen6"},
	{Slug: "scientistf-gen6", Label: "Scientistf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "scientist-gen6", Label: "Scientist (Gen 6)", Group: "showdown-gen6"},
	{Slug: "sina-gen6", Label: "Sina (Gen 6)", Group: "showdown-gen6"},
	{Slug: "steven-gen6", Label: "Steven (Gen 6)", Group: "showdown-gen6"},
	{Slug: "swimmerf2-gen6", Label: "Swimmerf2 (Gen 6)", Group: "showdown-gen6"},
	{Slug: "swimmerf-gen6", Label: "Swimmerf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "swimmer-gen6", Label: "Swimmer (Gen 6)", Group: "showdown-gen6"},
	{Slug: "tateandliza-gen6", Label: "Tateandliza (Gen 6)", Group: "showdown-gen6"},
	{Slug: "tate-gen6", Label: "Tate (Gen 6)", Group: "showdown-gen6"},
	{Slug: "triathletebiker-gen6", Label: "Triathletebiker (Gen 6)", Group: "showdown-gen6"},
	{Slug: "triathleterunner-gen6", Label: "Triathleterunner (Gen 6)", Group: "showdown-gen6"},
	{Slug: "triathleteswimmer-gen6", Label: "Triathleteswimmer (Gen 6)", Group: "showdown-gen6"},
	{Slug: "tuberf-gen6", Label: "Tuberf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "tuber-gen6", Label: "Tuber (Gen 6)", Group: "showdown-gen6"},
	{Slug: "twins-gen6", Label: "Twins (Gen 6)", Group: "showdown-gen6"},
	{Slug: "veteranf-gen6", Label: "Veteranf (Gen 6)", Group: "showdown-gen6"},
	{Slug: "veteran-gen6", Label: "Veteran (Gen 6)", Group: "showdown-gen6"},
	{Slug: "waitress-gen6", Label: "Waitress (Gen 6)", Group: "showdown-gen6"},
	{Slug: "wallace-gen6", Label: "Wallace (Gen 6)", Group: "showdown-gen6"},
	{Slug: "winona-gen6", Label: "Winona (Gen 6)", Group: "showdown-gen6"},
	{Slug: "worker2-gen6", Label: "Worker2 (Gen 6)", Group: "showdown-gen6"},
	{Slug: "worker-gen6", Label: "Worker (Gen 6)", Group: "showdown-gen6"},
	{Slug: "youngcouple-gen6", Label: "Young Couple (Gen 6)", Group: "showdown-gen6"},
	{Slug: "youngster-gen6", Label: "Youngster (Gen 6)", Group: "showdown-gen6"},
	{Slug: "youngster-gen6xy", Label: "Youngster (Gen 6 XY)", Group: "showdown-gen6"},
}

var showdownGen7Classes = []TrainerClass{
	{Slug: "acetrainerf-gen7", Label: "Ace Trainer F (Gen 7)", Group: "showdown-gen7"},
	{Slug: "acetrainer-gen7", Label: "Ace Trainer (Gen 7)", Group: "showdown-gen7"},
	{Slug: "anabel-gen7", Label: "Anabel (Gen 7)", Group: "showdown-gen7"},
	{Slug: "beauty-gen7", Label: "Beauty (Gen 7)", Group: "showdown-gen7"},
	{Slug: "blackbelt-gen7", Label: "Black Belt (Gen 7)", Group: "showdown-gen7"},
	{Slug: "blue-gen7", Label: "Blue (Gen 7)", Group: "showdown-gen7"},
	{Slug: "collector-gen7", Label: "Collector (Gen 7)", Group: "showdown-gen7"},
	{Slug: "colress-gen7", Label: "Colress (Gen 7)", Group: "showdown-gen7"},
	{Slug: "cook-gen7", Label: "Cook (Gen 7)", Group: "showdown-gen7"},
	{Slug: "cynthia-gen7", Label: "Cynthia (Gen 7)", Group: "showdown-gen7"},
	{Slug: "dancer-gen7", Label: "Dancer (Gen 7)", Group: "showdown-gen7"},
	{Slug: "fisherman-gen7", Label: "Fisherman (Gen 7)", Group: "showdown-gen7"},
	{Slug: "gentleman-gen7", Label: "Gentleman (Gen 7)", Group: "showdown-gen7"},
	{Slug: "grimsley-gen7", Label: "Grimsley (Gen 7)", Group: "showdown-gen7"},
	{Slug: "hiker-gen7", Label: "Hiker (Gen 7)", Group: "showdown-gen7"},
	{Slug: "janitor-gen7", Label: "Janitor (Gen 7)", Group: "showdown-gen7"},
	{Slug: "lass-gen7", Label: "Lass (Gen 7)", Group: "showdown-gen7"},
	{Slug: "madame-gen7", Label: "Madame (Gen 7)", Group: "showdown-gen7"},
	{Slug: "pokemonbreederf-gen7", Label: "Pokémon Breeder F (Gen 7)", Group: "showdown-gen7"},
	{Slug: "pokemonbreeder-gen7", Label: "Pokémon Breeder (Gen 7)", Group: "showdown-gen7"},
	{Slug: "policeman-gen7", Label: "Policeman (Gen 7)", Group: "showdown-gen7"},
	{Slug: "preschoolerf-gen7", Label: "Preschoolerf (Gen 7)", Group: "showdown-gen7"},
	{Slug: "preschooler-gen7", Label: "Preschooler (Gen 7)", Group: "showdown-gen7"},
	{Slug: "punkgirl-gen7", Label: "Punkgirl (Gen 7)", Group: "showdown-gen7"},
	{Slug: "punkguy-gen7", Label: "Punkguy (Gen 7)", Group: "showdown-gen7"},
	{Slug: "red-gen7", Label: "Red (Gen 7)", Group: "showdown-gen7"},
	{Slug: "scientist-gen7", Label: "Scientist (Gen 7)", Group: "showdown-gen7"},
	{Slug: "swimmerf2-gen7", Label: "Swimmerf2 (Gen 7)", Group: "showdown-gen7"},
	{Slug: "swimmerf-gen7", Label: "Swimmerf (Gen 7)", Group: "showdown-gen7"},
	{Slug: "swimmer-gen7", Label: "Swimmer (Gen 7)", Group: "showdown-gen7"},
	{Slug: "teacher-gen7", Label: "Teacher (Gen 7)", Group: "showdown-gen7"},
	{Slug: "veteranf-gen7", Label: "Veteranf (Gen 7)", Group: "showdown-gen7"},
	{Slug: "veteran-gen7", Label: "Veteran (Gen 7)", Group: "showdown-gen7"},
	{Slug: "worker-gen7", Label: "Worker (Gen 7)", Group: "showdown-gen7"},
	{Slug: "youngster-gen7", Label: "Youngster (Gen 7)", Group: "showdown-gen7"},
}

var showdownGen8Classes = []TrainerClass{
	{Slug: "artist-gen8", Label: "Artist (Gen 8)", Group: "showdown-gen8"},
	{Slug: "backpacker-gen8", Label: "Backpacker (Gen 8)", Group: "showdown-gen8"},
	{Slug: "beauty-gen8", Label: "Beauty (Gen 8)", Group: "showdown-gen8"},
	{Slug: "blackbelt-gen8", Label: "Black Belt (Gen 8)", Group: "showdown-gen8"},
	{Slug: "cameraman-gen8", Label: "Cameraman (Gen 8)", Group: "showdown-gen8"},
	{Slug: "clerkf-gen8", Label: "Clerkf (Gen 8)", Group: "showdown-gen8"},
	{Slug: "clerk-gen8", Label: "Clerk (Gen 8)", Group: "showdown-gen8"},
	{Slug: "dancer-gen8", Label: "Dancer (Gen 8)", Group: "showdown-gen8"},
	{Slug: "doctorf-gen8", Label: "Doctorf (Gen 8)", Group: "showdown-gen8"},
	{Slug: "doctor-gen8", Label: "Doctor (Gen 8)", Group: "showdown-gen8"},
	{Slug: "fisher-gen8", Label: "Fisher (Gen 8)", Group: "showdown-gen8"},
	{Slug: "gentleman-gen8", Label: "Gentleman (Gen 8)", Group: "showdown-gen8"},
	{Slug: "hiker-gen8", Label: "Hiker (Gen 8)", Group: "showdown-gen8"},
	{Slug: "lass-gen8", Label: "Lass (Gen 8)", Group: "showdown-gen8"},
	{Slug: "madame-gen8", Label: "Madame (Gen 8)", Group: "showdown-gen8"},
	{Slug: "model-gen8", Label: "Model (Gen 8)", Group: "showdown-gen8"},
	{Slug: "musician-gen8", Label: "Musician (Gen 8)", Group: "showdown-gen8"},
	{Slug: "pokekidf-gen8", Label: "Pokekidf (Gen 8)", Group: "showdown-gen8"},
	{Slug: "pokekid-gen8", Label: "Pokekid (Gen 8)", Group: "showdown-gen8"},
	{Slug: "pokemonbreederf-gen8", Label: "Pokémon Breeder F (Gen 8)", Group: "showdown-gen8"},
	{Slug: "pokemonbreeder-gen8", Label: "Pokémon Breeder (Gen 8)", Group: "showdown-gen8"},
	{Slug: "policeman-gen8", Label: "Policeman (Gen 8)", Group: "showdown-gen8"},
	{Slug: "reporter-gen8", Label: "Reporter (Gen 8)", Group: "showdown-gen8"},
	{Slug: "schoolkidf-gen8", Label: "School Kid F (Gen 8)", Group: "showdown-gen8"},
	{Slug: "schoolkid-gen8", Label: "School Kid (Gen 8)", Group: "showdown-gen8"},
	{Slug: "swimmerf-gen8", Label: "Swimmerf (Gen 8)", Group: "showdown-gen8"},
	{Slug: "swimmer-gen8", Label: "Swimmer (Gen 8)", Group: "showdown-gen8"},
	{Slug: "workerf-gen8", Label: "Workerf (Gen 8)", Group: "showdown-gen8"},
	{Slug: "worker-gen8", Label: "Worker (Gen 8)", Group: "showdown-gen8"},
	{Slug: "youngster-gen8", Label: "Youngster (Gen 8)", Group: "showdown-gen8"},
}

var showdownGen9Classes = []TrainerClass{
	{Slug: "artist-gen9", Label: "Artist (Gen 9)", Group: "showdown-gen9"},
	{Slug: "backpacker-gen9", Label: "Backpacker (Gen 9)", Group: "showdown-gen9"},
	{Slug: "beauty-gen9", Label: "Beauty (Gen 9)", Group: "showdown-gen9"},
	{Slug: "blackbelt-gen9", Label: "Black Belt (Gen 9)", Group: "showdown-gen9"},
	{Slug: "bodybuilderf-gen9", Label: "Bodybuilderf (Gen 9)", Group: "showdown-gen9"},
	{Slug: "bodybuilder-gen9", Label: "Bodybuilder (Gen 9)", Group: "showdown-gen9"},
	{Slug: "cabbie-gen9", Label: "Cabbie (Gen 9)", Group: "showdown-gen9"},
	{Slug: "cook-gen9", Label: "Cook (Gen 9)", Group: "showdown-gen9"},
	{Slug: "delinquentf2-gen9", Label: "Delinquentf2 (Gen 9)", Group: "showdown-gen9"},
	{Slug: "delinquentf-gen9", Label: "Delinquentf (Gen 9)", Group: "showdown-gen9"},
	{Slug: "delinquent-gen9", Label: "Delinquent (Gen 9)", Group: "showdown-gen9"},
	{Slug: "dragontamer-gen9", Label: "Dragon Tamer (Gen 9)", Group: "showdown-gen9"},
	{Slug: "hiker-gen9", Label: "Hiker (Gen 9)", Group: "showdown-gen9"},
	{Slug: "janitor-gen9", Label: "Janitor (Gen 9)", Group: "showdown-gen9"},
	{Slug: "musician-gen9", Label: "Musician (Gen 9)", Group: "showdown-gen9"},
	{Slug: "officeworkerf-gen9", Label: "Officeworkerf (Gen 9)", Group: "showdown-gen9"},
	{Slug: "officeworker-gen9", Label: "Officeworker (Gen 9)", Group: "showdown-gen9"},
	{Slug: "pokemaniac-gen9", Label: "Pokemaniac (Gen 9)", Group: "showdown-gen9"},
	{Slug: "scientist-gen9", Label: "Scientist (Gen 9)", Group: "showdown-gen9"},
	{Slug: "waiter-gen9", Label: "Waiter (Gen 9)", Group: "showdown-gen9"},
	{Slug: "waitress-gen9", Label: "Waitress (Gen 9)", Group: "showdown-gen9"},
	{Slug: "worker-gen9", Label: "Worker (Gen 9)", Group: "showdown-gen9"},
	{Slug: "youngster-gen9", Label: "Youngster (Gen 9)", Group: "showdown-gen9"},
}

var showdownLGPEClasses = []TrainerClass{
	{Slug: "agatha-lgpe", Label: "Agatha (LGPE)", Group: "showdown-lgpe"},
	{Slug: "blaine-lgpe", Label: "Blaine (LGPE)", Group: "showdown-lgpe"},
	{Slug: "blue-lgpe", Label: "Blue (LGPE)", Group: "showdown-lgpe"},
	{Slug: "brock-lgpe", Label: "Brock (LGPE)", Group: "showdown-lgpe"},
	{Slug: "burglar-lgpe", Label: "Burglar (LGPE)", Group: "showdown-lgpe"},
	{Slug: "channeler-lgpe", Label: "Channeler (LGPE)", Group: "showdown-lgpe"},
	{Slug: "erika-lgpe", Label: "Erika (LGPE)", Group: "showdown-lgpe"},
	{Slug: "gentleman-lgpe", Label: "Gentleman (LGPE)", Group: "showdown-lgpe"},
	{Slug: "giovanni-lgpe", Label: "Giovanni (LGPE)", Group: "showdown-lgpe"},
	{Slug: "koga-lgpe", Label: "Koga (LGPE)", Group: "showdown-lgpe"},
	{Slug: "lance-lgpe", Label: "Lance (LGPE)", Group: "showdown-lgpe"},
	{Slug: "lorelei-lgpe", Label: "Lorelei (LGPE)", Group: "showdown-lgpe"},
	{Slug: "mina-lgpe", Label: "Mina (LGPE)", Group: "showdown-lgpe"},
	{Slug: "misty-lgpe", Label: "Misty (LGPE)", Group: "showdown-lgpe"},
	{Slug: "psychic-lgpe", Label: "Psychic (LGPE)", Group: "showdown-lgpe"},
	{Slug: "red-lgpe", Label: "Red (LGPE)", Group: "showdown-lgpe"},
	{Slug: "sabrina-lgpe", Label: "Sabrina (LGPE)", Group: "showdown-lgpe"},
	{Slug: "worker-lgpe", Label: "Worker (LGPE)", Group: "showdown-lgpe"},
}

var showdownMastersClasses = []TrainerClass{
	{Slug: "acerola-masters", Label: "Acerola (Masters)", Group: "showdown-masters"},
	{Slug: "acerola-masters2", Label: "Acerola (Masters 2)", Group: "showdown-masters"},
	{Slug: "acerola-masters3", Label: "Acerola (Masters 3)", Group: "showdown-masters"},
	{Slug: "adaman-masters", Label: "Adaman (Masters)", Group: "showdown-masters"},
	{Slug: "allister-masters", Label: "Allister (Masters)", Group: "showdown-masters"},
	{Slug: "barry-masters", Label: "Barry (Masters)", Group: "showdown-masters"},
	{Slug: "bea-masters", Label: "Bea (Masters)", Group: "showdown-masters"},
	{Slug: "beauty-masters", Label: "Beauty (Masters)", Group: "showdown-masters"},
	{Slug: "bede-masters", Label: "Bede (Masters)", Group: "showdown-masters"},
	{Slug: "bianca-masters", Label: "Bianca (Masters)", Group: "showdown-masters"},
	{Slug: "blue-masters", Label: "Blue (Masters)", Group: "showdown-masters"},
	{Slug: "blue-masters2", Label: "Blue (Masters 2)", Group: "showdown-masters"},
	{Slug: "brendan-masters", Label: "Brendan (Masters)", Group: "showdown-masters"},
	{Slug: "brendan-masters2", Label: "Brendan (Masters 2)", Group: "showdown-masters"},
	{Slug: "brock-masters", Label: "Brock (Masters)", Group: "showdown-masters"},
	{Slug: "bugsy-masters", Label: "Bugsy (Masters)", Group: "showdown-masters"},
	{Slug: "burgh-masters", Label: "Burgh (Masters)", Group: "showdown-masters"},
	{Slug: "caitlin-masters", Label: "Caitlin (Masters)", Group: "showdown-masters"},
	{Slug: "calem-masters", Label: "Calem (Masters)", Group: "showdown-masters"},
	{Slug: "candice-masters", Label: "Candice (Masters)", Group: "showdown-masters"},
	{Slug: "cheren-masters", Label: "Cheren (Masters)", Group: "showdown-masters"},
	{Slug: "clair-masters", Label: "Clair (Masters)", Group: "showdown-masters"},
	{Slug: "collector-masters", Label: "Collector (Masters)", Group: "showdown-masters"},
	{Slug: "cynthia-masters", Label: "Cynthia (Masters)", Group: "showdown-masters"},
	{Slug: "cynthia-masters2", Label: "Cynthia (Masters 2)", Group: "showdown-masters"},
	{Slug: "cynthia-masters3", Label: "Cynthia (Masters 3)", Group: "showdown-masters"},
	{Slug: "cynthia-masters4", Label: "Cynthia (Masters 4)", Group: "showdown-masters"},
	{Slug: "cyrus-masters", Label: "Cyrus (Masters)", Group: "showdown-masters"},
	{Slug: "dawn-masters", Label: "Dawn (Masters)", Group: "showdown-masters"},
	{Slug: "dawn-masters2", Label: "Dawn (Masters 2)", Group: "showdown-masters"},
	{Slug: "dawn-masters3", Label: "Dawn (Masters 3)", Group: "showdown-masters"},
	{Slug: "diantha-masters", Label: "Diantha (Masters)", Group: "showdown-masters"},
	{Slug: "diantha-masters2", Label: "Diantha (Masters 2)", Group: "showdown-masters"},
	{Slug: "elesa-masters", Label: "Elesa (Masters)", Group: "showdown-masters"},
	{Slug: "elesa-masters2", Label: "Elesa (Masters 2)", Group: "showdown-masters"},
	{Slug: "elesa-masters3", Label: "Elesa (Masters 3)", Group: "showdown-masters"},
	{Slug: "elio-masters", Label: "Elio (Masters)", Group: "showdown-masters"},
	{Slug: "emmet-masters", Label: "Emmet (Masters)", Group: "showdown-masters"},
	{Slug: "erika-masters", Label: "Erika (Masters)", Group: "showdown-masters"},
	{Slug: "erika-masters2", Label: "Erika (Masters 2)", Group: "showdown-masters"},
	{Slug: "erika-masters3", Label: "Erika (Masters 3)", Group: "showdown-masters"},
	{Slug: "ethan-masters", Label: "Ethan (Masters)", Group: "showdown-masters"},
	{Slug: "gardenia-masters", Label: "Gardenia (Masters)", Group: "showdown-masters"},
	{Slug: "giovanni-masters", Label: "Giovanni (Masters)", Group: "showdown-masters"},
	{Slug: "gladion-masters", Label: "Gladion (Masters)", Group: "showdown-masters"},
	{Slug: "gloria-masters", Label: "Gloria (Masters)", Group: "showdown-masters"},
	{Slug: "grimsley-masters", Label: "Grimsley (Masters)", Group: "showdown-masters"},
	{Slug: "guzma-masters", Label: "Guzma (Masters)", Group: "showdown-masters"},
	{Slug: "hau-masters", Label: "Hau (Masters)", Group: "showdown-masters"},
	{Slug: "hilbert-masters", Label: "Hilbert (Masters)", Group: "showdown-masters"},
	{Slug: "hilbert-masters2", Label: "Hilbert (Masters 2)", Group: "showdown-masters"},
	{Slug: "hilda-masters", Label: "Hilda (Masters)", Group: "showdown-masters"},
	{Slug: "hilda-masters2", Label: "Hilda (Masters 2)", Group: "showdown-masters"},
	{Slug: "hilda-masters3", Label: "Hilda (Masters 3)", Group: "showdown-masters"},
	{Slug: "hop-masters", Label: "Hop (Masters)", Group: "showdown-masters"},
	{Slug: "ingo-masters", Label: "Ingo (Masters)", Group: "showdown-masters"},
	{Slug: "iono-masters", Label: "Iono (Masters)", Group: "showdown-masters"},
	{Slug: "iono-masters2", Label: "Iono (Masters 2)", Group: "showdown-masters"},
	{Slug: "irida-masters", Label: "Irida (Masters)", Group: "showdown-masters"},
	{Slug: "iris-masters", Label: "Iris (Masters)", Group: "showdown-masters"},
	{Slug: "jasmine-masters", Label: "Jasmine (Masters)", Group: "showdown-masters"},
	{Slug: "jasmine-masters2", Label: "Jasmine (Masters 2)", Group: "showdown-masters"},
	{Slug: "korrina-masters", Label: "Korrina (Masters)", Group: "showdown-masters"},
	{Slug: "kris-masters", Label: "Kris (Masters)", Group: "showdown-masters"},
	{Slug: "lana-masters", Label: "Lana (Masters)", Group: "showdown-masters"},
	{Slug: "lance-masters", Label: "Lance (Masters)", Group: "showdown-masters"},
	{Slug: "lance-masters2", Label: "Lance (Masters 2)", Group: "showdown-masters"},
	{Slug: "leaf-masters", Label: "Leaf (Masters)", Group: "showdown-masters"},
	{Slug: "leaf-masters2", Label: "Leaf (Masters 2)", Group: "showdown-masters"},
	{Slug: "leon-masters", Label: "Leon (Masters)", Group: "showdown-masters"},
	{Slug: "leon-masters2", Label: "Leon (Masters 2)", Group: "showdown-masters"},
	{Slug: "lillie-masters", Label: "Lillie (Masters)", Group: "showdown-masters"},
	{Slug: "lillie-masters2", Label: "Lillie (Masters 2)", Group: "showdown-masters"},
	{Slug: "lillie-masters3", Label: "Lillie (Masters 3)", Group: "showdown-masters"},
	{Slug: "lisia-masters", Label: "Lisia (Masters)", Group: "showdown-masters"},
	{Slug: "liza-masters", Label: "Liza (Masters)", Group: "showdown-masters"},
	{Slug: "lusamine-masters", Label: "Lusamine (Masters)", Group: "showdown-masters"},
	{Slug: "lyra-masters", Label: "Lyra (Masters)", Group: "showdown-masters"},
	{Slug: "lyra-masters2", Label: "Lyra (Masters 2)", Group: "showdown-masters"},
	{Slug: "lysandre-masters", Label: "Lysandre (Masters)", Group: "showdown-masters"},
	{Slug: "mallow-masters", Label: "Mallow (Masters)", Group: "showdown-masters"},
	{Slug: "marley-masters", Label: "Marley (Masters)", Group: "showdown-masters"},
	{Slug: "marnie-masters", Label: "Marnie (Masters)", Group: "showdown-masters"},
	{Slug: "marnie-masters2", Label: "Marnie (Masters 2)", Group: "showdown-masters"},
	{Slug: "marnie-masters3", Label: "Marnie (Masters 3)", Group: "showdown-masters"},
	{Slug: "may-masters", Label: "May (Masters)", Group: "showdown-masters"},
	{Slug: "may-masters2", Label: "May (Masters 2)", Group: "showdown-masters"},
	{Slug: "may-masters3", Label: "May (Masters 3)", Group: "showdown-masters"},
	{Slug: "may-masters4", Label: "May (Masters 4)", Group: "showdown-masters"},
	{Slug: "mina-masters", Label: "Mina (Masters)", Group: "showdown-masters"},
	{Slug: "misty-masters", Label: "Misty (Masters)", Group: "showdown-masters"},
	{Slug: "morty-masters", Label: "Morty (Masters)", Group: "showdown-masters"},
	{Slug: "morty-masters2", Label: "Morty (Masters 2)", Group: "showdown-masters"},
	{Slug: "morty-masters3", Label: "Morty (Masters 3)", Group: "showdown-masters"},
	{Slug: "nate-masters", Label: "Nate (Masters)", Group: "showdown-masters"},
	{Slug: "nemona-masters", Label: "Nemona (Masters)", Group: "showdown-masters"},
	{Slug: "nessa-masters", Label: "Nessa (Masters)", Group: "showdown-masters"},
	{Slug: "n-masters", Label: "N (Masters)", Group: "showdown-masters"},
	{Slug: "n-masters2", Label: "N (Masters 2)", Group: "showdown-masters"},
	{Slug: "n-masters3", Label: "N (Masters 3)", Group: "showdown-masters"},
	{Slug: "paulo-masters", Label: "Paulo (Masters)", Group: "showdown-masters"},
	{Slug: "phoebe-masters", Label: "Phoebe (Masters)", Group: "showdown-masters"},
	{Slug: "piers-masters", Label: "Piers (Masters)", Group: "showdown-masters"},
	{Slug: "punkgirl-masters", Label: "Punkgirl (Masters)", Group: "showdown-masters"},
	{Slug: "raihan-masters", Label: "Raihan (Masters)", Group: "showdown-masters"},
	{Slug: "red-masters", Label: "Red (Masters)", Group: "showdown-masters"},
	{Slug: "red-masters2", Label: "Red (Masters 2)", Group: "showdown-masters"},
	{Slug: "red-masters3", Label: "Red (Masters 3)", Group: "showdown-masters"},
	{Slug: "rosa-masters", Label: "Rosa (Masters)", Group: "showdown-masters"},
	{Slug: "rosa-masters2", Label: "Rosa (Masters 2)", Group: "showdown-masters"},
	{Slug: "rosa-masters3", Label: "Rosa (Masters 3)", Group: "showdown-masters"},
	{Slug: "roxanne-masters", Label: "Roxanne (Masters)", Group: "showdown-masters"},
	{Slug: "roxie-masters", Label: "Roxie (Masters)", Group: "showdown-masters"},
	{Slug: "sabrina-masters", Label: "Sabrina (Masters)", Group: "showdown-masters"},
	{Slug: "scottie-masters", Label: "Scottie (Masters)", Group: "showdown-masters"},
	{Slug: "selene-masters", Label: "Selene (Masters)", Group: "showdown-masters"},
	{Slug: "selene-masters2", Label: "Selene (Masters 2)", Group: "showdown-masters"},
	{Slug: "serena-masters", Label: "Serena (Masters)", Group: "showdown-masters"},
	{Slug: "serena-masters2", Label: "Serena (Masters 2)", Group: "showdown-masters"},
	{Slug: "serena-masters3", Label: "Serena (Masters 3)", Group: "showdown-masters"},
	{Slug: "shauna-masters", Label: "Shauna (Masters)", Group: "showdown-masters"},
	{Slug: "shauntal-masters", Label: "Shauntal (Masters)", Group: "showdown-masters"},
	{Slug: "siebold-masters", Label: "Siebold (Masters)", Group: "showdown-masters"},
	{Slug: "silver-masters", Label: "Silver (Masters)", Group: "showdown-masters"},
	{Slug: "skyla-masters", Label: "Skyla (Masters)", Group: "showdown-masters"},
	{Slug: "skyla-masters2", Label: "Skyla (Masters 2)", Group: "showdown-masters"},
	{Slug: "sonia-masters", Label: "Sonia (Masters)", Group: "showdown-masters"},
	{Slug: "steven-masters", Label: "Steven (Masters)", Group: "showdown-masters"},
	{Slug: "steven-masters2", Label: "Steven (Masters 2)", Group: "showdown-masters"},
	{Slug: "steven-masters3", Label: "Steven (Masters 3)", Group: "showdown-masters"},
	{Slug: "steven-masters4", Label: "Steven (Masters 4)", Group: "showdown-masters"},
	{Slug: "streetthug-masters", Label: "Streetthug (Masters)", Group: "showdown-masters"},
	{Slug: "swimmer-masters", Label: "Swimmer (Masters)", Group: "showdown-masters"},
	{Slug: "sycamore-masters", Label: "Prof. Sycamore (Masters)", Group: "showdown-masters"},
	{Slug: "tate-masters", Label: "Tate (Masters)", Group: "showdown-masters"},
	{Slug: "tina-masters", Label: "Tina (Masters)", Group: "showdown-masters"},
	{Slug: "victor-masters", Label: "Victor (Masters)", Group: "showdown-masters"},
	{Slug: "viola-masters", Label: "Viola (Masters)", Group: "showdown-masters"},
	{Slug: "volkner-masters", Label: "Volkner (Masters)", Group: "showdown-masters"},
	{Slug: "wallace-masters", Label: "Wallace (Masters)", Group: "showdown-masters"},
	{Slug: "wally-masters", Label: "Wally (Masters)", Group: "showdown-masters"},
	{Slug: "whitney-masters", Label: "Whitney (Masters)", Group: "showdown-masters"},
	{Slug: "youngster-masters", Label: "Youngster (Masters)", Group: "showdown-masters"},
	{Slug: "zinnia-masters", Label: "Zinnia (Masters)", Group: "showdown-masters"},
}

var showdownGOClasses = []TrainerClass{
	{Slug: "playerf-go", Label: "Player F (GO)", Group: "showdown-go"},
	{Slug: "player-go", Label: "Player (GO)", Group: "showdown-go"},
}

