// Package costumes resolves shiny costume sprites for the shiny checklist and public profiles.
//
// It is backed by two embedded JSON files:
//
//   - catalog.json  GENERATED by cmd/synccostumes from the mined PokeMiners asset tree.
//     Holds every costume code that actually has shiny art, and exactly which
//     species have it. Never hand-edited.
//   - labels.json   CURATED, and hand-ordered for reading. Maps the human labels trainers see and
//     type onto those codes. Only ever appended to, never rewritten: user_shinies.costume
//     is free text, so a label is user data and renaming one orphans entries people have
//     already saved. LabelsJSON is the one writer, and it splices rather than marshals.
//
// Resolution requires a catalog hit, so a label whose code has no art upstream is simply
// inert. That is what makes a pre-release costume safe to record without a "pending" flag,
// and it is what stops a mistyped code from silently emitting a URL that 404s.
package costumes

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
)

//go:embed catalog.json
var catalogJSON []byte

//go:embed labels.json
var labelsJSON []byte

// SpritePath is the route the sprites are served from. We proxy and cache them ourselves
// rather than hotlinking, so the origin is hit once per sprite and users' browsers only ever
// talk to us.
const SpritePath = "/api/costume-sprite/"

type entry struct {
	Pretty    string `json:"pretty"`
	Suggested string `json:"suggested"`
	Dex       []int  `json:"dex"`
}

// Unnamed is a costume the game has that nobody has given a label yet, and which is therefore
// invisible in the picker. This is the review backlog.
type Unnamed struct {
	Code      string `json:"code"`
	Pretty    string `json:"pretty"`    // the masterfile's machine name
	Suggested string `json:"suggested"` // what Dittobase calls it, if it knows
	Dex       []int  `json:"dex"`
	SpriteURL string `json:"sprite_url"` // shiny art for the first eligible species
}

type catalog struct {
	AssetBase    string            `json:"assetBase"`
	SourceCommit string            `json:"sourceCommit"`
	Codes        map[string]*entry `json:"codes"`
}

type shared struct {
	Label string `json:"label"`
	Code  string `json:"code"`
}

// labelSet mirrors labels.json. The _comment fields are carried through as raw JSON so that the
// GitHub sync can write the file back without silently deleting the hand-written notes in it, and
// field order here is the key order in the emitted file.
type labelSet struct {
	Comment                json.RawMessage              `json:"_comment,omitempty"`
	Species                map[string]map[string]string `json:"species"`
	Shared                 []shared                     `json:"shared"`
	Aliases                map[string]string            `json:"aliases"`
	HiddenComment          json.RawMessage              `json:"_hidden_comment,omitempty"`
	Hidden                 []string                     `json:"hidden"`
	NameCheckIgnoreComment json.RawMessage              `json:"_nameCheckIgnore_comment,omitempty"`
	NameCheckIgnore        []string                     `json:"nameCheckIgnore,omitempty"`
}

var (
	cat catalog
	lab labelSet // embedded, curated, immutable after init

	// Runtime naming, mirroring internal/i18n: an overlay merged over the embedded set and
	// hot-swapped under a lock. Maps and slices in `effective` are replaced wholesale, never
	// mutated, so a reader that has taken the pointer can use it without holding the lock.
	mu        sync.RWMutex
	ov        overlayFile
	effective *labelSet
	dir       string
)

func init() {
	if err := json.Unmarshal(catalogJSON, &cat); err != nil {
		panic("costumes: bad catalog.json: " + err.Error())
	}
	if err := json.Unmarshal(labelsJSON, &lab); err != nil {
		panic("costumes: bad labels.json: " + err.Error())
	}
	// Usable before Init: with no overlay, the effective set is just the embedded one, which is
	// what tests and any non-server consumer get.
	rebuildLocked()
}

// labels is the merged view every reader resolves against.
func labels() *labelSet {
	mu.RLock()
	defer mu.RUnlock()
	return effective
}

// covers reports whether a code has shiny art for this species.
func covers(code string, dex int) bool {
	e, ok := cat.Codes[code]
	return ok && slices.Contains(e.Dex, dex)
}

// resolve maps a label to a costume code for a species: a curated override wins, else a
// shared costume the species is eligible for. Both tiers require the code to have shiny art
// for this dex, so an unknown or stale label simply misses.
func resolve(dex int, species, label string) (string, bool) {
	if label == "" || dex == 0 {
		return "", false
	}
	l := labels()
	if canonical, ok := l.Aliases[label]; ok {
		label = canonical
	}
	if code, ok := l.Species[species][label]; ok && covers(code, dex) {
		return code, true
	}
	for _, s := range l.Shared {
		if s.Label == label && covers(s.Code, dex) {
			return s.Code, true
		}
	}
	return "", false
}

// SpriteURL returns the app-local URL of the shiny costume sprite, or false if the costume
// does not resolve (callers fall back to the plain shiny).
func SpriteURL(dex int, species, label string) (string, bool) {
	code, ok := resolve(dex, species, label)
	if !ok {
		return "", false
	}
	return SpritePath + assetFile(dex, code), true
}

// LabelsForDex lists the costume labels to offer for a species: its curated overrides, then
// any shared costume it is eligible for, skipping a code an override already covers so the
// same art is never offered under two labels.
func LabelsForDex(dex int, species string) []string {
	l := labels()
	var out []string
	usedCodes := map[string]bool{}

	for label, code := range l.Species[species] {
		if !covers(code, dex) {
			continue
		}
		out = append(out, label)
		usedCodes[code] = true
	}
	// Go map order is random, so sort: the picker must not reshuffle between requests, and the
	// TypeScript resolver sorts identically so the two stay in lockstep.
	sort.Strings(out)

	for _, s := range l.Shared {
		if usedCodes[s.Code] || slices.Contains(out, s.Label) || !covers(s.Code, dex) {
			continue
		}
		out = append(out, s.Label)
	}
	return out
}

// SpriteURLFor is the shiny sprite for one species wearing one costume, or false if that species
// has no art for it.
//
// It gates on the catalog for the same reason AllowedFile does: a URL this returns is one the
// sprite proxy will actually serve, so a caller cannot render a broken image. The admin review tab
// uses it to show a costume on every species that has it, because a costume is named from the whole
// set, not from whichever species happens to be first.
func SpriteURLFor(dex int, code string) (string, bool) {
	if !covers(code, dex) {
		return "", false
	}
	return SpritePath + assetFile(dex, code), true
}

// assetFile builds the mined asset filename for a (dex, code): pm25.cANNIVERSARY.s.icon.png.
// The code carries its own prefix ("c:" overlay or "f:" full form).
func assetFile(dex int, code string) string {
	p, name, _ := strings.Cut(code, ":")
	return "pm" + strconv.Itoa(dex) + "." + p + name + ".s.icon.png"
}

// AllowedFile reports whether a requested sprite filename is one the catalog can actually
// produce. The proxy MUST gate on this: without it the endpoint would fetch arbitrary paths
// from the origin on demand, which is an open proxy.
func AllowedFile(name string) bool {
	rest, ok := strings.CutPrefix(name, "pm")
	if !ok {
		return false
	}
	dexStr, rest, ok := strings.Cut(rest, ".")
	if !ok {
		return false
	}
	dex, err := strconv.Atoi(dexStr)
	if err != nil {
		return false
	}
	body, ok := strings.CutSuffix(rest, ".s.icon.png")
	if !ok || len(body) < 2 {
		return false
	}
	code := string(body[0]) + ":" + body[1:]
	return covers(code, dex)
}

// OriginURL is where the proxy pulls a sprite from on a cache miss. The base is pinned to the
// asset commit the catalog was synced from, so the bytes at this URL never change.
func OriginURL(name string) string {
	return cat.AssetBase + name
}

// Unlabelled lists the costumes the game has that no label points at, and that are not
// deliberately hidden. Each is inert: with no label it can never be offered in the picker or
// typed by a trainer, so this list IS the backlog of costumes nobody can record yet.
//
// It reads the MERGED label set, so a costume named through the admin panel drops out of the
// backlog immediately. No network.
func Unlabelled() []Unnamed {
	l := labels()
	labelled := labelledCodes()
	hidden := map[string]bool{}
	for _, h := range l.Hidden {
		hidden[h] = true
	}

	var out []Unnamed
	for code, e := range cat.Codes {
		if labelled[code] || hidden[code] || len(e.Dex) == 0 {
			continue
		}
		out = append(out, Unnamed{
			Code:      code,
			Pretty:    e.Pretty,
			Suggested: e.Suggested,
			Dex:       e.Dex,
			// The sprite is guaranteed servable: AllowedFile gates on catalog membership and this
			// code is in the catalog, so the review tab can never render a broken image.
			SpriteURL: SpritePath + assetFile(e.Dex[0], code),
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Code < out[j].Code })
	return out
}

// labelledCodes is every code a curated or runtime label points at, from the MERGED set. The
// drift check needs it too: a label vouching for a code is what admits a .f code the masterfile
// forgot to flag, exactly as it does when the sync tool builds the catalog.
func labelledCodes() map[string]bool {
	l := labels()
	out := map[string]bool{}
	for _, byLabel := range l.Species {
		for _, code := range byLabel {
			out[code] = true
		}
	}
	for _, s := range l.Shared {
		out[s.Code] = true
	}
	return out
}

// SourceCommit is the mined-asset commit the embedded catalog was built from.
func SourceCommit() string { return cat.SourceCommit }

// LabelsJSON is the MERGED label set, for two callers that must see runtime names:
//
//   - the shiny checklist and trainer templates, which inject it so the browser's copy of the
//     picker knows about costumes named since the last deploy (the TypeScript resolver compiles
//     labels.json in, so without this injection a new name would show on public profiles but not
//     in the picker);
//   - the GitHub sync, which PRs it back into internal/costumes/labels.json.
//
// The output is the embedded labels.json BYTE FOR BYTE, with the overlay's entries appended to its
// "shared" and "hidden" arrays. It is deliberately NOT a re-marshal of the parsed set: labelSet's
// Species and Aliases are maps, so marshalling sorts their keys and destroys the curation the file
// is hand-ordered for, and the encoder HTML-escapes every literal <, > and & in the _comment blocks.
// That once turned a two-line sync into a whole-file rewrite that could not be merged. Since
// rebuildLocked only ever appends to Shared and Hidden, splicing those two arrays is the whole job.
// TestLabelsJSONMatchesTheFileVerbatim pins this.
func LabelsJSON() ([]byte, error) {
	mu.RLock()
	o := ov
	mu.RUnlock()

	// Cloned, not aliased: with no overlay there is nothing to splice, and handing callers the
	// go:embed slice would let one append or write corrupt the embedded file for the whole process.
	out := bytes.Clone(labelsJSON)

	elems := []string{}
	for _, e := range overlayShared(lab.Shared, o.Shared) {
		label, err := json.Marshal(e.Label)
		if err != nil {
			return nil, fmt.Errorf("costumes: marshal label %q: %w", e.Label, err)
		}
		code, err := json.Marshal(e.Code)
		if err != nil {
			return nil, fmt.Errorf("costumes: marshal code %q: %w", e.Code, err)
		}
		elems = append(elems, fmt.Sprintf("{ \"label\": %s, \"code\": %s }", label, code))
	}
	var err error
	if out, err = appendToArray(out, "shared", elems); err != nil {
		return nil, err
	}

	elems = elems[:0]
	for _, code := range overlayHidden(lab.Hidden, o.Hidden) {
		b, err := json.Marshal(code)
		if err != nil {
			return nil, fmt.Errorf("costumes: marshal hidden code %q: %w", code, err)
		}
		elems = append(elems, string(b))
	}
	if out, err = appendToArray(out, "hidden", elems); err != nil {
		return nil, err
	}
	return out, nil
}

// overlayShared returns the overlay entries the embedded set does not already carry.
//
// Nothing prunes the overlay once a sync PR merges: the entry is then in labels.json AND still on
// the server's disk, "redundant-but-identical". Without this filter the merged set would carry the
// label twice, and since the merged set is what the next sync PRs back, each round would append
// another copy. Duplicates within the overlay itself are dropped for the same reason.
func overlayShared(embedded []shared, o []overlayEntry) []shared {
	have := make(map[shared]bool, len(embedded))
	for _, e := range embedded {
		have[e] = true
	}
	out := make([]shared, 0, len(o))
	for _, e := range o {
		s := shared{Label: e.Label, Code: e.Code}
		if have[s] {
			continue
		}
		have[s] = true
		out = append(out, s)
	}
	return out
}

// overlayHidden is overlayShared for the hidden codes.
func overlayHidden(embedded, o []string) []string {
	have := make(map[string]bool, len(embedded))
	for _, code := range embedded {
		have[code] = true
	}
	out := make([]string, 0, len(o))
	for _, code := range o {
		if have[code] {
			continue
		}
		have[code] = true
		out = append(out, code)
	}
	return out
}

// appendToArray splices elems onto the end of the top-level array named key, leaving every other
// byte of raw untouched. elems are raw JSON, already encoded by the caller.
//
// Insertion goes AFTER the last existing element rather than before the closing bracket, so the
// comma always belongs to us and the existing last line is not disturbed. The new lines copy the
// last element's own indent, so the result matches whatever the file already looks like.
func appendToArray(raw []byte, key string, elems []string) ([]byte, error) {
	if len(elems) == 0 {
		return raw, nil
	}

	dec := json.NewDecoder(bytes.NewReader(raw))
	tok, err := dec.Token()
	if err != nil {
		return nil, fmt.Errorf("costumes: read labels.json: %w", err)
	}
	if tok != json.Delim('{') {
		return nil, fmt.Errorf("costumes: labels.json is not a JSON object")
	}

	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return nil, fmt.Errorf("costumes: read labels.json: %w", err)
		}
		name, _ := tok.(string)
		if name != key {
			var skip json.RawMessage
			if err := dec.Decode(&skip); err != nil {
				return nil, fmt.Errorf("costumes: skip %q in labels.json: %w", name, err)
			}
			continue
		}

		tok, err = dec.Token()
		if err != nil {
			return nil, fmt.Errorf("costumes: read %q in labels.json: %w", key, err)
		}
		if tok != json.Delim('[') {
			return nil, fmt.Errorf("costumes: %q in labels.json is not an array", key)
		}

		// Walk to the last element. InputOffset after a Decode is the end of the value just read,
		// and before it the end of the preceding token, so [start, end) brackets the element
		// together with the whitespace in front of it.
		start, end := dec.InputOffset(), dec.InputOffset()
		empty := true
		for dec.More() {
			start = dec.InputOffset()
			var skip json.RawMessage
			if err := dec.Decode(&skip); err != nil {
				return nil, fmt.Errorf("costumes: read %q in labels.json: %w", key, err)
			}
			end = dec.InputOffset()
			empty = false
		}

		lead := "\n  "
		if !empty {
			lead = leadingWhitespace(raw[start:end])
		}
		var b strings.Builder
		b.Write(raw[:end])
		for _, elem := range elems {
			if !empty {
				b.WriteString(",")
			}
			b.WriteString(lead)
			b.WriteString(elem)
			empty = false
		}
		b.Write(raw[end:])
		return []byte(b.String()), nil
	}
	return nil, fmt.Errorf("costumes: labels.json has no %q array", key)
}

// leadingWhitespace returns the newline and indent that seg (an array element preceded by its own
// whitespace) sits behind, so a sibling written after it lines up.
//
// The FIRST newline, not the last: seg opens with the whitespace in front of the element, and the
// element itself may well contain newlines of its own.
func leadingWhitespace(seg []byte) string {
	nl := bytes.IndexByte(seg, '\n')
	if nl < 0 {
		return "\n  "
	}
	i := nl + 1
	for i < len(seg) && (seg[i] == ' ' || seg[i] == '\t') {
		i++
	}
	return string(seg[nl:i])
}

// Codes is the set of costume codes with shiny art, for the admin drift check.
func Codes() map[string]bool {
	out := make(map[string]bool, len(cat.Codes))
	for code := range cat.Codes {
		out[code] = true
	}
	return out
}
