package handlers

// Code generated by scripts/gen-costumes.mjs; DO NOT EDIT.
// Source of truth: ts/shared/costumes.ts (COSTUME_SPRITES + SHARED_COSTUMES).

type costumeCode struct {
	p    string
	code string
}

// species name -> costume label -> {prefix, Niantic code}
var costumeOverrides = map[string]map[string]costumeCode{
	"Pikachu": {
		"Party Hat": {"c", "ANNIVERSARY"},
		"Witch Hat": {"c", "HALLOWEEN_2017"},
		"Santa Hat": {"c", "HOLIDAY_2016"},
		"Holiday Outfit": {"c", "WINTER_2018"},
		"Straw Hat": {"c", "SUMMER_2018"},
		"Detective Hat": {"c", "MAY_2019_NOEVOLVE"},
		"Detective Hat 2023": {"c", "PI"},
		"Flower Crown": {"c", "FEB_2019"},
		"Flower Hat": {"c", "APRIL_2020_NOEVOLVE"},
		"Cake Hat": {"c", "ANNIVERSARY_2022_NOEVOLVE"},
		"Safari Hat": {"c", "SAFARI_2020_NOEVOLVE"},
		"Top Hat": {"c", "JAN_2023_NOEVOLVE"},
		"Red Party Hat": {"c", "JAN_2020_NOEVOLVE"},
		"Rayquaza Hat": {"c", "HOENN_2020_NOEVOLVE"},
		"Charizard Hat": {"c", "KANTO_2020_NOEVOLVE"},
		"Lucario Hat": {"c", "SINNOH_2020_NOEVOLVE"},
		"Umbreon Hat": {"c", "JOHTO_2020_NOEVOLVE"},
		"Meloetta Hat": {"c", "GOFEST_2021_NOEVOLVE"},
		"Cherry Blossom": {"c", "SPRING_2023"},
		"Original Cap": {"c", "ONE_YEAR_ANNIVERSARY"},
		"World Cap": {"c", "COSTUME_1"},
		"New Year's Hat": {"c", "COSTUME_2"},
		"Rock Star": {"f", "ROCK_STAR"},
		"Pop Star": {"f", "POP_STAR"},
		"Libre": {"f", "VS_2019"},
		"Ph.D.": {"f", "DOCTOR"},
		"Clone Pikachu": {"f", "COPY_2019"},
		"Mimikyu Costume": {"f", "FALL_2019"},
		"Flying Pikachu": {"f", "COSTUME_2020"},
		"Cap's Hat": {"f", "HORIZONS"},
		"Kariyushi Shirt": {"f", "KARIYUSHI"},
		"Blue Shirt": {"f", "JEJU"},
		"Green Shirt": {"f", "TSHIRT_01"},
		"Purple Shirt": {"f", "TSHIRT_02"},
		"Batik Shirt": {"f", "TSHIRT_03"},
		"Kurta": {"f", "KURTA"},
		"Saree": {"f", "DIWALI_2024"},
		"Lucas's Hat": {"f", "GOTOUR_2024_A"},
		"Dawn's Hat": {"f", "GOTOUR_2024_B"},
		"Akari's Kerchief": {"f", "GOTOUR_2024_B_02"},
		"Hilbert's Hat": {"f", "GOTOUR_2025_A"},
		"Hilda's Hat": {"f", "GOTOUR_2025_A_02"},
		"Nate's Visor": {"f", "GOTOUR_2025_B"},
		"Rosa's Visor": {"f", "GOTOUR_2025_B_02"},
		"Sun Crown": {"f", "GOFEST_2024_STIARA"},
		"Moon Crown": {"f", "GOFEST_2024_MTIARA"},
		"Malachite Crown": {"f", "SUMMER_2023_A"},
		"Aquamarine Crown": {"f", "SUMMER_2023_B"},
		"Quartz Crown": {"f", "SUMMER_2023_C"},
		"Pyrite Crown": {"f", "SUMMER_2023_D"},
		"Amethyst Crown": {"f", "SUMMER_2023_E"},
	},
	"Pichu": {
		"Santa Hat": {"c", "HOLIDAY_2016"},
	},
	"Raichu": {
		"Santa Hat": {"c", "HOLIDAY_2016"},
		"Original Cap": {"c", "ONE_YEAR_ANNIVERSARY"},
	},
	"Eevee": {
		"Sun Crown": {"f", "GOFEST_2024_STIARA"},
		"Moon Crown": {"f", "GOFEST_2024_MTIARA"},
	},
	"Espeon": {
		"Day Scarf": {"f", "GOFEST_2024_SSCARF"},
	},
	"Umbreon": {
		"Night Scarf": {"f", "GOFEST_2024_MSCARF"},
	},
	"Squirtle": {
		"Sunglasses": {"c", "SUMMER_2018"},
	},
	"Wartortle": {
		"Sunglasses": {"c", "SUMMER_2018"},
	},
	"Blastoise": {
		"Sunglasses": {"c", "SUMMER_2018"},
	},
	"Snorlax": {
		"Nightcap": {"c", "NIGHTCAP"},
		"Studded Jacket": {"f", "WILDAREA_2024"},
	},
	"Slowpoke": {
		"New Year Costume": {"f", "2020"},
	},
	"Slowbro": {
		"New Year Costume": {"f", "2021"},
	},
	"Slowking": {
		"New Year Costume": {"f", "2022"},
	},
	"Jigglypuff": {
		"Ribbon": {"c", "JAN_2024"},
	},
	"Wigglytuff": {
		"Ribbon": {"c", "JAN_2024"},
	},
	"Noibat": {
		"Headband": {"c", "HALLOWEEN_2025"},
	},
	"Noivern": {
		"Headband": {"c", "HALLOWEEN_2025"},
	},
	"Cubchoo": {
		"Holiday Outfit": {"f", "WINTER_2020"},
	},
	"Beartic": {
		"Holiday Outfit": {"f", "WINTER_2020"},
	},
	"Delibird": {
		"Holiday Ribbon": {"f", "WINTER_2020"},
		"Holiday Outfit": {"f", "WINTER_2020"},
	},
	"Spheal": {
		"Festive Outfit": {"c", "HOLIDAY_2021_NOEVOLVE"},
	},
	"Psyduck": {
		"Holiday Attire": {"c", "HOLIDAY_2023"},
	},
	"Gengar": {
		"Halloween Costume": {"f", "COSTUME_2020"},
	},
	"Lapras": {
		"Drip Scarf": {"f", "COSTUME_2020"},
	},
	"Dragonite": {
		"Bowtie & Sunglasses": {"c", "FALL_2023"},
	},
	"Minccino": {
		"Fashion Outfit": {"c", "FASHION_2025"},
	},
	"Cinccino": {
		"Fashion Outfit": {"c", "FASHION_2025"},
	},
	"Shinx": {
		"Fashion Outfit": {"c", "FALL_2020_NOEVOLVE"},
	},
	"Kirlia": {
		"Fashion Outfit": {"c", "FALL_2020_NOEVOLVE"},
	},
	"Gardevoir": {
		"Meloetta Hat": {"c", "GOFEST_2021_NOEVOLVE"},
	},
	"Croagunk": {
		"Fashion Outfit": {"c", "FALL_2020_NOEVOLVE"},
	},
	"Toxicroak": {
		"Fashion Outfit": {"c", "FALL_2020_NOEVOLVE"},
	},
	"Diglett": {
		"Fashion Outfit": {"c", "FALL_2022"},
	},
	"Butterfree": {
		"Fashion Outfit": {"c", "FASHION_2021_NOEVOLVE"},
	},
	"Aerodactyl": {
		"Satchel": {"f", "SUMMER_2023"},
	},
	"Cubone": {
		"Cempasúchil Crown": {"c", "FALL_2023"},
	},
	"Ponyta": {
		"Candela Costume": {"c", "SPRING_2023_VALOR"},
	},
	"Vulpix": {
		"Spooky Festival Costume": {"c", "FALL_2022"},
	},
	"Wurmple": {
		"Party Hat": {"c", "JAN_2020_NOEVOLVE"},
	},
}

type sharedCostume struct {
	label string
	p     string
	code  string
	dex   map[int]bool
}

// costumes shared by one code across many species; dex is the eligible set
var sharedCostumes = []sharedCostume{
	{"Party Hat", "c", "JAN_2020_NOEVOLVE", map[int]bool{1: true, 2: true, 3: true, 4: true, 5: true, 6: true, 7: true, 8: true, 9: true, 20: true, 25: true, 33: true, 94: true, 133: true, 202: true, 265: true}},
	{"Flower Crown", "c", "NOVEMBER_2018", map[int]bool{25: true, 26: true, 113: true, 133: true, 134: true, 135: true, 136: true, 172: true, 196: true, 197: true, 242: true, 440: true, 470: true, 471: true, 700: true}},
	{"Cherry Blossom", "c", "SPRING_2023", map[int]bool{25: true, 26: true, 133: true, 134: true, 135: true, 136: true, 172: true, 196: true, 197: true, 470: true, 471: true, 700: true}},
	{"Holiday Wreath", "c", "HOLIDAY_2022", map[int]bool{133: true, 134: true, 135: true, 136: true, 196: true, 197: true, 470: true, 471: true, 700: true}},
	{"Sunglasses", "c", "SUMMER_2018", map[int]bool{7: true, 8: true, 9: true, 25: true, 26: true, 172: true}},
	{"Flower Hat", "c", "APRIL_2020_NOEVOLVE", map[int]bool{25: true, 175: true, 176: true, 427: true, 428: true, 468: true}},
	{"Fashion Outfit", "c", "FALL_2020_NOEVOLVE", map[int]bool{238: true, 281: true, 403: true, 453: true, 454: true}},
	{"Witch Hat", "c", "HALLOWEEN_2025", map[int]bool{216: true, 217: true, 714: true, 715: true, 901: true}},
	{"Holiday Attire", "c", "HOLIDAY_2023", map[int]bool{25: true, 26: true, 54: true, 55: true}},
	{"Winter Hat", "c", "WINTER_2024", map[int]bool{702: true, 831: true, 832: true}},
	{"Meloetta Hat", "c", "GOFEST_2021_NOEVOLVE", map[int]bool{25: true, 282: true, 330: true}},
}
